### ISSUE TITLE
consistent End of File Error

### ISSUE THREAD

**Issue by tunnels** [z411/trackma#100]
I've been using this for a week or so, and for some reason, trackma will fail to start after a few days of usage. I'm on OS X.

Here's the traceback
```
Traceback (most recent call last):
  File "/usr/local/bin/trackma", line 9, in <module>
    load_entry_point('Trackma==0.3', 'console_scripts', 'trackma')()
  File "/Library/Python/2.7/site-packages/trackma/ui/cli.py", line 614, in main
    main_cmd.start()
  File "/Library/Python/2.7/site-packages/trackma/ui/cli.py", line 95, in start
    self.engine.start()
  File "/Library/Python/2.7/site-packages/trackma/engine.py", line 176, in start
    (self.api_info, self.mediainfo) = self.data_handler.start()
  File "/Library/Python/2.7/site-packages/trackma/data.py", line 127, in start
    self._load_meta()
  File "/Library/Python/2.7/site-packages/trackma/data.py", line 464, in _load_meta
    loadedmeta = cPickle.load( open( self.meta_file , "rb" ) )
EOFError
```

after this I've just been deleting my .trackma config directory and relogging into mal, then it's fine again for a few days before it breaks again. Just in case this comes in handy, here's the initialization log
```
Initializing engine...
Engine: Trackma v0.3 - using account tunnels(mal).
Engine: Reading config files...
Data: Initializing...
libmal: Initializing...
Data: Using libmal (anime)
```

**Comment by tunnels** [comment]
just tested it out to see which of the files was responsible, and it's .trackma/[account].mal/anime.meta. deleting it fixes trackma without having to delete the other config files. Something to note is that it was an empty file before I removed it, but after I removed  it, it regenerated a working anime.meta file which had actual content

**Comment by z411** [comment]
Thank you for your report; an user had a similar user in this issue #62 - I've never been able to reproduce it, but I suspect it might a bug that happens in some systems when Trackma is closed by a term or kill signal (like, when shutting down). I specifically Have you been able to note if this happens in that specific case, or randomly?

Anyway, I'm removing any code that might be writing things at exit.

**Comment by tunnels** [comment]
Actually yes, I just reproduced the error by opening trackma in two different terminal sessions and closing both windows rather than cleanly using "quit", and the anime.meta file was corrupted.

**Comment by z411** [comment]
I see, that helps a lot, thank you very much. I just removed the code that I suspect it's making it attempt to write to the file. Could you re-pull and try again? And does it happen only with 2 or more terminal sessions?

**Comment by tunnels** [comment]
It's still happening, and It only happens when I open multiple terminal sessions. And as you say, it only happens when I close the term windows rather than using trackma's quit command.

**Comment by tunnels** [comment]
It's actually almost impossible to get this behavior now, I'm basically forcing it to happen and even then I'm getting almost no results. Before I could consistently force it to happen, but now I've only gotten this behavior once, even after doing it some several dozen times. I'll report back if it occurs again during regular usage.
