### ISSUE TITLE
Arguments

### ISSUE THREAD

**Issue by GRMrGecko** [z411/trackma#103]
It would be nice to have arguments to choose which account to load at start. I have 3 accounts I am using Trackma for and I essentially have to have 3 terminal tabs open and choose my account on each instence. I would like to be able to write a bash script to open all 3 at one time using -a 1, -a 2, -a 3 or something like that.

Ether that, or change this to a multi account sync request. I do not know much about python, if I did I would help with this.

**Comment by GRMrGecko** [comment]
Maybe something similar to the request at https://github.com/z411/trackma/issues/79

For something like this, https://github.com/z411/trackma/issues/72 why noy just have it load multiple windows/sessions at start?

**Comment by Argon-** [comment]
> For something like this, #72 why noy just have it load multiple windows/sessions at start?

So you basically "operate" on both at the same time when you e.g. update an episode? This sounds like a neat solution to #72.
One would have to deal with inconsistent lists, e.g. when episode A is within one account's list but not in the others, but this shouldn't be that much of a problem. Updating such an episode will simply update it for whichever account the show contain and the GUI could add some kind of tag/hint to visualize in which account's list it's missing (as I assume mirrored lists are desired by the user, at least they are by me).

**Comment by GRMrGecko** [comment]
Depending on the user, mirrored lists is desired. At least for some shows. For example, some people may want to not list R18 shows on one network, but are ok with doing so on another.

**Comment by z411** [comment]
The tracker wouldn't have a problem doing this, as the tracker does a fuzzy search on the list to guess what show it should update based on the title, so it would just do the same for all the accounts.
But what if I want to change the episode, or the score, or the status, of a show manually? The only plausible workaround I can think of is, when a manual change is done to a show in the main account (for example change the score), do a fuzzy title search in the secondary account and try to apply the same change in the secondary account, and silently fail it it can't find it. But there's also the problem of different sites having different scoring systems, for example; or different statuses.

**Comment by Argon-** [comment]
Imo this would be fine as long as the user knows which account is master.
