### ISSUE TITLE
<class 'trackma.utils.APIFatal'>: Connection error: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by MellonQ** [z411/trackma#107]
Is trackma's UA banned by MAL or something?
I have just stolen the UA from Taiga, and the trackma is working fine with it.
I guess something like that is not a very good idea... :3

**Comment by z411** [comment]
It's working fine for me. Does it still happen?

**Comment by MellonQ** [comment]
Now it's working with the UA of trackma  very well for me too ^_^ Maybe there were some troubles with my subnet
Thx
