### ISSUE TITLE
trackma-qt displays wrong Trayicon in KDE

### ISSUE THREAD

**Issue by Frozen-byte** [z411/trackma#108]
I am using Kubuntu 14.04 with Plasma Desktop and sadly the tray icon of your awesome App is not displayed [Look at the second Icon](http://a.pomf.se/jthwqt.png)
The Application Icon is [Displayed correctly](http://a.pomf.se/pmdvrj.png)

Tell me if you need any Logs/Informations I am willing to help!

**Comment by veluria** [comment]
Works fine for me (fresh install): http://abload.de/img/snapshot14durn.png

**Comment by z411** [comment]
It works for me too. Are you sure it's enabled in the UI settings?

**Comment by Frozen-byte** [comment]
Of course I made a tick at Settings->Show tray icon
I guess the problem belongs to my System then and is not caused by your Application.

Anyway if you know any methods to pin down the issue I would be glad.

**Comment by lolihunter** [comment]
I have this same issue using the default Breeze icon theme on my laptop, running Plasma on Arch.

**Comment by Frozen-byte** [comment]
Fresh re-install and it got even worse =(
System: Kubuntu 15.10
Installed via: python2-pip
Running: trackma-qt 
Displays as: http://i.imgur.com/WzTtyQW.png
The green Icons should be the Trackma one.
On the bottom screen the second (gray document) should display the Trackma icon.

**Comment by z411** [comment]
I'm assuming this occurs only on KDE Plasma? I'm assuming it has to do with using Qt 4.

**Comment by Frozen-byte** [comment]
Indeed, switched to QT5 now the icon shows up.
