### ISSUE TITLE
Trackma: No images in KDE Opensuse

### ISSUE THREAD

**Issue by JeroenMathon** [z411/trackma#110]
Screenshot: http://i.imgur.com/DEYakXv.png

Traceback:
Data: Locking database...
Data: Reading metadata...
Data: Reading cache...
Tracker: Initializing...
Tracker: Enabling tracker...
Tracker: inotifyx not available; using polling (slow).
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/Trackma-0.3-py2.7.egg/trackma/ui/gtkui.py", line 983, in run
    im = Image.open(img_file)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 2256, in open
    % (filename if filename else fp))
IOError: cannot identify image file <cStringIO.StringI object at 0x7f0711d9a360>

**Comment by z411** [comment]
I can't seem to reproduce the problem, but I might try in an Opensuse VM.
It seems the image wasn't downloaded at all, or corrupted.
Have you tried the Qt interface? Does it happen with other sites too?

**Comment by JeroenMathon** [comment]
The problem is that it does not download the picture.
It seems to be the PIL library thats missing.
Ill try to install it see if the problem still occurs.
(I think i tried this before and the problem still occured)

**Comment by z411** [comment]
No I think it is installed since the error occurs in one file of the PIL module.
When the PIL library isn't installed you get a warning and Trackma just doesn't attempt to download them.
Do you have any files in the ~/.trackma/cache directory?

**Comment by JeroenMathon** [comment]
The cache directory is empty.
Here i got the debug output.
I tried both interfaces, Same result

Data: Locking database...
Data: Reading metadata...
Data: Reading cache...
Tracker: Initializing...
Tracker: Enabling tracker...
Tracker: inotifyx not available; using polling (slow).
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/Trackma-0.3-py2.7.egg/trackma/ui/gtkui.py", line 983, in run
    im = Image.open(img_file)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 2256, in open
    % (filename if filename else fp))
IOError: cannot identify image file <cStringIO.StringI object at 0x7f89ac66a360>

**Comment by JeroenMathon** [comment]
This issue is consistent with OpenSuse Plasma 5.
And is now distribution wide.

**Comment by z411** [comment]
Thanks for the report. I really can't reproduce the issue; I will try installing OpenSUSE in a VM and try it there to see what's the exact issue.

**Comment by z411** [comment]
Hello, I finally could test it (I had trouble installing the latest stable OpenSUSE so I had to go for Tumbleweed).

It seems there was a conflict with versions; I made a change that fixes it on my end, please tell me if it works.
