### ISSUE TITLE
portage for sailfishOS

### ISSUE THREAD

**Issue by newincpp** [z411/trackma#118]
I just downloaded and tested trackma, it work pretty well ! I love it !

So I'd love to see it on my phone which it a jolla phone: https://jolla.com
this phone run Sailfish linux which is a genuine linux with a special architecture and display manager designed for phones.
You can make a SailfishOS app using this SDK https://sailfishos.org/develop/
and this https://github.com/thp/pyotherside (because trackma is in python)

If you are lost you can still ask to the community which will be very happy to answer you: https://together.jolla.com/questions/

You will be awesome if you do this ! =D

**Comment by Argon-** [comment]
How is he supposed to test, maintain and support this in general without such a phone? This is basically a prerequisite unless you consider testing in a VM as sufficient (it's not for e.g. android apps).

**Comment by newincpp** [comment]
For 80% of the dev a VM is sufficient, and for the test on the phone the (very) active community will help.
They can test for you or I even saw for an app named "saera" that the dev just ask to the community to buy a phone to finish the developing process (the project was 204% founded)
