### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by soredake** [z411/trackma#120]
It will support python3?

**Comment by z411** [comment]
Yes, I'm planning to move to Python 3 and maybe Qt 5 when they get a bit more widespread, probably soon.

**Comment by veluria** [comment]
Ubuntu is going to switch to Python 3 as default interpreter in the next release, but all distros have been having it in their repos for quite some time now. Qt 5 still has an annoying bug that the tray icon does not work on Linux (it apparently appears at some random position, but not where it should be). The bug has been marked as resolved for 5.5 in the bug tracker. I haven't checked whether it's also included in 5.4.2, which has just been released.

**Comment by rr-** [comment]
@z411 I'm willing to work on Python 3 version if you'd like to.

**Comment by Frozen-byte** [comment]
I am interested in a python3/qt5 version, too.

**Comment by Birdulon** [comment]
After catching a bit of unicode nonsense switching between QStrings and strs in the filter code, I'm interested in Python 3, too. I'm still clinging to Qt4 as long as I can though. My understanding is that PyQt4 can be built against Qt5 if need be, so Trackma should be able to run on Qt5 with no modifications.

**Comment by veluria** [comment]
It needs a few modifications to run on Qt5: https://github.com/veluria/trackma/commit/fc48e6e46efd0309bb7d2bc52cd76648c436878a

**Comment by z411** [comment]
Oh you're working on it @veluria , thank you. I think we should be switching very soon; I was clinging to Python 2 because of urwid but it seems it supports Py3 by now.
Are there any reasons you would prefer to cling to Qt4, @Birdulon ?

**Comment by veluria** [comment]
My branch is kinda old and it's probably easier to redo this, seeing as to how many things have changed in the meantime. There is a helper script, pyqt4topyqt5, which does most of the work. Just a few additional fixes needed, pretty easy to track down with the exceptions. :)

**Comment by Birdulon** [comment]
Just removed the ubuntu version of PyQt4 and built it from source (v4.11.4) on my laptop under KDE5, can confirm that the current version of trackma will run unmodified on Qt5 without needing to switch to PyQt5.
![trackmaqt5pyqt4](https://cloud.githubusercontent.com/assets/5397662/13601887/0a436714-e583-11e5-814c-a8fcb84c0ea6.png)
That said, most users won't want to build PyQt4 and all the compiled packages I've seen are built against Qt4 so if there are problems with the default experience on Qt5 I'm not against moving to PyQt5.

@veluria Having briefly looked at the changes in that commit, it looks to me that there's only a few method changes and most of it is just a namespace change. Perhaps it would be possible to support both PyQt4 and PyQt5 in the same version by importing from the namespaces and adding checks on the few lines with different method names?

@z411 entirely personal reason, I use KDE4 on my development & primary anime machine as KDE5 is not at feature parity yet and has had some workflow-interrupting bugs. For whatever reason Qt5 applications don't use the system theme properly on there despite my best efforts. With the upcoming 16.04 LTS I'll give KDE5 another shot on there.

**Comment by veluria** [comment]
I didn't test everything, but most stuff works: https://gist.github.com/veluria/c041aa2d912c819ec67d

![screenshot from 2016-03-08 14-18-17](https://cloud.githubusercontent.com/assets/1119538/13602890/b2302f10-e539-11e5-8f72-3bba87ff1d6b.png)

**Comment by Birdulon** [comment]
I should rewrite the filter code to use python strings anyway, to reuse it in the other GUIs. It should be a bit cleaner in python3!

**Comment by Birdulon** [comment]
After importing all of the used classes (which have moved modules in pyqt5) into the namespace, here's the remaining changes that pyqt4topyqt5 picked up: https://gist.github.com/Birdulon/496b831eed29a4c6f81a

I believe it would be reasonable to support both pyqt4 and pyqt5 from a single codebase this way, with only a handful of version checks within the code, and perhaps an option in the settings for enabling Qt4 (default to pyqt5 if available).

**Comment by veluria** [comment]
Changes I made manually:

    apiname = self.api.itemData(index)
    index = action.data()

And this was removed:

    self.contents.layout().setMargin(0)

Also the QString for the filter tooltip.

**Comment by Birdulon** [comment]
Thanks @veluria, here's my attempt at it: https://github.com/Birdulon/trackma/tree/Qt5
Didn't get to test anything with the tracker in pyqt5 mode but I couldn't find any more errors poking around the UI.
