### ISSUE TITLE
Add support for streaming detection

### ISSUE THREAD

**Issue by veluria** [z411/trackma#122]
I'm opening this “issue”, because I think this is a great feature Trackma is still missing. Taiga, for example, is able to recognize when you are playing a stream in your web browser (Crunchyroll, DAISUKI...). I did implement a similar behaviour in Trackma a while ago, using the following approach:

* List all windows with their titles using `wmctrl`
* Filter them for browsers specified
* See if the titles matched a certain regex (for example, all videos on Crunchyroll start with “Crunchyroll - Watch”)
* Extract all the information using the regex and pass them to the to the tracker

This worked quite well, but it has its downsides:

* Works only on Linux, X11 even
* Requires polling (I don't think there is anything that can be done about this, though)
* Resets the timer when the user changes the current tab (and thus the window title)

Any ideas about a better approach?

**Comment by z411** [comment]
Did you commit your work into your fork?

> Resets the timer when the user changes the current tab (and thus the window title)

I see, I would assume Taiga also uses the window title to detect the streaming show, does this also occur in Taiga when you change the tab? I would be wary of security decisions if browsers let random programs to read the titles of the open tabs.

**Comment by veluria** [comment]
>Did you commit your work into your fork?

Unfortunately, I lost my work due, let's say, technical issues? At any rate, I can write what I had again.

>I see, I would assume Taiga also uses the window title to detect the streaming show, does this also occur in Taiga when you change the tab? I would be wary of security decisions if browsers let random programs to read the titles of the open tabs.

Taiga is not only able to use all the tab titles but also the URL. https://github.com/erengy/taiga/blob/master/src/track/media_stream.cpp

**Comment by veluria** [comment]
You can see my work [here](https://github.com/veluria/trackma/commit/a90be2aa0c21015690aecc00d9932c97c1d064a6). There are some things I'm not so sure about:

* Where to do this and when to do this. Right now, the trackers tries to look for the browser title when it couldn't detect an open file. The resulting “filename” still gets passed to the extractor, which is unnecessary, but not a big deal either, I suppose.
* Using a shell to do the processing of `wmctrl`'s output. It's very easy to handle it this way, and `wmctrl`'s  output is clearly defined in its man page, but it might be better to do the parsing in Python.
* The default config provides the regular expressions to parse the window titles. This is nice, because it should be easy for a user to add a new one for whatever streaming services they use. On the other hand, it also makes it impossible to update regular expressions or to add new ones from upstream once the config file has been written.

Right now, there is no way to handle these options through any of the GUIs. I could add options to the Qt interface once we've settled on a solution.

**Comment by z411** [comment]
For the first point, there are already two types of tracker currently implemented, "local" and "plex", which is chosen through the "tracker_type" option in the config. Depending on this, it calls a different "observe_*" function in tracker.py when the tracker starts. To keep it consistent, the streaming tracker should be just another tracker type. Therefore we would end up with 3 tracker types (and 3 observe functions), local, streaming and plex.

I'm not sure if what Taiga does can be done in an X environment, will investigate that.

**Comment by veluria** [comment]
> To keep it consistent, the streaming tracker should be just another tracker type. Therefore we would end up with 3 tracker types (and 3 observe functions): local, streaming and plex.

But that would make it impossible to have two at the same time, wouldn't it? And just because someone watches streams, it doesn't mean he doesn't have any local file, for example. No idea about Plex, since I've never used it before.

**Comment by z411** [comment]
Right. Have you tried this with inotify? Because when inotify is enabled `_get_playing_show` gets called only when there's an event.

**Comment by veluria** [comment]
No, you're right. I didn't consider that. For the current approach to work, polling is required, but if we do two things simultaneously, they might end up interfering with each other. And spawning another process might not be a good either. What do you propose?

**Comment by z411** [comment]
Trackma already runs the tracker in a separate thread (spawned in engine.py), so it should be trivial to modify it so it creates a new tracker instance for each enabled tracker type, letting us run different trackers simultaneously.
I'm more concerned about how changing the tab would reset the timer. Will look into it. Thanks.

**Comment by veluria** [comment]
I'm not interested in this any more, so if you don't plan on working on this, feel free to close it. :)
