### ISSUE TITLE
Package for Fedora

### ISSUE THREAD

**Issue by dyskette** [z411/trackma#128]
So, I've been packaging trackma for my personal use since a few months ago on Fedora. And now I made this [copr repo](https://copr.fedoraproject.org/coprs/dyskette/trackma/) for anyone who wants to use it.

**Comment by z411** [comment]
Thanks. Added to the readme.

**Comment by Mrfiregem** [comment]
Are you planning to update this for Fedora 39?

**Comment by dyskette** [comment]
@Mrfiregem I rebuilded the package for F39.

Looking back... 8 years already, huh
