### ISSUE TITLE
hotkeys

### ISSUE THREAD

**Issue by anjandev** [z411/trackma#129]
could we add hotkeys like ctrl + n playing the next episode?

I tried taking this guy's code:
https://gist.github.com/seanh/555602

and turning it into something we could use for gtkui.

```python
    # Hotkeys
        self._window.connect("key-press-event",self._key_press_event)
        def _key_press_event(self,widget,event):
            keyval = event.keyval
            keyval_name = gtk.gdk.keyval_name(keyval)
            state = event.state
            ctrl = (state & gtk.gdk.CONTROL_MASK)
            if ctrl and keyval_name == 'n':
                self.do_play()
```

I added this into gtkui.py and tried to get gtkui to play nice with it but I dont know anything about how the rest of the code is structured. Perhaps you guys with more experience could make it work?

**Comment by z411** [comment]
GTK already supports accelerators so it's not necessary to implement it at the key event level.
I just added some accelerators in the GTK interface, including the <Ctrl>N you suggested.
Tell me if you want to add more or change them. If they're fine, I'll replicate them in the Qt interface.

**Comment by anjandev** [comment]
Thank you! I really missed this from taiga.

**Comment by anjandev** [comment]
yup, gtk's hotkeys work really well.

**Comment by z411** [comment]
Also added Ctrl-Left, Ctrl-Right to change the episode.
Replicated everything in Qt.
Considering this fixed.
