### ISSUE TITLE
Right click > Play episode # / Status: rewatching

### ISSUE THREAD

**Issue by anjandev** [z411/trackma#132]
It would be nice to be able to right click a show and select an episode to watch like you can with taiga. Watching episodes from something that you have copmpleted is very cumbersome with the current ui. 

Similarily, it would be nice to add a rewatching status.

**Comment by z411** [comment]
I see, I haven't checked but what happens when a show has 100+ episodes? Is it a scrolling list?

**Comment by anjandev** [comment]
I think so, if u would move ur mouse to the lower part of the list, it would scroll.

**Comment by z411** [comment]
This was implemented in the GTK interface. Please tell me if this is what you wanted so I can implement it in the Qt interface too. Any other suggestions to improve the (currently clunky) interfaces are also welcome.

**Comment by anjandev** [comment]
well, taiga recently changed their select episode to play option to look like this:
![trackma](https://cloud.githubusercontent.com/assets/8602360/9692991/bd911696-5301-11e5-84b7-201bacf2f0a6.png)
I feel like this is a better ui choice than one giant scrolling list.

**Comment by veluria** [comment]
@z411 
There is a logic error in your code.

    for i in xrange(1, show['total']):

Should be

    for i in xrange(1, show['total'] + 1):

instead.

**Comment by z411** [comment]
You're right @veluria, thank you.

**Comment by z411** [comment]
This was implemented in Qt by Birdulon.
For the rewatching status refer to #141
