### ISSUE TITLE
Open containing folder for anime / Deleting anime

### ISSUE THREAD

**Issue by anjandev** [z411/trackma#133]
It would be nice to add an option to ask the user if they want to delete the entire anime's folder from their hard drive when the show is right clicked or when the show is deleted from the list. It would allow one to keep their anime folder under control and use less space. It's hard to look through a giant folder with files everywhere.

**Comment by ToostInc** [comment]
Isn't that more a job for the user to keep his folders organized though?
Similarly, this organization will really differ per person, and will be hard to get working safely. Deleting files based on a regexp pattern seems very unsafe.

**Comment by anjandev** [comment]
I mean updating hummingbird/MAL is a job for the user but we have taiga automate that cause we are lazy. I think opening thunar/nautilus/ranger and asking to confirm if that was the right folder would be a nice remedy to the problem of having a mistake. There's not many ways to organize anime. Most people do it like ./anime/series_title

**Comment by ToostInc** [comment]
Or everything in a large map called anime, or an even larger map(/partition) called media. Or a folder for every episode... 

It's best to let the deletion of files up to the user really, but if https://github.com/z411/trackma/issues/117 becomes a thing, you can use that to delete the files.

**Comment by dyskette** [comment]
> It would be nice to add an option to ask the user if they want to delete the entire anime's folder from their hard drive when the show is right clicked

I think this is out of the scope of trackma. Altering local files should be left to their respective tools. 

Trackma is handling online lists, that are not tied to local files. You could be syncing between different machines, have external hard drives well organized or everything in the "Downloads" folder.

> or when the show is deleted from the list.

Is this usecase often?

**Comment by z411** [comment]
Indeed; besides what's been said, I wouldn't want Trackma to go around the user's hard disk deleting files...

**Comment by anjandev** [comment]
When I right click an anime, could you add an option in the gui to view containing folder? When clicked, this would open the folder in which trackma thinks the show is stored. The user then can delete the show manually through the file manager of their choice.

**Comment by z411** [comment]
> When clicked, this would open the folder in which trackma thinks the show is stored
How could Taiga guess this? What about the location of the latest episode?

**Comment by anjandev** [comment]
I assume thats it. If the show has never been played before, trackma could use the search engine to find the episode #1's directory and assume that that is where all the episodes are stored. 

I am assuming taiga makes a database for where the shows' folders are. If the folder no longer exists where the database says it is, taiga searches for the show in the folders and updates the database.

**Comment by anjandev** [comment]
I think this issue can be reopened.

**Comment by z411** [comment]
Currently Trackma scans the directory and caches the path of each episode individually.
As far as I know, recording specifically a directory for a show is used by Trackma for its torrent function; I don't think it'd be necessary for now.

I think your suggestion of either using the latest episode, or the first episode, sounds good.

**Comment by z411** [comment]
Open Containing Folder has been implemented.

**Comment by anjandev** [comment]
This feature hasn't been implemented in the other uis. I think we should keep parity in the features list across uis

**Comment by anjandev** [comment]
@z411 this issue can be closed as it has been implemented in all uis.
