### ISSUE TITLE
More options for auto-detected shows

### ISSUE THREAD

**Issue by anjandev** [z411/trackma#136]
So when I enable the auto update feature, it will send the update when Im not finished watching the show. It would be nice to have more control over this. Suchas adding an option to ask to confirm update to list once an auto-detected episode has been closed.

**Comment by z411** [comment]
Hello, the options you suggested were implemented in the Qt, GTK and curses interfaces. You might want to take a look (they are in the Settings dialog, Wait for the player to close and Ask before updating).

**Comment by anjandev** [comment]
that option works for shows that I play through trackma by right-clicking Play. However, even though I have that enabled, it does not work for shows I open through the file manager and trackma detects is playing. This is from the gtk interface by the way.

**Comment by z411** [comment]
That's weird, it's working for me.
What message does it appear in the status bar of the interface when the show is detected (when you open it in your file manager)?

**Comment by anjandev** [comment]
I just git cloned the latest release. I think it's fixed.
