### ISSUE TITLE
Visual indicator of new episodes

### ISSUE THREAD

**Issue by benbarclay** [z411/trackma#137]
This is a nice to have, but in the UI for MAL Updater (windows) there is a somewhat more granular status bar.

From memory it:
- highlights the % watched in blue (similar to the current GTK interface)
- then it highlights in grey any episodes that it finds on disk but are unwatched
- then it uses a light grey to indicate aired episodes that it cannot find on disk
- then it goes white to indicate unaired episodes

I used to find the grey indicator of unwatched episodes on disk a handy reference. I'm not sure how this would translate into all the other interface types (like the curses interface), but it might be a handy feature for the GUI interfaces.

**Comment by z411** [comment]
Good timing because I was actually in the way of implementing this. It's already done in the engine and Qt interface (thanks to how easy it is to make custom widgets). I have to look into how to do it in the GTK interface.
For the curses interface, I guess a numeric display of the latest aired episode and available episode should be enough?

**Comment by Argon-** [comment]
Or maybe add some little symbol to the title, a `+` or `*` behind/in front of the title. Just an idea that occurred to me, not sure what provides the best UX.

**Comment by z411** [comment]
Hello, this is currently implemented in the Qt interface in the `libraryscan` branch. You might want to test it. Make sure to go to List -> Rescan library (I plan to make this automatic later), and the available episodes should appear indicated in the progress bar.

>Or maybe add some little symbol to the title, a + or * behind/in front of the title. Just an idea that occurred to me, not sure what provides the best UX.
The curses interface currently colors the row orange when the next episode is available, should I keep that?

**Comment by z411** [comment]
Implemented in GTK.

**Comment by benbarclay** [comment]
I'll give this a test tonight

**Comment by benbarclay** [comment]
Nice! The GTK version works well.

**Comment by z411** [comment]
Great. Implemented orange row color in curses.
Merged to `master`.
