### ISSUE TITLE
Some password gets http error 401 on auth

### ISSUE THREAD

**Issue by soredake** [z411/trackma#138]
```
libmal: Logging in...
Data: Info: Connection error: HTTP Error 401: Unauthorized
```

**Comment by fenque** [comment]
http://myanimelist.net/forum/?topicid=1423799

**Comment by z411** [comment]
I wasn't aware of the issue.
I'm skeptical of them ever fixing this issue upstream, honestly.

**Comment by fenque** [comment]
I understand, maybe you just need to add a warning when 401 with the explanation that it is probably a problem with the password?

**Comment by z411** [comment]
Indeed, something like a "Unauthorized. Please check your username and password. Please note that you might also be getting this error if you have non-alphanumeric characters in your password due to an upstream MAL bug (#138)." would be fine?

**Comment by fenque** [comment]
Yes, it will be a little better, thank you.
