### ISSUE TITLE
CLI is badly designed

### ISSUE THREAD

**Issue by bradenbest** [z411/trackma#139]
The CLI interface is poorly designed and needs to be re-done. 

As someone who uses (and designs his own) CLI interfaces for 99% of his work, I can confirm that the interface is unintuitive and clunky (I've designed better CLIs in bash in < 100 lines of code, cli.py is 700 lines, so it's in no way a complex problem). 

The lack of documentation on the "undocumented" commands is unacceptable. A lot of this could be fixed by simply making it easier to read.

For example, the prompt line 

    MyAnimeList(anime) Watching> help

could be changed to look like 

    [mal] (anime) watching >> help

Already a lot easier to read. Add some colors in there and you have a winner. Just make sure to define a set of "non-colors" for terminals that can't handle color.

The biggest issue is with documentation, though. The ls-style help listing is ugly and cognitively difficult to navigate. An easier and better way to do it is to list it like an index

    command   args          description
    -----------------------------------
    com1      <name, val>   does thing
    com2      <none>        does other thing
    ...

By keeping it simple, you let the user figure it out, and make it impossible for yourself to be lazy enough to "not document" a command. That makes it intuitive, rather than frustrating. 

Also, for the sake of readability, I've found that vertical listings benefit a lot from maintaining a margin of at least two spaces between columns. Designing a CLI takes a lot of sitting back to take in the information, just as much as you do when designing a GUI. A good CLI conveys information quickly and efficiently with little to no parsing effort on the user's end. A bad CLI has to be studied like a map before the user can decipher what's going on.

Design can make or break a CLI, and because of the current CLI, I was actually turned off of this program for several months (until I found out it had a gtk interface).

Just keep in mind that we already use one CLI: bash. We don't want to have to memorize a whole 'nother command line just for one specific task.

**Comment by bradenbest** [comment]
Here's an example:

Currently, the CLI looks like:

    MyAnimeList(anime) Watching> help

    Documented commands (type help <topic>):
    ========================================
    account  delete  help  mediatype  score   sort    undoall
    add      filter  list  quit       search  status  update 

    Undocumented commands:
    ======================
    EOF  info  neweps  play  retrieve  send  track  viewqueue

    MyAnimeList(anime) Watching> help sort

            sort - Change sort
            
            Usage: sort <sort type>
            Available types: id, title, my_progress, total, my_score
            
But here's an example of what it *could* look like:

    [mal] (anime) watching >> help

    command    args      description
    ---------------------------------------------------------------------
    account    (none)    connect or switch to an account
    add        pattern   search for <pattern> and add it to list
    delete     id/title  delete a show from the list
    EOF        ????????  Whatever EOF does
    filter     type      change the filter. e.g. watching. If no 
                         <type>, a list of available filters will display
    help       (none)    display this help text
    info       lorem     ispum dolor sit amet
    [...]

That's a lot less clutter.

**Comment by Argon-** [comment]
>I've designed better CLIs in bash in < 100 lines of code, cli.py is 700 lines, so it's in no way a complex problem

I'm sure this project is happy about pull requests.

**Comment by bradenbest** [comment]
> I'm sure this project is happy about pull requests.

I would love to, except ...

1. I'm not the one who should be writing documentation. That's the responsibility of the developer, @z411 . Besides, I have no idea what half of the functions do (specifically, the undocumented ones). Mr. z411, however *does* know what they do.
2. I've never merged/pulled with git, so I have no idea how to use that functionality.

If you want me to fix up the CLI, then please provide me with a table of each user-callable function, what they do, and what arguments they take. Do that, and I'll make a beautiful CLI for you.

**Comment by z411** [comment]
It seems you're using an old version. All commands have been documented for a good time now. Please clone from master.

The CLI (and thus, the help command and formatting) is actually handled by the Cmd Python module; it's not me who designed the way the help command is displayed. If we want to change that we'd either have to re-implement the help command to show it as you suggest, or reimplement the whole CLI handling from scratch. Either way it requires more LOC.

**Comment by bradenbest** [comment]
@z411 Thanks for replying. 

Okay, so I cloned the repo and installed, but the CLI still has the problems I mentioned before. EOF is still undocumented, despite being a trivial function (typing EOF or Ctrl+D both make it quit). 

At the very least, I would like to see the `help` command list the commands in a column with a short description for each command. That's infinitely more useful than a flat list of the possible commands without any elaboration. I assume the module handles outputting for `help <command>` but the listing for `help` by itself is just a regular `print` statement.

To better illustrate what I think would help the CLI interface, here's a screenshot of a few different help screens:

![image](http://i.imgur.com/tlAVoZr.png)

* The bottom right quadrant shows git's own `--help` output
* The upper right quadrant shows the output of `h` in my own program, qwatch.
* The left hand side shows the detailed help from the command `help:commands`

As you can see, I've put a hell of a lot of work into the help for qwatch. Perhaps I'm a little more meticulous about documentation than the average developer (and maybe a little more insane, too, for writing 1,000 lines of bash just to manage videos), but I've screwed myself with bad UIs and poor documentation many times in the past.

**Comment by z411** [comment]
Took your idea of help and prompt. Is this fine?

![cli](https://cloud.githubusercontent.com/assets/1988512/10682401/b6d1e3dc-790b-11e5-9a7e-5df1e0e22948.png)


Also I guess I should make the commands shorter.

**Comment by bradenbest** [comment]
@z411

Looks beautiful! Can't wait to try it out for myself.

Full-word commands are fine. What I usually do for that is add tab completion, or add two-letter mnemonics for each command and (of course) add them to the command list on the same line as the full command(s) (where tab completion is sufficiently difficult or impossible to implement, such as in C or bash). For example, you could type in "history" or "hs" to get the same result.

How's that sound?

**Comment by bradenbest** [comment]
And by the way, There only reason there are no long commands in that bash viewer script in the screenshot from earlier is because I was being lazy. 

I did recently design a cli in C, though, that uses long and short commands, like history/hs in the above example.

**Comment by z411** [comment]
I see. Trackma supports tab completion so it should be fine. I still added ls/list for example; I might add more later.
Considering this fixed.
