### ISSUE TITLE
Trackma-gtk opens epiphany instead of default web browser on GNOME

### ISSUE THREAD

**Issue by dyskette** [z411/trackma#143]
Using the option "Show > Open web site" opens Epiphany instead of Firefox (which I choose as default web browser in GNOME settings).

"Show > Show details > Open web" does nothing.

**Comment by z411** [comment]
Hi, I changed the GTK interface to use GTK's own function to open the browser, instead of Python's webbrowser module (ce4aafeca9936b8d4e95b7a0f92303cdad8daf66).

Please check if this has fixed the problem.

**Comment by dyskette** [comment]
Yes, this change fixed it. Now it opens the site in the default browser from the 3 locations (Details window, contextual menu and main menu.).

Hummingbird account doesn't do anything, but I think that's another issue. So, I'm closing this.

Thanks.
