### ISSUE TITLE
Hummingbird account fails

### ISSUE THREAD

**Issue by Kcchouette** [z411/trackma#144]
I think I'm using the last commit of git (8733174e11747da7728e0de58e2adecbba7fd605)

Here the traceback:

```
$ trackma-qt
Data: Locking database...
Data: Reading metadata...
Data: Reading info DB...
Data: No items in queue.
libhb: Logging in...
libhb: Downloading list...
Data: Saving info DB...
Data: Saving cache...
Data: Saving metadata...
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Trackma-0.3-py2.7.egg/trackma/ui/qtui.py", line 871, in r_engine_loaded
    self._rebuild_lists(showlist, altnames, library)
  File "/usr/lib/python2.7/site-packages/Trackma-0.3-py2.7.egg/trackma/ui/qtui.py", line 406, in _rebuild_lists
    self._rebuild_list(status, filtered_list[status], altnames, library)
  File "/usr/lib/python2.7/site-packages/Trackma-0.3-py2.7.egg/trackma/ui/qtui.py", line 438, in _rebuild_list
    self._update_row( widget, i, show, altnames.get(show['id']) )
  File "/usr/lib/python2.7/site-packages/Trackma-0.3-py2.7.egg/trackma/ui/qtui.py", line 481, in _update_row
    widget.setItem(row, 1, ShowItem( title_str, color ))
  File "/usr/lib/python2.7/site-packages/Trackma-0.3-py2.7.egg/trackma/ui/qtui.py", line 1649, in __init__
    QtGui.QTableWidgetItem.__init__(self, text)
TypeError: arguments did not match any overloaded call:
  QTableWidgetItem(int type=QTableWidgetItem.Type): argument 1 has unexpected type 'NoneType'
  QTableWidgetItem(QString, int type=QTableWidgetItem.Type): argument 1 has unexpected type 'NoneType'
  QTableWidgetItem(QIcon, QString, int type=QTableWidgetItem.Type): argument 1 has unexpected type 'NoneType'
  QTableWidgetItem(QTableWidgetItem): argument 1 has unexpected type 'NoneType'
```

Thanks

**Comment by z411** [comment]
Hello; I can't seem to reproduce the problem. It seems there's something specific with your list triggering the bug.

Could you upload your list cache (located in `~/.trackma/<username>.hb/anime.list`)? Don't worry, it doesn't contain personal info.

**Comment by Kcchouette** [comment]
Since github can't host .txt file, I paste this file on my gist: https://gist.github.com/Kcchouette/509b8fba6367319033dd

Thanks for your help!

**Comment by z411** [comment]
Thank you, confirmed.

**Comment by z411** [comment]
So, this seems to be an issue upstream where the anime Wizard Barristers for some reason has an empty title, so you might want to report that to Hummingbird?
![wizard](https://cloud.githubusercontent.com/assets/1988512/9700674/be8646bc-53e1-11e5-9fcb-153471bc4ea0.png)

Either way, I modified libhb anyway to workaround the issue. Please try to delete the cache (the anime.list file) and re-open Trackma. The show should appear now with an empty title instead of hanging completely.

**Comment by Kcchouette** [comment]
Ok now I see a empty title.

I report the issue on hummingbird forum: https://forums.hummingbird.me/t/wizard-barristers-has-a-null-title/26857

Thanks. I think you can close the issue on github :+1:

**Comment by z411** [comment]
Just saw that this was already reported here:

https://github.com/hummingbird-me/hummingbird/issues/623
