### ISSUE TITLE
GTK: Random crashes on "Re-scan library"

### ISSUE THREAD

**Issue by mat8913** [z411/trackma#145]
About 60% of the time, the "Re-scan library" button causes a crash:

    /home/matthew/git/trackma/trackma/ui/gtkui.py:79: GtkWarning: gtk_list_store_get_value: assertion 'VALID_ITER (iter, list_store)' failed
      gtk.main()
    /home/matthew/git/trackma/trackma/ui/gtkui.py:79: Warning: g_object_set_property: assertion 'G_IS_VALUE (value)' failed
      gtk.main()
    /home/matthew/git/trackma/trackma/ui/gtkui.py:79: Warning: g_value_unset: assertion 'G_IS_VALUE (value)' failed
      gtk.main()
    [1]    21457 segmentation fault (core dumped)  ./trackma-gtk

The following patch seems to fix it:

    --- a/trackma/ui/gtkui.py
    +++ b/trackma/ui/gtkui.py
    @@ -557,7 +557,7 @@ class Trackma_gtk(object):
             threading.Thread(target=self.task_play, args=(playnext,ep)).start()
     
         def do_scanlibrary(self, widget):
    -        threading.Thread(target=self.task_scanlibrary).start()
    +        self.task_scanlibrary()
     
         def do_delete(self, widget):
             try:

**Comment by z411** [comment]
Thank you.

I can remember it happening once, but I can't reproduce it anymore.
The rebuilding of the list was accidentally being done in the thread, this shouldn't happen.
I fixed that by making it rebuild the list in the main thread.
Please tell me if it works.

If it doesn't I'll just put all the processing in the main thread (will lock the GUI though).

**Comment by mat8913** [comment]
It works! Thanks for fixing that. Also, I can't get the Qt interface to crash so
it's probably fine too.

**Comment by z411** [comment]
Great, thanks for the report. I'll consider it fixed then.
If it happens again don't hesitate to say it here or open a new issue.

**Comment by mat8913** [comment]
While I was testing the Qt interface I noticed another bug in the GTK interface.
The last episode of a series doesn't show up blue in the little bar. The
following patch fixes it:

    --- a/trackma/ui/gtkui.py
    +++ b/trackma/ui/gtkui.py
    @@ -2311,7 +2311,7 @@ class ProgressCellRenderer(gtk.GenericCellRenderer):
             if self.eps:
                 cr.set_source_rgb(0.4, 0.5, 0.6)
                 for episode in self.eps:
    -                if episode > 0 and episode < self.total:
    +                if episode > 0 and episode <= self.total:
                         start = int(w / float(self.total) * (episode - 1))
                         finish = int(w / float(self.total) * episode)
                         cr.rectangle(x+start, y+h-self._subheight, finish-start, h-(h-self._subheight))

**Comment by z411** [comment]
Thank you, applied.
