### ISSUE TITLE
Graphical bug

### ISSUE THREAD

**Issue by hbers** [z411/trackma#146]
![2015-09-10-230729_560x527_scrot](https://cloud.githubusercontent.com/assets/13052105/9799616/04e863e6-5811-11e5-9003-d3f8830d057b.png)

It started happening after re-scanning the library. I don't know if it's intentional and don't think so. I'm talking about the "percent" part by the way.

**Comment by hbers** [comment]
Oops. Those little bars are the present files in the disk. Sorry I get it now.

**Comment by z411** [comment]
Yeah, dark grey means released, dark blue means available in your disk.
Maybe I should explain it somewhere?
The Qt interface shows an explanation tooltip when hovering the progress bar. I should do that in the GTK one.

**Comment by hbers** [comment]
Yeah I think that would be great. I thought it was a bug at first as I couldn't find any info on it what does it do.
