### ISSUE TITLE
self.show_progress_bar does not update automatically.

### ISSUE THREAD

**Issue by JeroenMathon** [z411/trackma#148]
When doing a update, Add or Remove epp.
The self.show_progress_bar does not update itself.
Unless you select another show and then go back to the current show.

No error output just these calls are missing 
```python 
self.show_progress_bar.set()
self.show_progress_bar.update()
```
I don't know much of the engine itself so ill post the issue here.

**Comment by z411** [comment]
Fixed, thank you.
