### ISSUE TITLE
Progress bars appearance [GTK]

### ISSUE THREAD

**Issue by archnous** [z411/trackma#153]
The progress bars in 0.3 were better looking, especially in dark themes. I haven't checked the code, but I believe in 0.3 they followed the theme's widget style, instead of being arbitrarily set as in 0.4 (please, correct me if I'm wrong).

![trackma-0 3](https://cloud.githubusercontent.com/assets/6310912/10425203/4f68bda4-70de-11e5-8c6a-1844bc8a5fa0.png)
![trackma-0 4](https://cloud.githubusercontent.com/assets/6310912/10425204/4f6920d2-70de-11e5-8084-d5a967c5a313.png)

**Comment by wizbright** [comment]
![151012112642-572x545](https://cloud.githubusercontent.com/assets/1281756/10432965/3da0f2f8-70d4-11e5-8d6e-5ddd97af4443.png)

I guess it depends on the theme. I think the bars look fine to be honest.

**Comment by archnous** [comment]
I'd prefer the uniform look of the theme. Right now the colour of the bars is fixed; please see how much more elegant is the look of the themes, whether they're dark or light:

![2015-10-12-230707_1920x1080_scrot](https://cloud.githubusercontent.com/assets/6310912/10437675/69d99a92-7137-11e5-9e75-24b6348705cb.png)
![2015-10-12-230814_1920x1080_scrot](https://cloud.githubusercontent.com/assets/6310912/10437676/69dc7b90-7137-11e5-9256-c02033275286.png)
![2015-10-12-230901_1920x1080_scrot](https://cloud.githubusercontent.com/assets/6310912/10437672/69d0d790-7137-11e5-95d2-cf492d981c18.png)
![2015-10-12-230930_1920x1080_scrot](https://cloud.githubusercontent.com/assets/6310912/10437674/69d65468-7137-11e5-8316-d29f27361039.png)
![2015-10-12-230958_1920x1080_scrot](https://cloud.githubusercontent.com/assets/6310912/10437673/69d144b4-7137-11e5-9fd7-0e7553134c0b.png)

I believe this should be reverted to the old behaviour, i.e. let the theme apply its colours.

**Comment by z411** [comment]
The new progress bar is made from scratch since it also shows aired episodes and available episodes in your hard disk (try List -> Re-scan library). Reverting the changes would also destroy this functionality.
The best solution is to modify the current custom progress bar to use the theme colors. I'll be confirming this.
