### ISSUE TITLE
[REQUEST] Please add support for shikimori.org

### ISSUE THREAD

**Issue by frostheart** [z411/trackma#157]
I would like to see an implementation api of shikimori.org in your application.
You can find API here: [Shikimori.org API](http://shikimori.org/api/doc)

Thank you.

P.S.
Shikimori.org is an anime and manga database similar to mal but in russian language and partial english.

**Comment by z411** [comment]
Hello, just a heads up. I added basic support for Shikimori. It's still incomplete but you can retrieve your list and search for anime/manga.

I added syncing functionality too but the server returns 503 (Service Unavailable) when trying to update. I'm not sure yet if this is a problem with the server right now or I'm doing something wrong on my end. Will look into it.

**Comment by frostheart** [comment]
Thank you so much. Especially, how quick you are.

**Comment by z411** [comment]
Add/Update/Delete should be working in the latest commit now.

**Comment by z411** [comment]
Nothing left to implement API-wise, considering this done.
If you have any trouble or suggestions don't hesitate to comment it here or create a new issue.
