### ISSUE TITLE
Automatic library scan + Make Play Next use the library

### ISSUE THREAD

**Issue by Veicc** [z411/trackma#162]
Wrote this issue without paying enough attention to the previous ones, sorry for that. This one is very similar: https://github.com/z411/trackma/issues/152

The library scanner expects filenames to have episode numbers on them, even if the show has only one episode (e.g. movies). So, from what I've experienced, even single-episode movie filenames need to have an additional character "1" on them if you want that library scanner detects them. This, in my opinion, doesn't make sense. 

Thanks in advance, and Thank You for developing the best client for managing lists!

**Comment by adkow** [comment]
+1

**Comment by z411** [comment]
Hello, it works for me. When a filename doesn't have an episode number, it is assuming it's episode 1.

Could you tell me which filenames are you trying?

**Comment by z411** [comment]
Also, I think this only happens with Play Next, not with the tracker (that is, it detects it properly if you start your media player manually). Am I correct?

**Comment by Veicc** [comment]
> Also, I think this only happens with Play Next

Yup, you're correct. I was a bit ambiguous about it in my post because I was so excited when I discovered that this playing could start playing files directly :3

**Comment by z411** [comment]
Indeed. The library scanner works fine, it's just that the Play Next functionality actually doesn't use the data from the library scanner. It should, but I have to deal first with keeping the library up to date. This is easy to do on Linux with inotify, as Trackma can get notified on any new file, but on other OSes I'm not sure. There, the library scan can be done automatically when Trackma starts, and any subsequent scans should be done manually.
