### ISSUE TITLE
With the recent updates, Trackma hangs on fully loading

### ISSUE THREAD

**Issue by wizbright** [z411/trackma#173]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/Trackma-0.4-py2.7.egg/trackma/ui/gtkui.py", line 833, in task_start_engine
    self.build_all_lists()
  File "/usr/lib/python2.7/site-packages/Trackma-0.4-py2.7.egg/trackma/ui/gtkui.py", line 934, in build_all_lists
    self.build_list(status)
  File "/usr/lib/python2.7/site-packages/Trackma-0.4-py2.7.egg/trackma/ui/gtkui.py", line 943, in build_list
    widget.append(show, self.engine.altname(show['id']), library.get(show['id']))
  File "/usr/lib/python2.7/site-packages/Trackma-0.4-py2.7.egg/trackma/ui/gtkui.py", line 1329, in append
    episodes_str = "%d / %d" % (show['my_progress'], show['total'])
TypeError: %d format: a number is required, not NoneType
```
I received this error after I pulled all the new updates and ran trackma-gtk again.

**Comment by hbers** [comment]
In my case Trackma behaves like this. You can't see the list but can interact with it.
![ss](https://cloud.githubusercontent.com/assets/13052105/11429792/c244b204-9485-11e5-862c-d87633f31678.png)

**Comment by z411** [comment]
Hello, thanks for the report.

Does it still happen after you attempt to re-download the list? (you can force this by deleting the ~/.trackma/<username>.mal directory).

**Comment by z411** [comment]
Hello, thanks for the report.

Does it still happen if you attempt to redownload the list?
Could you please upload the file ~/.trackma/<username>.mal/anime.list ?
It's your list cache. Don't worry, it doesn't contain sensitive information.

**Comment by z411** [comment]
@hbers Thanks, I think your issue might be different than @wizbright's. Could you run trackma-gtk in the Terminal and post the output?

**Comment by wizbright** [comment]
[anime_list.txt](https://github.com/z411/trackma/files/46109/anime_list.txt)

Here ya go

**Comment by hbers** [comment]
@z411 Sure, here is the output. I saw that there is a new issue posted but I'll just post the output here.
![2015-11-27-231303_570x212_scrot](https://cloud.githubusercontent.com/assets/13052105/11448228/83371340-955c-11e5-9add-cfeed3aff62b.png)

**Comment by z411** [comment]
@wizbright Thank you, I could reproduce the bug. I'll look into it.
@hbers Weird, there seems to be nothing wrong, but I think I know what the problem is, will look into it in a moment.

**Comment by z411** [comment]
@hbers The latest commit should fix it. Please tell me if it works.

**Comment by z411** [comment]
@wizbright I fixed it on my end, please pull the latest commit and re-retrieve your list (you can use the CLI interface and the `retrieve` command). The GTK interface should work again.

**Comment by wizbright** [comment]
I pulled the new files, it is still running into the same problem. It loaded fine until it hung on the tracker.

**Comment by hbers** [comment]
@z411 It works now. Thank you.

**Comment by z411** [comment]
@wizbright Same exact error? It's working on my end this time; did you attempt to retrieve again? If so, could you upload your anime.list?

**Comment by wizbright** [comment]
Looks like it finally works again, seems it wasn't fully retrieving my list last time. Thanks for fixing it!
