### ISSUE TITLE
Show details image cropped [GTK]

### ISSUE THREAD

**Issue by archnous** [z411/trackma#174]
Double-clicking a show in Qt shows the full-sized image correctly:
![trackma-qt](https://cloud.githubusercontent.com/assets/6310912/11448682/df64e1c0-9565-11e5-9bb2-0f613a4feb5b.png)

In GTK the image is center-cropped and zoomed:
![trackma-gtk](https://cloud.githubusercontent.com/assets/6310912/11448687/fc9122a4-9565-11e5-950b-ac4c757fa765.png)

**Comment by z411** [comment]
I'm guessing the image is too big; since different sites have different sizes for the cover image I'll modify it so it resizes it too instead.
