### ISSUE TITLE
Multiple Media directories.

### ISSUE THREAD

**Issue by Logmytech** [z411/trackma#179]
I have my anime in multiple directories and Hard disks. But Trackma has option for only one "Media directory".
So, please add option for including multiple directories for Media Sources

**Comment by SkepticalsArctic** [comment]
I second this. I have two anime hard drives and and can't acess all of my anime easily

**Comment by ToostInc** [comment]
You can workaround by adding symlinks from one to the other directory, that's how I fixed this.

**Comment by 9Morello** [comment]
I also would like this feature.

**Comment by MadeOfMagicAndWires** [comment]
Should add that, when using pyinotify, symlinks will still work for the library, but that files will not be picked up by the tracker (see https://github.com/seb-m/pyinotify/issues/83)

**Comment by HS-157** [comment]
+1

**Comment by BradleyDS2** [comment]
Sorry to be a bother, but is this currently being worked on? Progress has been silent since 2016.

I split my series by TV/Web quality and bluray quality in different folders, so this feature would be much appreciated.

Thank you for all your hard work, I love trackma!

**Comment by z411** [comment]
Sorry for the lateness. This has been implemented in the `develop` branch; I'd appreciate it if you could test it out and tell me if it works with your setup before merging. Thanks.

**Comment by 9Morello** [comment]
Hi @z411 , unfortunately I cannot test it for now because the other HDD isn't with me currently. Hopefully one of the others is able to. Thanks for working on this.
