### ISSUE TITLE
.qt source file for trackma-qt

### ISSUE THREAD

**Issue by Logmytech** [z411/trackma#180]
I was wondering if the qt GUI was created using a WYSIWYG tool like "Qt Designer" or "QT creator" and later converted to python code.
If yes then the .qt file should be provided so that others can edit the GUI easily.

Or is it coded directly in python without a WYSIWYG editor. If it is, is editing the code my only option to change the GUI? Or can I still use a WYSIWY editor?

**Comment by z411** [comment]
Sorry, it is coded directly. I didn't use any WYSIWYG editor so there's no UI file.
