### ISSUE TITLE
.desktop file for launching using the menu

### ISSUE THREAD

**Issue by Logmytech** [z411/trackma#182]
I installed trackma using pip in Linux Mint 17.2 and I'm unable to see trackma in the (Start) menu. I have to launch it every time using the terminal. Please  add a .desktop file on install so that you can launch it using the menu.

**Comment by ToostInc** [comment]
@Logmytech 

Might not entirely be what you're looking for but you can find the .desktop I use for the AUR package [here](https://github.com/ToostInc/AUR/tree/master/trackma-git).

**Comment by z411** [comment]
Moved to #282
