### ISSUE TITLE
Error when Docker Daemon is running. 

### ISSUE THREAD

**Issue by Rivalo** [z411/trackma#188]
On Linux Mint, when the Docker Daemon (1.9.1) is running Trackma(Latest: https://github.com/z411/trackma/commit/5442876a5f9340291bff5ad6f72487bf7f63ab0f) prints the following error:
```bash
lsof: WARNING: can't stat() ext4 file system /var/lib/docker/aufs
      Output information may be incomplete.
```

This disrupts the trackma and trackma-curses interface since printing of this error erases parts of the interface. It's a weird error, but it seems Trackma disrupts the Docker Daemon which does a `printf` to the terminal? It might even be a Docker error, but this is the first application that gave me this error.

Stopping the docker daemon:
`sudo service docker stop` fixes the problem, starting it again and the error is back.

**Comment by z411** [comment]
I think I just disabled the lsof warnings (+w) but I'm not sure if it's the other way around. I tried installing docker but couldn't reproduce.

**Comment by Rivalo** [comment]
Great! Commit https://github.com/z411/trackma/commit/95563551b831d10cabe2cddef91dcc0a41a89b56 fixed the issue!
