### ISSUE TITLE
Bad picture for Evangelion

### ISSUE THREAD

**Issue by Kcchouette** [z411/trackma#189]
I don't really know what's append. It doesn't see to be a HB issue because `http://hummingbird.me/api/v1/anime/21` return a good picture.

Here a screenshot
![screenshot_Evangelion_OPpicture](https://cloud.githubusercontent.com/assets/3000936/12701740/2160a5b6-c813-11e5-9bc9-7c6d2eb240c2.png)

**Comment by veluria** [comment]
That's because you previously used MAL and One Piece's ID is 21 on MAL. Delete /home/Kcchouette/.trackma/cache/21.jpg and the right image should appear.

**Comment by Kcchouette** [comment]
Yes, thanks, @veluria

**Comment by Birdulon** [comment]
This also occurs for collisions with manga IDs and presumably any other mediatype. I think unique API and mediatype prefixes to pictures in the cache would be an easy solution to this, however it would mean a forced (picture) cache clear for this change.
