### ISSUE TITLE
Can't open show link

### ISSUE THREAD

**Issue by Kcchouette** [z411/trackma#192]
I'm thinking an issue on my side until I read #143 (exactly [here](https://github.com/z411/trackma/issues/143#issuecomment-137986257))

> Hummingbird account doesn't do anything, but I think that's another issue. So, I'm closing this.

To do that: open trackma-gtk, choose the hummingbird account (not tested with other account), right click on a show > open web site.

Thanks

**Comment by Birdulon** [comment]
Did a quick test with my hb account on Qt and gtk clients, 6d84c38 should fix this.

**Comment by z411** [comment]
Merged @Birdulon 's fix, thanks.

**Comment by Kcchouette** [comment]
Thanks @Birdulon and @z411 

Is there a way to use API of hummingbird in HTTPS (and the url too)? Should I open a new issue for that?

**Comment by Birdulon** [comment]
Possibly. I get SSL errors with my python setup so I can't test that, I
think the image retrieval already uses HTTPS as it fails to load them for
me.
