### ISSUE TITLE
More love for curses interface

### ISSUE THREAD

**Issue by rr-** [z411/trackma#195]
It'd be super cool if we could configure trackma's urwid palette so that it looks good in light terminals - compare vim's colors vs trackma's colors:

![20160320_122731_yin](https://cloud.githubusercontent.com/assets/1045476/13904150/2adc60da-ee97-11e5-8769-c29dc56081d8.png)

...and also configure the menu hotkeys - typing F1-F12 on 60% keyboards is suboptimal:

![HHKB Lite](http://www.pfusystems.com/images/hhkb/lite2-angle.jpg)

**Comment by z411** [comment]
Should we have themes or manually customizable colors?
The keybinds are already customizable, check out the ~/.trackma/keymap.json file.
Although I should probably change the defaults and include vi-like up-down/j-k.

**Comment by rr-** [comment]
I didn't know about `keymap.json`, that's awesome! 

But yep:

1. being able to remap <kbd>↓</kbd>/<kbd>↑</kbd> to <kbd>J</kbd>/<kbd>K</kbd> would make it more intuitive, too
2. it'd be cool if we could define multiple hotkeys, e.g. `"quit": ["q", "ctrl q"]`.
3. the help screen should reflect current settings from `keymap.json` rather than showing the defaults.

Regarding themes: I think that's a little overkill - being able to customize the `palette` (`curses.py:64..81`) like `keymap.json` would be plenty already. Note that in order to fully use urwid's capabilities, the mainloop needs to get screen with 256 colors like this:

    term_colors =  256 # I'd make this customizable, too, and set to 16 by default
    screen = urwid.raw_display.Screen()
    screen.set_terminal_properties(colors=term_colors)
    self.mainloop = urwid.MainLoop(self.view, palette, unhandled_input=self.keystroke, screen=screen)

and the entries in the palette need to specify the extra colors in additional fields like this:

        palette = [
            ('body', '', ''),
            ('focus', '', 'yellow', '', '', '#fc0'),

**Comment by z411** [comment]
Sure, please feel free. Although the current file is called keymap.json; maybe we could rename it to ui-curses.json to keep both keymap and palette configuration in the same file.

**Comment by z411** [comment]
Changed to file ui-curses.json: Added capability for multiple keybinds, color customization, fixed help menu.

**Comment by rr-** [comment]
:+1: I was intending to work on this soonish, sorry

**Comment by z411** [comment]
Marking this as done.

**Comment by raniesantos** [comment]
> Added capability for multiple keybinds, color customization

I'm currently editing ui-curses.json and I can't get yellow to work. I couldn't find any info on this repo's wiki on how to specify colors.

**Comment by raniesantos** [comment]
Okay, I can actually change the colors I probably just don't know the right label for what I want to change.

**Comment by sudoshindo** [comment]
I'm posting a comment here because it's related to my question. How exactly do I use more specific colors?

I want to set a wider range of colors like `h27` or `h39`. I read the urwid documentation which says this should be possible?

I'm getting an error that says `urwid.display.common.AttrSpecError: foreground/background require more colors than have been specified (16)`

@rr- @z411

**Comment by Birdulon** [comment]
> I'm posting a comment here because it's related to my question. How exactly do I use more specific colors?
> 
> I want to set a wider range of colors like `h27` or `h39`. I have read the urwid documentation which says this should be possible.
> 
> I'm getting an error that says `urwid.display.common.AttrSpecError: foreground/background require more colors than have been specified (16)`

You'd need to do `screen.set_terminal_properties(colors=256)` (or `2**24` for 24bit) somewhere to set the increased colorspace, which might not work depending on the terminal.
Possibly right after this https://github.com/z411/trackma/blob/023a9f78f01df203dcbe3f265ed7576ed5057c25/trackma/ui/curses.py#L123-L124 in which case you'd want something like
```python
self.mainloop.screen.set_terminal_properties(colors=256)
```

I haven't tested this, it's just my reading of the urwid docs.

**Comment by sudoshindo** [comment]
@Birdulon wait, you mean the application doesn't support it by default????

I was under the assumption that anything using urwid would be able to do it by default.

**Comment by sudoshindo** [comment]
@Birdulon hello?

**Comment by z411** [comment]
> [@Birdulon](https://github.com/Birdulon) wait, you mean the application doesn't support it by default????
> 
> I was under the assumption that anything using urwid would be able to do it out-of-the-box.

It is supported but not enabled by default. I enabled it in the commit https://github.com/z411/trackma/commit/4e0be918b8f019c6ee7a960c636ef5da1cbbf3be

Could you please try adding the high colors in your ui-curses.json config file like this example:

```
        "item_airing": [
            "dark blue",
            "",
            "",
            "#3B3",
            ""
        ]
```

  If it worked, it should use the specified hi-color green 3B3. If not, it will fall back to *dark blue*.

![Image](https://github.com/user-attachments/assets/2feffe8b-1585-402e-bc99-b486cd3bd9ce)

**Comment by sudoshindo** [comment]
Do I apply the change manually or did you already publish a new pypi release?

**Comment by FichteFoll** [comment]
try `pipx install --system-site packages https://github.com/z411/trackma.git`

**Comment by sudoshindo** [comment]
```
> pipx install --system-site-packages https://github.com/z411/trackma.git

  ERROR: Cannot unpack file /tmp/pip-unpack-_q73axor/trackma.git (downloaded from /tmp/pip-req-build-8cf3h2ka, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-8cf3h2ka
Cannot determine package name from spec 'https://github.com/z411/trackma.git'. Check package spec for errors.
```

**Comment by sudoshindo** [comment]
The command given above didn't work, so I just manually applied the changes from the commit.

I went into `/.local/share/pipx/venvs/trackma/lib/python3.12/site-packages/trackma/ui` and I directly edited `curses.py`

Here is the error message that I got:

```
Traceback (most recent call last):
  File "/home/shindo/.local/bin/trackma-curses", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/shindo/.local/share/pipx/venvs/trackma/lib64/python3.12/site-packages/trackma/ui/curses.py", line 1228, in main
    ui = Trackma_urwid()
         ^^^^^^^^^^^^^^^
  File "/home/shindo/.local/share/pipx/venvs/trackma/lib64/python3.12/site-packages/trackma/ui/curses.py", line 123, in __init__
    self.mainloop = urwid.MainLoop(
                    ^^^^^^^^^^^^^^^
  File "/home/shindo/.local/share/pipx/venvs/trackma/lib64/python3.12/site-packages/urwid/event_loop/main_loop.py", line 135, in __init__
    screen.register_palette(palette)
  File "/home/shindo/.local/share/pipx/venvs/trackma/lib64/python3.12/site-packages/urwid/display/common.py", line 1100, in register_palette
    self.register_palette_entry(*item)
  File "/home/shindo/.local/share/pipx/venvs/trackma/lib64/python3.12/site-packages/urwid/display/common.py", line 1173, in register_palette_entry
    basic = AttrSpec(foreground, background, 16)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shindo/.local/share/pipx/venvs/trackma/lib64/python3.12/site-packages/urwid/display/common.py", line 598, in __init__
    raise AttrSpecError(
urwid.display.common.AttrSpecError: foreground/background ('#3B3'/'') require more colors than have been specified (16).
```
