### ISSUE TITLE
play_random gives IndexError when it can't find any new episodes.

### ISSUE THREAD

**Issue by MadeOfMagicAndWires** [z411/trackma#202]
Trackma crashes when it can't find any unwatched episodes to randomly pick from. Even when there should be episodes available to pick from for a single show.

Traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/trackma/ui/qtui.py", line 3011, in run
    ret = self.function(*self.args,**self.kwargs)
  File "/usr/lib/python2.7/site-packages/trackma/ui/qtui.py", line 2931, in _play_random
    (show, ep) = self.engine.play_random()
  File "/usr/lib/python2.7/site-packages/trackma/engine.py", line 708, in play_random
    show = random.choice(newep)
  File "/usr/lib/python2.7/random.py", line 275, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range
```

Interestingly, as mentioned in the comment, `newep` seems to be empty in this case but it should have found unwatched episodes of one show which _are_ picked up by 'Play Next' and library scan, but seem to be ignored by play_random.  When new episodes are available for multiple shows, it does work, and will (randomly)  also select episodes of the first show. 

I don't know why this is, but it seems to me that, even if there is only one show to pick from it should still "randomly" select that one show, instead of ignoring it completely.

**Comment by ToostInc** [comment]
the 'single' show tested on was [Shouwa Genroku Rakugo Shinju](http://anilist.co/anime/20972/ShouwaGenrokuRakugoShinjuu) btw, but I don't think that matters, since it *is* able to randomly select the show when multiple shows with new episodes are available.

**Comment by z411** [comment]
Does this still happen? Can't reproduce.

**Comment by MadeOfMagicAndWires** [comment]
Me neither, seems to have resolved itself.

**Comment by z411** [comment]
It was probably a bug in the library that got fixed elsewhere.
