### ISSUE TITLE
Trackma-qt fails to close correctly.

### ISSUE THREAD

**Issue by suttlesc** [z411/trackma#206]
Trackma-qt fails to close, and stays open indefinitely. Need to kill process to close. Trackma-gtk and trackma-curses are uneffected.

All terminal gives is the following.

`[lolihunter@lolihunter-thinkpad ~]$ trackma-qt`
`Warning: DateUtil is unavailable. Next episode countdown will be disabled.`
`Data: Locking database...`
`Data: Reading metadata...`
`Data: Reading queue...`
`Data: Reading info DB...`
`Data: No items in queue.`
`libhb: Logging in...`
`libhb: Downloading list...`
`Data: Saving info DB...`
`Data: Saving cache...`
`Data: Saving metadata...`
`Tracker: Initializing...`
`Tracker: Enabling tracker...`
`Tracker: Using inotify.`
`Tracker: inotify: Watching /mnt/server/home/lolihunter/Downloads/Anime`
`Ready.`
`Tracker: inotify: Watching /mnt/server/home/lolihunter/Downloads/Anime/Active`
`Engine: Unloading...`
`Data: Unloading...`
`Data: No items in queue.`
`Data: Saving metadata...`

Tried deleting the .trackma folder and re-adding my account, and the issue persists.

**Comment by z411** [comment]
Are you sure it's not staying in the system tray?

**Comment by lolihunter** [comment]
I checked that it is, with the contents greyed out. It hangs, with the last output from terminal being "Data: Saving metadata...". The strange thing is if I kill it using killall trackma-qt, the program starts normally as if it was shutdown correctly.

**Comment by Birdulon** [comment]
Admittedly I've seen this happen on my Plasma5 machine, though it happens with a bunch of other applications that use the system tray so I just wrote it off as a problem somewhere else. I'll look into it some more on a fresh ubuntu studio 16.04 install.

**Comment by z411** [comment]
In that case, does disabling the system tray icon in the settings fix the issue?

**Comment by lolihunter** [comment]
I can confirm it does allow the program to close. I am also running KDE Plasma 5 on Arch, so it appears to be a tray issue.

**Comment by z411** [comment]
Could you check if you're using Qt5 (see About menu)? Trackma-qt should now try Qt5 if it's available.

**Comment by llomellamomario** [comment]
I do have the same behavior under KDE. Recently decided to give KDE a try, and it was working  fine under LXDE where it did not happen. Using Arch and it is indeed using Qt 5.7.

**Comment by z411** [comment]
Fixed in #289
