### ISSUE TITLE
Tracker support for Kodi

### ISSUE THREAD

**Issue by lolihunter** [z411/trackma#214]
I have an android TV box that I use for pretty much all my anime and tv. I have a server running Arch, and have tried to get the tracker to be able to detect when I am watching the shows to no avail. Trying to set the tracker to pick up on samba reading the file doesn't work, (smbd process).

**Comment by z411** [comment]
So are you running Trackma on the server, correct?
Implementing Kodi support shouldn't be hard as we already have a Plex implementation thanks to a contributor (see extras/plex.py).

**Comment by lolihunter** [comment]
Yes, running trackma on an Arch linux server, and using Kodi on android. Kodi has no way to scrobble to hummingbird itself.

**Comment by lolihunter** [comment]
Oh, and FYI, kodi does support control through a webserver (if enabled) on port 8080. Although it might take some work to implement a way for trackma to detect what is playing and make it work.

**Comment by z411** [comment]
Implemented by #214 - Thank you.
