### ISSUE TITLE
inotifyx isn't available for python3

### ISSUE THREAD

**Issue by ToostInc** [z411/trackma#218]
Seems the inotifyx package you currently use is written in python2 and so can't be be used anymore.

I don't know what the solution for this problem is.
I tried seeing what 2to3 could do, but since it also uses C it's looking like porting this will require more than just a quick patch.
Either someone would have to put in the work to port this to python 3 or you could maybe look into using [this ](https://pypi.python.org/pypi/inotify) or some other inotify package instead? I don't know.

For now I've removed inotifyx from the Arch package dependencies, so that will be solely relying on lsof for the moment.

**Comment by z411** [comment]
Thank you; Indeed inotifyx isn't working and it seems to be abandoned. We'll have to switch; pyinotify seems like the only option since it seems to be readily available in the repos of main distros.

**Comment by rr-** [comment]
Just a question, but isn't availability on PIP enough?

**Comment by Birdulon** [comment]
The inotify part of the tracker looks small and discrete enough that it may not be a big deal supporting both of the PyInotify libs.

**Comment by z411** [comment]
Fixed by #221
