### ISSUE TITLE
Trackma detects torrent client as Mediaplayer

### ISSUE THREAD

**Issue by okabekudo** [z411/trackma#232]
Headline basically says it, if there's an active torrent for the wanted anime either seeding or downloading it will update the queue. I'm on newest Trackma 0.6.1 and Arch Linux Gnome. And it appears in Vuze and in Qbittorrent.

**Comment by z411** [comment]
Thank you. Which inotify library are you using, if any?

**Comment by Birdulon** [comment]
What's your Process name regex set to?

**Comment by okabekudo** [comment]
> Which inotify library are you using, if any?

libnotify 0.7.6-2

> What's your Process name regex set to?
Which process exactly?

**Comment by Birdulon** [comment]
Under Global Settings->Media there's a field called "Process Name" which is a regex used to identify your video players. If it's blank it'll match all processes so any process that accesses the videos in the watch directory will trigger the tracker.

**Comment by okabekudo** [comment]
> Under Global Settings->Media there's a field called "Process Name" which is a regex used to identify your video players. If it's blank it'll match all processes so any process that accesses the videos in the watch directory will trigger the tracker.

Ah that's what you meant. Lol was very unclear before. Nope it's not empty, I made sure that it isn't before. It's set to: mplayer|mplayer2|mpv|

**Comment by Birdulon** [comment]
If that trailing | is there, try removing it.

**Comment by okabekudo** [comment]
> If that trailing | is there, try removing it.

Sorry for my late reply. So that damn trailing was the culprit as it seems haha. Would've never guessed that.

**Comment by z411** [comment]
Should we find a way to work around this?

**Comment by Birdulon** [comment]
I think making the option more descriptive in gtk and qt, and adding a
validation that warns about wildcards if detected would be sensible changes.
