### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by giuliandenicola** [z411/trackma#244]
I really like Trackma, but the lack of information is kind of bad. For instance when I search up a anime I would like to see genres, sequel, sidestory etc. (this isn't a complaint just a suggestion)

**Comment by z411** [comment]
You're talking about the show details dialog, correct? It depends exclusively whether the API provides that information or not. MAL, for example, doesn't.

**Comment by giuliandenicola** [comment]
Oh eh, I am using MAL. does the API differs much from the api for mobile?
Because on the android apps there is genres etc. showing **For example** `pocket mal` `atarashii`

**Comment by MadeOfMagicAndWires** [comment]
You can get genre, summary, aliases and air dates by clicking `Show details` (in either the show or right-click menu), but unfortunately other things like related series aren't supported by the APIs yet.

**Comment by z411** [comment]
Genre is currently not retrieved by libmal. erengy made a comparison of Hummingbird and MAL official APIs; see *Metadata Terms* for the information that the official APIs provide:

http://taiga.erengy.com/api.html

It seems `genre` is actually available in MAL's API through an undocumented call. We could use that. But the API doesn't provide anything else that's not in that list.

Other APIs like Hummingbird's do provide extra information; the details dialog shows all the information the API has provided (or it should; if it's missing something please add it or poke me about it).
