### ISSUE TITLE
[win32, Qt] Remember window size and position not remembering position

### ISSUE THREAD

**Issue by qyot27** [z411/trackma#246]
I've noticed a drift when opening trackma-qt multiple times, in which it slowly creeps up the screen with each time it opens.  Eventually, this gets bad enough that the user can't grab the titlebar, and then it can even get bad enough that the menus can't be opened.  I have to resort to either A) remembering to drag the window down to the middle of the screen before the title bar gets swallowed by the edge of the desktop, or to go into ui-qt.json in  %USERPROFILE%\.trackma and forcibly reset last_y to something well within the screen boundaries.

Example: I force last_x to 282 and last_y to 221.  Launch it once, it's in more-or-less the right place.  But after closing it, last_x is now 274 and last_y is 190.

It seems to be fine with remembering the window size, so this is just positioning.

It'd actually be nice to have an 'Always open window in the center of the screen' option.

**Comment by giuliandenicola** [comment]
Hmm, I do not have this problem? 
It opens at the same position everytime I start it, even after a reboot.
