### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by kahrkunne** [z411/trackma#249]
Best expressed through the error log, methinks:
```
Trackma v0.6.1  Copyright (C) 2012  z411
This program comes with ABSOLUTELY NO WARRANTY; for details type 'info'
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details.

Initializing engine...
[0;32mEngine: Trackma v0.6.1 - using account kahrkunne(hb).[0m
[0;32mEngine: Reading config files...[0m
[0;33mData: Initializing...[0m
[0;34mlibhb: Initializing...[0m
[0;33mData: Using libhb (anime)[0m
[0;34mlibhb: Logging in...[0m
Traceback (most recent call last):
  File "/usr/lib64/python3.5/urllib/request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib64/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/usr/lib64/python3.5/http/client.py", line 1237, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python3.5/ssl.py", line 376, in wrap_socket
    _context=self)
  File "/usr/lib64/python3.5/ssl.py", line 747, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.5/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.5/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/trackma", line 9, in <module>
    load_entry_point('Trackma==0.6.1', 'console_scripts', 'trackma')()
  File "/usr/lib64/python3.5/site-packages/Trackma-0.6.1-py3.5.egg/trackma/ui/cli.py", line 901, in main
    main_cmd.start()
  File "/usr/lib64/python3.5/site-packages/Trackma-0.6.1-py3.5.egg/trackma/ui/cli.py", line 147, in start
    self.engine.start()
  File "/usr/lib64/python3.5/site-packages/Trackma-0.6.1-py3.5.egg/trackma/engine.py", line 223, in start
    (self.api_info, self.mediainfo) = self.data_handler.start()
  File "/usr/lib64/python3.5/site-packages/Trackma-0.6.1-py3.5.egg/trackma/data.py", line 163, in start
    self.download_data()
  File "/usr/lib64/python3.5/site-packages/Trackma-0.6.1-py3.5.egg/trackma/data.py", line 522, in download_data
    self.showlist = self.api.fetch_list()
  File "/usr/lib64/python3.5/site-packages/Trackma-0.6.1-py3.5.egg/trackma/lib/libhb.py", line 108, in fetch_list
    self.check_credentials()
  File "/usr/lib64/python3.5/site-packages/Trackma-0.6.1-py3.5.egg/trackma/lib/libhb.py", line 99, in check_credentials
    response = self._request( "/users/authenticate", post={'username': self.username, 'password': self.password} ).read().decode('utf-8')
  File "/usr/lib64/python3.5/site-packages/Trackma-0.6.1-py3.5.egg/trackma/lib/libhb.py", line 85, in _request
    return self.opener.open(self.url + url, post, 10)
  File "/usr/lib64/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/lib64/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.5/urllib/request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.5/urllib/request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645)>
```

**Comment by z411** [comment]
Seems to be a problem with your Python/SSL setup. You might want to upgrade your Python and OpenSSL packages.

To see your OpenSSL version:

    python3 -c 'import ssl; print (ssl.OPENSSL_VERSION)'

**Comment by kahrkunne** [comment]
Gives me 
```OpenSSL 1.0.2j 26 Sep 2016```
Python version 3.5.1

Both are completely up to date with my distribution's repos.

**Comment by MadeOfMagicAndWires** [comment]
Very strange. Bit of a long shot, but it seems that hummingbird's certificate was recently renewed (Thursday, 13 October 2016 at 02:00:00) so that might be the problem. Alternatively your system time could have messed with things as well. See if you can reach https://hummingbird.me/ (and https://hummingbird.me/api/v1/users/kahrkunne/library) via your browser without problem and that should tell you something. 
Otherwise I don't know what the issue is, it all works fine over here.

Regardless, making sure these kind of errors are handled gracefully should be easy, the issue is whether the libraries should fall back to plain http in case it does encounter such errors? Seems dangerous to do, especially by default.

**Comment by z411** [comment]
I finally could test and I'm getting the same error; but since I just reinstalled my OS I'm not sure either if it's a problem on my end, or due to the any incompatibility with the new SSL certificate @MadeOfMagicAndWires mentioned.

    openssl s_client -connect hummingbird.me:443
    140591925311120:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:s23_clnt.c:769:

**Comment by kahrkunne** [comment]
> See if you can reach https://hummingbird.me/ (and https://hummingbird.me/api/v1/users/kahrkunne/library) via your browser without problem and that should tell you something. 

Both can be reached without problem

**Comment by MadeOfMagicAndWires** [comment]
Well then I don't think it can be the certificate and I have officially exhausted all of my SSL expertise.

It's a bit hard to test for me, but with both of you having problems and nothing for me, as a hail mary it might be worth checking your local urllib version and MAYBE your `openssl version -f` for your comilation flags?

[Latest version of urllib](https://pypi.python.org/pypi/urllib3#changes) did have some fixes and changes with certificates so that might be it, but that's now nearly a month ago so I assume you'd have it.

**Comment by veluria** [comment]
You need the servername:

    openssl s_client -connect hummingbird.me:443 -servername hummingbird.me

**Comment by kahrkunne** [comment]
> openssl s_client -connect hummingbird.me:443 -servername hummingbird.me
Gives the same error as before

>it might be worth checking your local urllib version and MAYBE your openssl version -f for your comilation flags?
Not sure how ti find the urllib version, but for the other thing:
```compiler: x86_64-pc-linux-gnu-gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DL_ENDIAN -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -O2 -pipe -march=native -fno-strict-aliasing -Wa,--noexecstack```

**Comment by z411** [comment]
Are you using Gentoo or another source-based distro?

Hummingbird's certificate is a COMODO ECC certificate, so it needs the EC algorithms compiled into OpenSSL for the handshake to work.

OpenSSL compiled with the `--enable-ec` configuration flag connects properly:

    $ openssl s_client -connect hummingbird.me:443 -servername hummingbird.me
    depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
    verify return:1
    depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO ECC Certification Authority
    verify return:1
    depth=1 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO ECC Domain Validation Secure Server CA 2
    verify return:1
    depth=0 OU = Domain Control Validated, OU = PositiveSSL Multi-Domain, CN = sni64270.cloudflaressl.com
    verify return:1
    CONNECTED(00000003)
    [rest omitted]

Without it, it throws:

    $ openssl s_client -connect hummingbird.me:443 -servername hummingbird.me
    140609414076048:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:769:

[ECC seems to be patented](https://en.wikipedia.org/wiki/ECC_patents), so Gentoo with the `bindist` flag disables it.

In your compiler flags I see `-march=native` so I assumed you're also using Gentoo; in that case, disabling the `bindist` USE flag for the `dev-libs/openssl` package should fix it. The USE flag description explains:

> bindist : Disable EC algorithms (as they seem to be patented) -- note: changes the ABI

If you also have `net-misc/openssh` installed you'll have to disable it there too.

**Comment by MadeOfMagicAndWires** [comment]
@kahrkunne depending on your distribution it's probably installed through your package manager, so i'd try there first.
If it isn't, try `python -c "import pkg_resources; print(pkg_resources.get_distribution('urllib').version)"`

@z411 ECC is under a different flag: `-DECP_NISTZ256_ASM`

**Comment by kahrkunne** [comment]
Yes, I do use Gentoo. I did as you said and it works now, thanks.

**Comment by z411** [comment]
Great. Will probably add a note in the SSL error regarding this.
