### ISSUE TITLE
Error Opening Trackma GTK

### ISSUE THREAD

**Issue by garchomps** [z411/trackma#250]
Traceback (most recent call last):
  File "/usr/local/bin/trackma-gtk", line 7, in <module>
    from trackma.ui.gtkui import main
  File "/usr/local/lib/python2.7/dist-packages/trackma/ui/gtkui.py", line 38, in <module>
    import urllib.request
ImportError: No module named request

**Comment by MadeOfMagicAndWires** [comment]
As of version 0.6 trackma requires python 3.4 or above, so that's causing your problems.

Reinstall trackma using python 3 and everything should be fine.

**Comment by z411** [comment]
Should we add a check?

**Comment by MadeOfMagicAndWires** [comment]
I don't think it'll be necessary?

Anyone installing it from now on will just be using python 3, so it's just a matter of old users who haven't made the switch yet.
 Additionally, for those who use their distro's package manager to install trackma that responsibility is up to the packagers and the end-users shouldn't even experience any change so it's a subset of a subset.

Unless it's supposed to be backwards compatible I don't think we need to spend time checking for python versions even if it's just for an error message. People will have to switch to Python 3 *some day*.

**Comment by z411** [comment]
Point taken.
