### ISSUE TITLE
I cant start GUI

### ISSUE THREAD

**Issue by gugica** [z411/trackma#251]
Hello everyone.
I love this program, but since I switched desktops from LXDE to XFCE (Raspbian) I keep getting this error when I try to start trackma GUI. Its driving me crazy because I already tried installing a ton of different python packages to get this thing running but without much luck.
<img width="826" alt="screen shot 2016-10-25 at 11 20 30 pm" src="https://cloud.githubusercontent.com/assets/18504403/19704861/d3e23e38-9b09-11e6-9b6f-06c1e23931dc.png">

I would really appreciate your help.

**Comment by z411** [comment]
Did you install Pillow?

    # pip3 install Pillow

**Comment by gugica** [comment]
Thank you very much.
That fixed the problem now. Now I just want to know which package do I need to install for Qt interface. I know that I need to install Pyqt5, but i am not sure which package from that list should I install. (https://packages.debian.org/search?keywords=pyqt5)
I already tried with python-pyqt5 package, but even with that installed it didn't start the qt interface.
<img width="768" alt="screen shot 2016-10-26 at 7 46 42 am" src="https://cloud.githubusercontent.com/assets/18504403/19723466/b05f51d6-9b7b-11e6-9ff6-6a5cbf92f61b.png">

I really appreciate your help.

**Comment by veluria** [comment]
@gugica `python3-pyqt5`

**Comment by gugica** [comment]
Thank you very much 😊
