### ISSUE TITLE
[libanilist] Search special characters

### ISSUE THREAD

**Issue by Birdulon** [z411/trackma#258]
I've noticed with anilist that the search API uses special characters and as such searching for titles with e.g. `!` in them will turn up nothing unless the characters are escaped with a backslash. This might also apply to other APIs but I haven't tested those in a while.

Should the escapements be handled by the library and hidden from the user? Or perhaps it could be handled by the UI with an option to disable automatic escapement for advanced searching.

**Comment by joshstar** [comment]
Think this might be something I should fix on the AniList API side of things. I know sphinx search makes use of special characters like that for certain searching techniques, I thought I disabled it but will look into it.

**Comment by joshstar** [comment]
Should be fixed on the api side now.

**Comment by z411** [comment]
Thank you @joshstar .
