### ISSUE TITLE
[Site Support] Add support for anime-planet.com

### ISSUE THREAD

**Issue by Omar007** [z411/trackma#259]
Got wind of this program so I thought I'd check it out but found it has no support (yet?) for www.anime-planet.com.
So hereby a request for that ;)

Though tbh I don't believe they have an API available so this may be a no-go until that happens.

**Comment by z411** [comment]
Indeed they don't have a public API and they don't seem interested in exposing one either.

**Comment by z411** [comment]
Someone asked about this in their forums some time ago but they don't seem interested in exposing an API.

http://www.anime-planet.com/forum/threads/getting-ap-to-work-with-trackma.260670/
