### ISSUE TITLE
Tracma-gtk not opening

### ISSUE THREAD

**Issue by Szarcsak** [z411/trackma#268]
I have set up some settings for trackma-gtk and once I closed it I couldnt open it again.
I get this:
Engine: Can't auto-scan library: Operation not supported by current site or mediatype.
/home/szarcsak/.local/lib/python3.5/site-packages/trackma/ui/gtkui.py:82: Warning: value "1427" of type 'gint' is invalid or out of range for property 'subvalue' of type 'gint'
  Gtk.main()
/home/szarcsak/.local/lib/python3.5/site-packages/trackma/ui/gtkui.py:82: Warning: value "1014" of type 'gint' is invalid or out of range for property 'subvalue' of type 'gint'
  Gtk.main()
Can somebody tell me how to fix this, I now know that some functions are net ready yet, so if I could just somehow restore the default setting, that will do!

**Comment by dyskette** [comment]
Trackma saves its configuration in `~/.Trackma/config.json`, just rename that file.

**Comment by Szarcsak** [comment]
OK, I did rename then config.json but now I get this:
Data: Locking database...
Data: Reading metadata...
Data: Reading cache...
Engine: Can't auto-scan library: The set media directory doesn't exist.
Tracker: Initializing...
Tracker: Enabling tracker...
Tracker: pyinotify not available; using polling (slow).
/usr/local/lib/python3.5/dist-packages/Trackma-0.6.2-py3.5.egg/trackma/ui/gtkui.py:82: Warning: value "1094" of type 'gint' is invalid or out of range for property 'subvalue' of type 'gint'
  Gtk.main()
Sorry for trouble, but I'd like to use this program and  it just dont want to work :D

**Comment by Birdulon** [comment]
That would likely be related to the `last_height` and `last_width` properties in `~/.trackma/ui-Gtk.json`. Try changing `remember_geometry` to false and if that doesn't do it, rename the file so it generates a default one on startup.

**Comment by Szarcsak** [comment]
Wooaa, I found what the problem was...the remember_geometry was already on false so I wondered what the problem was...and then found out that the closetotray was set to true, so I changed everything tray related to false, and the program suddenly works...Thanks for the help! :D

**Comment by z411** [comment]
I don't see how that would warrant a crash though?

**Comment by Szarcsak** [comment]
No, it wasnt crashing! It just simply didnt start(the gtk version)... It brought up the gtk login screen, I logged in with my MAL account and then it just couldnt start...

**Comment by z411** [comment]
I see, I'll still check what's going on so I'll mark this as bug.

**Comment by Szarcsak** [comment]
Ok, I'll try to set up the same settings and help figure out what the problem was! Even through I'm a noob for this.

**Comment by Szarcsak** [comment]
Ok, I played with ui-Gtk.json file and this is what happened...When I installed trackma(the GTK version) it opened without any problem...so I opened the Global settings and played with it...I wanted my tracker to be always visible in tray so I changed the tray related settings...and thus tracma-gtk never opened aftr exiting...After you guys said to change the settings directly(sudo gedit) I found why it wouldnt start then(but I dont know  why and what caused it). So in the end it was tray related. I'm using Ubuntu 16.04(64bit) and no matter what settings I check I have no tray icon for trackma-gtk. 
Now I will put the errors I get when changing the tray related settings so you can figure out whats happening:

First settings:
> "close_to_tray": true,
>     "show_tray": true,
>     "start_in_tray": true,
>     "tray_api_icon": true,

The errors:

> Tracker: Initializing...
> Tracker: Enabling tracker...
> Tracker: pyinotify not available; using polling (slow).
> lsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
>       Output information may be incomplete.
> /usr/local/lib/python3.5/dist-packages/Trackma-0.6.2-py3.5.egg/trackma/ui/gtkui.py:82: Warning: value "1095" of type 'gint' is invalid or out of range for property 'subvalue' of type 'gint'
>   Gtk.main()
> lsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
>       Output information may be incomplete.
> lsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
>       Output information may be incomplete.
> lsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
>       Output information may be incomplete.
> lsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
>       Output information may be incomplete.
> lsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
>       Output information may be incomplete.
> ^Clsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
>       Output information may be incomplete.
> lsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
>       Output information may be incomplete.
> lsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
>       Output information may be incomplete.

It seems like its in loop or something...

Second settings:
> "close_to_tray": false,
>     "show_tray": true,
>     "start_in_tray": true,
>     "tray_api_icon": true,

The errors:

> Tracker: Initializing...
> Tracker: Enabling tracker...
> Tracker: pyinotify not available; using polling (slow).
> lsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
>       Output information may be incomplete.
> /usr/local/lib/python3.5/dist-packages/Trackma-0.6.2-py3.5.egg/trackma/ui/gtkui.py:82: Warning: value "1095" of type 'gint' is invalid or out of range for property 'subvalue' of type 'gint'
>   Gtk.main()
> lsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
>       Output information may be incomplete.

In loop.

Third settings:
> "close_to_tray": true,
>     "show_tray": true,
>     "start_in_tray": true,
>     "tray_api_icon": false,

The errors:

> Tracker: Initializing...
> Tracker: Enabling tracker...
> Tracker: pyinotify not available; using polling (slow).
> lsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
>       Output information may be incomplete.
> /usr/local/lib/python3.5/dist-packages/Trackma-0.6.2-py3.5.egg/trackma/ui/gtkui.py:82: Warning: value "1095" of type 'gint' is invalid or out of range for property 'subvalue' of type 'gint'
>   Gtk.main()
> lsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
>       Output information may be incomplete.

In loop.

I only tried half of the possibilities, but I'll try the other ones too as long as it helps. These are tried:

> "close_to_tray": false,
>     "show_tray": false,
>     "start_in_tray": true,
>     "tray_api_icon": true,
WORKS

> "close_to_tray": false,
>     "show_tray": false,
>     "start_in_tray": false,
>     "tray_api_icon": false,
WORKS

> "close_to_tray": false,
>     "show_tray": false,
>     "start_in_tray": false,
>     "tray_api_icon": true,
WORKS

> "close_to_tray": true,
>     "show_tray": false,
>     "start_in_tray": false,
>     "tray_api_icon": false,
WORKS

> "close_to_tray": true,
>     "show_tray": true,
>     "start_in_tray": false,
>     "tray_api_icon": false,
WORKS

> "close_to_tray": false,
>     "show_tray": true,
>     "start_in_tray": true,
>     "tray_api_icon": true,
ERROR

> "close_to_tray": true,
>     "show_tray": true,
>     "start_in_tray": true,
>     "tray_api_icon": true,
ERROR

> "close_to_tray": true,
>     "show_tray": true,
>     "start_in_tray": true,
>     "tray_api_icon": false,
ERROR

**Comment by z411** [comment]
Aren't you sure Trackma isn't actually running but starting hidden as a tray icon? That's what the start_in_tray option does.

**Comment by Szarcsak** [comment]
The tray icon definitely dont show up here... you can see this on the screenshots, I've checked the option...
![screenshot from 2016-12-26 23-52-54](https://cloud.githubusercontent.com/assets/24736651/21487391/102195c6-cbc8-11e6-8f6a-8969a5e7dffb.png)
Are these tracker files related to trackma, that I dont know but they are running after closing trackma.
![screenshot from 2016-12-26 23-56-48](https://cloud.githubusercontent.com/assets/24736651/21487390/1018c32e-cbc8-11e6-94ec-d8e1d38113af.png)

**Comment by dyskette** [comment]
> Are these tracker files related to trackma

No. Those are [GNOME's tracker](https://wiki.gnome.org/Projects/Tracker/).

**Comment by Szarcsak** [comment]
Well then, If nobody else reported this kind of something then ok, but the tray is not working on my pc, I dont mind, I happy that anything else is working(you are the mvp). Thanks for trying to fix it! :D

**Comment by z411** [comment]
Trackma is most probably starting minimized to tray, but the tray icon isn't showing for some reason. I'm assuming that's Unity in your screenshot. I wonder if GTK 3 has any trouble with Unity's tray.

**Comment by Szarcsak** [comment]
Well I can imagine this error cause of unity... but I dont plan changing it to anything else, I took quite the liking to unity...so I guess it's just unity thing! Anyway thanks again for trying...if other people didnt post this kind of tray related error the dont mind this issue... I'm good here! :D

**Comment by dyskette** [comment]
I do have a tray related issue, but on a different system. Fedora 25 GNOME Wayland. And is exactly like @z411 said.

> Trackma is most probably starting minimized to tray, but the tray icon isn't showing for some reason.

However, the tray icon works on X, and indeed starts minimized to tray there.

Maybe a difference between Unity's tray implementation and others?

**Comment by Szarcsak** [comment]
Sorry, I dont know how to check that trackma is running its tray hidden... and I'll be honest, I dont know what you mean by the tray icon "works on X", but if it cant be helped then it cant be helped! :D
