### ISSUE TITLE
Can't install at all.

### ISSUE THREAD

**Issue by prrg** [z411/trackma#271]
So I installed everything that was asked for (http://z411.github.io/trackma/) and did the "sudo python setup.py install" command (later I did it with "python3"), but the setup.py file apparently asks for stuff that isn't in the set of files at all, like a folder called "setuptools".

I tried again with the updated stuff from the README/github ("python3" instead of "python"; re-installing from this place's master) and still doesn't work. Using "pip3 install Trackma" gives out this error:

`Invalid script entry point: <ExportEntry trackma-qt4 = trackma.ui.qt4ui:None ['qt']> for req: Trackma - A callable suffix is required. Cf https://packaging.python.org/en/latest/distributing.html#console-scripts for more information.`

I'm lost.

**Comment by z411** [comment]
Hello, what OS are you using? And what version of PIP? (`pip3 --version`)

>but the setup.py file apparently asks for stuff that isn't in the set of files at all, like a folder called "setuptools"
Did you install setuptools system-wide? That's a module you need to install it using the setup.py script.

**Comment by prrg** [comment]
Ubuntu 16.04, PIP 8.1.1

No worries though, I got it running already. No idea what happened. It just installed after trying a bunch of times.

**Comment by z411** [comment]
Ok, good to know.
