### ISSUE TITLE
pyinotify: after first episode consequent episodes don't get updated

### ISSUE THREAD

**Issue by 4re** [z411/trackma#284]
Basically this pattern gets repeated:
```
[D] Tracker (pyinotify): Sending last state 1 ({'titles': ['Ao no Exorcist: Kyoto Fujouou-hen', 'Blue Exorcist: Kyoto Impure King Arc', 'Blue Exorcist: Kyoto Saga'], 'title': 'Ao no Exorcist: Kyoto Fujouou-hen', 'id': 33506, 'my_progress': 2, 'total': 12, 'type': None}, 3)
[D] Tracker (pyinotify): Got CLOSE event: /home/d/Downloads [HorribleSubs] Ao no Exorcist - Kyoto Fujouou-hen - 03 [1080p].mkv
[D] Tracker (pyinotify): Our pid hasn't closed the file.
[D] Tracker (pyinotify): Got OPEN event: /home/d/Downloads [HorribleSubs] Ao no Exorcist - Kyoto Fujouou-hen - 04 [1080p].mkv
[D] Tracker (pyinotify): There's already a tracked open file.
[D] Tracker (pyinotify): Got CLOSE event: /home/d/Downloads [HorribleSubs] Ao no Exorcist - Kyoto Fujouou-hen - 04 [1080p].mkv
[D] Tracker (pyinotify): A different file was closed.
```
My guess is when a new episode plays with the same PID, somewhat trackma doesn't acknowledge that and keeps thinking it's tracking something different from what it's actually playing currently.

**Comment by z411** [comment]
Are you using some playlist feature in your player where the subsequent episode gets played immediately after the previous one ends? If so, the latest commit should fix it.

**Comment by 4re** [comment]
Yes, I'm using autoload.lua with mpv.
Gonna check right now if this commit fixes it.

**Comment by 4re** [comment]
I watched 3 episodes straight, popups about something being updated were appearing, so I was thinking it was working right, but only the first episode was actually updated.
https://gist.github.com/4re/d6bc6d9bd988091d21d5b7d7bcf2ea57

**Comment by z411** [comment]
Thanks for the feedback. Will proceed to do some testing.

**Comment by z411** [comment]
Found the problem; it was an issue in the tracker itself rather than the inotify code so it was affecting all trackers. The `updated` flag was getting reset only if the previous file was closed first, not all the time. The entire tracker code went through several changes lately so we're hitting different bugs. Latest commit should fix that.

**Comment by 4re** [comment]
It works!! Thank you! ^__^

**Comment by z411** [comment]
I lowered the wait time for the CLOSE event, I re-tested and it still works, but in case the tracker broke for you again please tell me.
