### ISSUE TITLE
trackma-qt doesn't start

### ISSUE THREAD

**Issue by nekoswag** [z411/trackma#285]
trackma-qt fails to start here.
I installed inotify-tools, python3-qt5, python3-Pillow and python3-urwid.

> Warning: DateUtil is unavailable. Next episode countdown will be disabled.
> Trackma-qt v0.7.1
> Traceback (most recent call last):
>   File "/usr/bin/trackma-qt", line 11, in <module>
>     load_entry_point('Trackma==0.7.1', 'gui_scripts', 'trackma-qt')()
>   File "/usr/lib/python3.6/site-packages/trackma/ui/qtui.py", line 3198, in main
>     mainwindow = Trackma(debug)
>   File "/usr/lib/python3.6/site-packages/trackma/ui/qtui.py", line 148, in __init__
>     accountman_widget.show()
> NameError: name 'accountman_widget' is not defined

DateUtil (on my system "python3-python-dateutil") is also not mentioned as a dependency.

The other interfaces (cli and curses) seem to work.

openSUSE Tumbleweed 20170304 (KDE Plasma 5.9.2, KDE Frameworks 5.31.0, QT 5.7.1)

**Comment by z411** [comment]
Sorry, it was a typo in the code. Should be fixed.
