### ISSUE TITLE
libanilist: APIError when specifically on searching "Kuzu no Honkai"

### ISSUE THREAD

**Issue by MadeOfMagicAndWires** [z411/trackma#286]
Can't at look into this to deeply at the moment, but minimal debugging shows that anilist returns "Bad Request" errors anywhere from `Kuzu no H` on.   
Very specific, might be on anilists end, but who knows.

Also as a small nitpick the standard APIError for 400 errors very definitely states that the PIN is invalid, while for example in this case is not the case; this could probably be changed into something more open and descriptive. I can see most people just refreshing their perfectly good PIN, which in this case wouldn't work.

**Comment by z411** [comment]
The server just returns this:

    <html>
    <head>
    <title>400 Bad Request</title>
    </head>
    <body bgcolor="white">
    <center><h1>400 Bad Request</h1></center>
    <hr><center>nginx/1.11.9</center>
    </body>
    </html>

So I don't see a way we can pinpoint and handle the exact error that's occurring. This seems to be a bug upstream.

**Comment by z411** [comment]
I shouldn't get ahead of myself; I'll debug if there's something wrong with my request.

**Comment by MadeOfMagicAndWires** [comment]
Cheers!
