### ISSUE TITLE
Can't install Trackma, "Invalid script entry point"

### ISSUE THREAD

**Issue by nekoswag** [z411/trackma#288]
I get this output while trying to install Trackma:

> hostname:/home/username # pip3 install Trackma
> Collecting Trackma
> Installing collected packages: Trackma
> Invalid script entry point: <ExportEntry trackma-qt4 = trackma.ui.qt4ui:None ['qt']> for req: Trackma - A callable suffix is required. Cf https://packaging.python.org/en/latest/distributing.html#console-scripts for more information.

KDE Plasma 5.9.2
KDE Frameworks 5.31.0
Qt 5.7.1
openSUSE Tumbleweed 20170324

I have both python-qt5 and python-qt4 installed for other applications.

**Comment by z411** [comment]
Uploaded new release that should fix this. Please check.

**Comment by nekoswag** [comment]
Thanks, it works now.
