### ISSUE TITLE
trackma-qt doesn't close

### ISSUE THREAD

**Issue by nekoswag** [z411/trackma#289]
trackma-qt doesn't close correctly. It stays open in the system tray, when showing the window again, it says "Engine: Unloading" in the status bar.

output when launching from terminal:

`Trackma-qt v0.7.3`
`Engine: Scanning local library...`
`Tracker (pyinotify): Initializing...`
`Tracker (pyinotify): Using pyinotify.`
`Ready.`
(select Show -> Quit)
`Engine: Unloading...`
(stays like this)

KDE Plasma 5.9.2
KDE Frameworks 5.31.0
Qt 5.7.1
openSUSE Tumbleweed 20170324

#206 
Maybe it's related to this, but I have a different console output.

**Comment by hbers** [comment]
Same here. I just disabled the "show tray icon" setting and now it closes fine.
I too am on KDE 5 but on Arch.

**Comment by z411** [comment]
It seems this only occurs on KDE 5, correct? Unfortunately I'm away from home right now so I'll attempt to reproduce it in the weekend.

**Comment by z411** [comment]
I can reproduce it. Using Qt4 everything works fine, but with Qt5 not only it doesn't close, but the tray icon doesn't even appear.

**Comment by z411** [comment]
Please check if the latest commit fixes it.

**Comment by hbers** [comment]
Problem is solved here. Thanks for your work.

**Comment by 4re** [comment]
This fixed it for me too. Thx!
