### ISSUE TITLE
[kitsu API] API error: 100: rating - must be greater than or equal to 2

### ISSUE THREAD

**Issue by Kcchouette** [z411/trackma#294]
## Did it reproduce in all case

It seems I can reproduce the API error since yesterday.

## How reproduce this error

1. Show > Add/search a new Show
2. Search a show that you have not in your list
3. Add it
4. Sync your list (and you'll have the error)

## The log
```
libkitsu: Searching for re:crea...
Data: Saving info DB...
Data: Saving queue...
Data: Saving cache...
Data: Queued add for Re:Creators
Data: Processing queue...
libkitsu: Adding show Re:Creators...
Data: Can't process Re:Creators, will leave unsynced.
Data: Info: API error: 100: rating - must be greater than or equal to 2
Data: Saving cache...
Data: Saving queue...
Data: Saving queue...
Data: Cleared queue.
```

**Comment by z411** [comment]
There seems to be changes being done upstream to the API, will look it up.

**Comment by z411** [comment]
It seems it was a bug that has been fixed upstream.

**Comment by Kcchouette** [comment]
indeed, thank you.
