### ISSUE TITLE
Can't connect to plex

### ISSUE THREAD

**Issue by cerinthus** [z411/trackma#298]
Cannot connect to claimed plex server, presumably because no X-Plex-Token.  Sessions provides 401 without it.

**Comment by z411** [comment]
Thank you for reporting. I currently have no way to test Plex; @Hairo ?

**Comment by cerinthus** [comment]
It's definitely what it is, just playing with it myself.  Since it doesn't seem to affect many users, adding something like self.plex_token in plex.py for users to manually enter it resolves the issue (unless you want it in the GUI).

something like:

        self.plex_token = "<ENTER TOKEN HERE>"

And then changing line 104 to:

        session_url = "http://"+self.host_port+"/status/sessions?X-Plex-Token="+self.plex_token

Resolves it without having to request an X-Plex-Token (though it's less user friendly)

**Comment by Hairo** [comment]
What plex version? Was there a recent update? I was using it with no issues last night.

**Comment by cerinthus** [comment]
No recent update. Is your server claimed?

It shouldn't work without an x-plex-token if it is.  All URLs should require it.

https://support.plex.tv/hc/en-us/articles/204059436-Finding-an-authentication-token-X-Plex-Token

**Comment by Hairo** [comment]
oh, i don't login in the device i'm using to watch anime.

Apparently it can be solved with https://forums.plex.tv/discussion/129922/how-to-request-a-x-plex-token-token-for-your-app/p1

Though it would require the plex username and password, i'll work on it soon.

**Comment by z411** [comment]
Indeed requesting the token out of a username and password sounds like the correct thing to do. There isn't any mechanism to ask the user for credentials, I guess the way to do it would be to specify them in the config/settings panel.

**Comment by cerinthus** [comment]
I can confirm the pull request fixes it.  Once it's merged this can be closed.
