### ISSUE TITLE
A summary of win32 issues

### ISSUE THREAD

**Issue by qyot27** [z411/trackma#3]
Since it's mentioned as a possible TODO item, I wanted to see how well the current git master of wMAL works on win32 as-is.  The following is pretty much what I've got so far:

In all cases, the biggest issue is that Python on Windows is all kinds of nasty to get modules into.  You can have Python on your PATH, but trying to call easy_install to get stuff installed doesn't work without explicitly navigating to its directory first (which is probably safest since who knows if it would end up in the right spot if easy_install was on the PATH).

In some cases, this requires downloading the packages manually and installing them.  In other cases (like readline) it requires getting Python-oriented substitutions for GNU tools that don't ship with MSys/MinGW or Cygwin.

wmal.py: works perfectly, albeit with a bit of a cosmetic problem with the command prompt.  [See screenshot] (http://imageshack.us/a/img197/3346/wmalwin32prompt.png).  I've used it successfully to sync, update, score, and change status while I've been in Windows.

wmal-curses.py: probably has the bulk of the issues with external modules not being present or needing workarounds to get working.  I still haven't got it working; it's currently sitting at missing fcntl - Google seems to turn up the result that this needs to be altered to either use Windows system calls or to use some sort of platform-agnostic form.  curses itself is known to be problematic or nonexistent on Windows, but there seem to be some alternatives that can be used.

wmal-gtk.py: not working either, but in seemingly different ways.  If there is no 'lock' file in .wmal/mal, there are no warnings output to the Prompt, the outline of the window shows up, but not any of the internal window elements (I vaguely seem to remember that it does show up sometimes, or did at one point...not really sure).  If 'lock' is present, there are warnings about the file locking that get output to the Prompt (see below), but now the window and all its internal decorations/elements show up, although it gets stuck in a loop and never loads any of the MAL content.  Clicking the close button doesn't do anything, requiring me to close the Prompt instead.  As mentioned, I seem to remember that the first time I ever tried launching the GTK interface, it was without 'lock' present, but the window was still correctly drawn (none of the content appeared, though).

```>python27 wmal-gtk.py
Starting engine...
Locking database...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\WINDOWS\Python27\lib\threading.py", line 551, in __bootstrap_inner
    self.run()
  File "C:\WINDOWS\Python27\lib\threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wmal-gtk.py", line 412, in task_start_engine
    self.engine.start()
  File "C:\dap\vid\Incoming Files\wmal-python\modules\engine.py", line 113, in start
    (self.api_info, self.mediainfo) = self.data_handler.start()
  File "C:\dap\vid\Incoming Files\wmal-python\modules\data.py", line 97, in start
    self._lock()
  File "C:\dap\vid\Incoming Files\wmal-python\modules\data.py", line 329, in _lock
    raise utils.DataFatal("Database is locked by another process. "
DataFatal: Database is locked by another process. If you're sure there's no other process is using it, remove the file ~/.wmal/lock```

**Comment by z411** [comment]
It's been a long time but the Qt interface, and the tracker are working nicely under Windows, so I'll be closing this.
There are working alternatives in Windows to Taiga, but Windows support will still be provided for completeness support.
