### ISSUE TITLE
ImportError:No module named request

### ISSUE THREAD

**Issue by NotableSpectator** [z411/trackma#302]
When running trackma-gtk I get an error stating there's no request module although I've installed it from pip.
I've only recently started using Linux (Ubuntu) so I'm still a bit inept regarding what I'm supposed to do

**Comment by z411** [comment]
Trackma doesn't use the request module. What steps did you follow to install it? Did you install it using pip3? Trackma runs on Python 3, not Python 2 which is default in most distributions.
