### ISSUE TITLE
recognition and percent

### ISSUE THREAD

**Issue by tom2411** [z411/trackma#312]
hello,
I wanted to know how trackma recognize the anime because i watch my anime on VLC and it don't work.
I also wanted to know how can I put the number on the percent.

If someone can help me.
Tom.

**Comment by z411** [comment]
Hello,

For VLC to work, you must open Trackma, go to Options->Settings and put `vlc` in the "Process name" field.

As for the second question, if you mean changing the progress you must select the show and click the + and - buttons; you can also enter the progress manually.

**Comment by tom2411** [comment]
thank you for answered me but the second question it's how can display the number of percent  on the rubric "Percent"?

**Comment by tom2411** [comment]
i have put vlc like you said and I watch an anime but it don't add a episode automatically.

**Comment by z411** [comment]
Could you run it in a terminal and copy paste the output?
