### ISSUE TITLE
Tracker crashes when prompting to add a new show

### ISSUE THREAD

**Issue by albel727** [z411/trackma#318]
If "Ask to add new shows" is enabled, then upon closing the media player the tracker thread crashes and stops tracking anything henceforth.

The error is "TypeError: string indices must be integers" and the backtrace points at the following code in `TrackerBase._update_state()`:

```python
if self.last_show_tuple:
  (last_show, last_show_ep) = self.last_show_tuple
  self._emit_signal('playing', last_show['id'], False, last_show_ep)
```

The last line errors out, because `last_show` in the case of an unknown show is actually just a string. This is because of the following code in  `_get_playing_show()`

```python
if self.not_found_prompt:
  return (utils.TRACKER_NOT_FOUND, (show_title, show_ep))
else:
  return (utils.TRACKER_NOT_FOUND, None)
```

where `show_title` is just a string, instead of a dictionary with series info.

I've tested the following fix to `TrackerBase._update_state()` locally, and it seems to behave correctly:

```python
if self.last_show_tuple and self.last_state == utils.TRACKER_PLAYING:
```

**Comment by albel727** [comment]
Incidentally, I noticed there's a related pull request https://github.com/z411/trackma/pull/307. I wonder if it would be a better fix.

**Comment by albel727** [comment]
Well maybe not, since that PR ends up emitting `unrecognized` signal twice, and so it opens two identical "Add show" popups. It's easy to fix though.

**Comment by z411** [comment]
I don't like the idea of mixing data types that much; I changed it to use a dummy show with ID 0 instead. Please check if that fixes it.

**Comment by albel727** [comment]
It does, thanks.
