### ISSUE TITLE
trackma-qt not working for me!

### ISSUE THREAD

**Issue by Unkdu** [z411/trackma#320]
i wanted to use the trackma-qt, installed all the reqs... i can use the normal trackma.. the trackma-gtk
but not the one i want... ( the qt).... When i try to use it this the answer from the terminal:

> "Couldn't import Qt5 dependencies. Make sure you installed the PyQt5 package.
> Couldn't import Qt dependencies. Make sure you installed the PyQt4 package."

help me plz ? :/

Im on ubuntu 17.10 btw.

**Comment by zJoul** [comment]
Silly question, but did you install the PyQt5 package ?
Apparently, it's name is : [python3-pyqt5](https://launchpad.net/ubuntu/artful/+package/python3-pyqt5)

**Comment by Unkdu** [comment]
had the PyQt4 only ... now i installed the PyQt5 and it gives another error.. :/
 
> Segmentation fault (core dumped)

am i doing something wrong?

**Comment by zJoul** [comment]
Do you have a full output of the error when you lanch it from the terminal ?

And apparently you can use `trackma-qt4` to use PyQt4.
