### ISSUE TITLE
[Docker] Trackma Docker image

### ISSUE THREAD

**Issue by frosty5689** [z411/trackma#323]
Hi,

Just wanted to let people know for those that might be interested in running Trackma on a home server inside Docker. I have the Docker image setup so it can be fully configured using only environment variables. It can run in the background and automatically restart depending on restart policy. I have been using it for months to automatically update my MAL list through my Plex server

Feel free to let me know if there are improvements that can be made.

https://hub.docker.com/r/frosty5689/trackma/

**Comment by z411** [comment]
Thank you, added to README.
