### ISSUE TITLE
Trackma doesn't recognize episodes in subfolders not named after series

### ISSUE THREAD

**Issue by Ashymad** [z411/trackma#333]
With #293 merged, if an episode of anime is in subfolder of the watch directory, named differently than the series name, it is not recognized. For example if I wanted to have my anime categorized by genre in folders named e.g. `sci-fi`, `fantasy`, `slice-of-life`, trackma will join the folder name with episode name, causing it to be not recognized.

**Comment by z411** [comment]
I was expecting the PR to do that which I wasn't merging it... either way an option to disable it would be fine or would you prefer a more complex solution?

**Comment by Ashymad** [comment]
I suppose a simple option to disable it is enough. I can send a PR after the weekend if you want.
