### ISSUE TITLE
[Feature Request] Discord Rich Presence

### ISSUE THREAD

**Issue by SynderBlack** [z411/trackma#341]
Would be cool to have, kinda like how Taiga does it.
The idea would be to have trackma show what anime and which episode you're currently watching.

**Comment by z411** [comment]
Interesting. For now it could be implemented via hook.

**Comment by SynderBlack** [comment]
From what I can see a hook would only allow for a toggle, rather than streaming your progress. The idea was to show a progress bar for how long you've been watching.
Just a little to think about. For now a hook is alright.

**Comment by Birdulon** [comment]
Trackma only detects file open/close, it would need media player
integration for playback position. Granted, MPRIS integration might be
pretty nice for other things too.

**Comment by molkoback** [comment]
Here's an experimental but working hook https://github.com/molkoback/trackma/blob/master/hooks/discord_presence.py
Not sure if we're allowed to start new threads in hooks tho.

**Comment by SynderBlack** [comment]
regarding position, it might not be needed if we can somehow get the length of the episode, since you can send a start time and end time to achieve the same effect. So a hook would be enough (if the show param has some episode_length key)

regarding your example, that's a selfbot, which is banned on discord. its possible to use IPC regularly.

**Comment by FichteFoll** [comment]
You might be interested in my RPC implementation. I intend to flesh it out into a proper pypi package eventually, but for now it's included in my discordrp-mpris tool: https://github.com/FichteFoll/discordrp-mpris Has a synchronous and asynchronous variant.

**Comment by rollingmoai** [comment]
This should now be resolved in #542
