### ISSUE TITLE
i am getting wierd error

### ISSUE THREAD

**Issue by Zocex** [z411/trackma#342]
https://i.imgur.com/oPExrk4.png
i am trying to install trackma on windows.

**Comment by z411** [comment]
It looks like an authentication error. Could you try removing the account and creating it again? When creating it, it should ask you to visit a link and you should log into your account there. It will then return a PIN code which you should copy and paste in Trackma.

**Comment by Zocex** [comment]
oh i am very sorry. it turns out i put different pin. instead of the correct pin, i put my own pin from the site lol. thank you for the program tho
