### ISSUE TITLE
AniList API v1 shutdown - Migration to v2

### ISSUE THREAD

**Issue by joshstar** [z411/trackma#343]
AniList API v1 was given 6 months before it was meant to be shut down after API v2 went stable.
I made a few announcements about this and sent out emails to developers who had registered API v1 clients.

It looks like trackma is still using API v1, which was meant to be shut down on May 1st, due to some issues on AniList's part, API v1 is still running, though will likely only up for another 2 weeks or so, as the majority of applications have already migrated to v2.

Super sorry if you didn't hear about all this, as this would be super short notice.

[Api v2 docs can be found here](https://github.com/AniList/ApiV2-GraphQL-Docs), if you check the migration folder theres a number of queries that aim to replicate v1's rest call data set, so hopefully they help with the possible migration.

**Comment by z411** [comment]
Hello Josh, thank you for your concern. I haven't been able to work on my open source projects since last year and as such I missed the shut down date, so there's absolutely no need to apologize for it is an issue on my side. I will start work on this ASAP.

**Comment by Birdulon** [comment]
@z411 I'd been looking over the migration docs for a while before this, I can handle it if you'd prefer.

**Comment by Birdulon** [comment]
@z411 If it's any help, here's authentication and list fetching 613d8f2

@joshstar I'm impressed with the v2 API so far, solves a number of difficulties I had with the v1!

**Comment by z411** [comment]
Merged most Anilist v2 implementation into the `anilistv2` branch.

**Comment by z411** [comment]
Merged into `master`. Should work but we have to do something to support different scoring schemes in a standard way, as Kitsu does this as well.

**Comment by Birdulon** [comment]
Qt UI breaks on the new next episode format (string -> int timestamp). I had a fix in with my changes which accommodated both, but perhaps invalidating the old cached entries and just using the new ones is better?

**Comment by z411** [comment]
The old cache should be automatically invalidated (the data handler now checks for the API version as well) so accommodating the old one shouldn't be necessary. My preferred solution would be for us to use a standard format instead, such as a `datetime.datetime` object as the rest of Trackma does, so as any changes in this or future APIs didn't require a change in the UI as well.

**Comment by z411** [comment]
This reminds me, do we need the `dateutil` module? We don't need its `parse` functionality anymore and comparing the UTC datetime to `datetime.datetime.utcnow()` should be enough to get rid of `dateutil.tz.tzutc()`.

**Comment by Birdulon** [comment]
We can do time until next episode without it, but if we wanted to e.g. display the airing time in local time it may still be useful.

**Comment by z411** [comment]
libanilist should return a UTC datetime now and the Qt UI should handle it accordingly. I removed the dateutil dependency for now as it doesn't necessary currently. We can add it back eventually, but as far as I know Python's native `datetime` can compute timezones as well.

**Comment by Birdulon** [comment]
Can confirm, `datetime` is perfectly capable of providing local timezone info. Even in the event of another API using datetime strings we could write a simple parser for that with no `dateutil` dependency.

**Comment by z411** [comment]
Fixed and added some things, I've been using it myself and it seems to work fine, I think it's safe to assume basic migration is complete. Thank you for your work @Birdulon !

**Comment by FichteFoll** [comment]
When trying to open trackma (any interface) for my anilist account, I get this notice and it shuts down:

```
APIFatal: This appears to be a V1 API PIN. You need a V2 API PIN to continue using Anilist.
```

Since apparently the V2 API is working (?), it would be nice if trackma provided me with a way to get this new V2 API PIN? Or do I have to remove the account (manuall through pickle)?

I'm running latest `master`.

**Comment by z411** [comment]
Deleting the account and recreating it in Trackma itself should be enough.

Maybe an Edit account/Re-authorize function would be more intuitive, I guess, but deleting and creating it again should work for now.

**Comment by FichteFoll** [comment]
Yeah, a function to catch that problem and either deleting the account or attempting to recreate it with the same user name would certainly be better.

Fortunately I know Python so I can edit `accounts.dict` manually, but many other people will likely have to resort to deleting that file instead. Tbh losing your other accounts isn't too bad effortwise, but it's still a bad experience.

**Comment by Birdulon** [comment]
The Update account dropdown on the qt account list should do it.

**Comment by FichteFoll** [comment]
(Though, if you have the account selected as default, you can't get there since the app will show an error modal after starting and then quit, without ever showing the main window or account selector.)

**Comment by Birdulon** [comment]
That will definitely need a fix then, default account errors should kick back to the account selection dialog.

**Comment by SolarAquarion** [comment]
I keep on getting this 

`Error: Fatal engine error: Invalid request: b'{"data":{"Viewer":null},"errors":[{"message":"Invalid token","status":400,"locations":[{"line":1,"column":2}]}]}'`

**Comment by z411** [comment]
Did you delete our old account and create a new one?

**Comment by SolarAquarion** [comment]
Yes

**Comment by RunAge** [comment]
@z411 I have same error ```Error: Fatal engine error: Invalid request: b'{"data":{"Viewer":null},"errors":[{"message":"Invalid token","status":400,"locations":[{"line":1,"column":2}]}]}'```

**Comment by SolarAquarion** [comment]
I think this error only shows up in trackma-gtk

**Comment by z411** [comment]
@RunAge @SolarAquarion I'm assuming it had to do with GTK's account creation dialog having a 128 character limit for the token which is shorter than Anilist's. I removed the limit, please try recreating your account and logging in with the GTK UI.

**Comment by Birdulon** [comment]
Just did a new OS install and noticed that the pip version threw up an invalid PIN dialog. Guess that'll need updating and the master version number will need to be incremented accordingly.

**Comment by z411** [comment]
Done. There also should be no issues editing your account as UIs should show you the account dialog after the PIN error.

**Comment by lrenaud** [comment]
I got the 0.7.5 release and the application is autoclosing after providing an GUI error indicating the conventional "This appears to be a V1 API PIN. You need a V2 API PIN to continue using Anilist."

Trackma then quits regardless of which interface I try to launch. I realize I can frag my accounts.dict file to get past this, but the behavior is libel to produce a few odd bug reports for users not aware of what's going on behind the scenes.

**Comment by purposelycryptic** [comment]
@Irenaud - Can confirm less-informed users becoming confused, as it happened to me - I knew enough to know some file had to be edited or nuked, but it took a few mins of trial and error to figure out which. I had experienced the same issue after initially setting up Trackma to auto-login while using a Plex password that includes symbols (same insta-crash behavior, not sure if that has changed since).

I guess it's some sort of bug that causes the GUI versions to hard-crash on authentication errors? I'm on Windows, so I can only speak for the QT version in terms of GUI, but good to know the CLI version seems to bypass or reset whatever causes the crash.

**Comment by z411** [comment]
Pushed to pip; I tested it and it works so far, tell me if there are issues.

**Comment by lrenaud** [comment]
@z411 Thank you.

I pulled my backup .trackma account data from yesterday and verified it against 0.7.6. Graceful failure as desired, and the account chooser is presented after the error window pops up. Everything works like a champ after updating the API key.

**Comment by z411** [comment]
Great, thanks for reporting and confirming!

**Comment by z411** [comment]
Trackma should be able to handle different scoring formats now. Any issues please don't hesitate to report.

**Comment by z411** [comment]
I've been using it for a while and all features seem to be working; if there are any issues please open a new issue.
