### ISSUE TITLE
Shortcut to increase episode counter by one for console interfaces

### ISSUE THREAD

**Issue by FichteFoll** [z411/trackma#353]
Both the cli and the curses interfaces don't have a quick way to increase the episode counter by one. You always have use the "update" function and write the new number manually.

### curses

A possible solution would be to make the "update" command default to the *next* number rather than the current, or to add a binding to <kbd>+</kbd> and have that increase the number by one (and similarly <kbd>-</kbd>).

### CLI

For the CLI, the second parameter to `update` could be made optional.

**Comment by z411** [comment]
I think I like the +/- binding better.
