### ISSUE TITLE
MyanimeList

### ISSUE THREAD

**Issue by tom2411** [z411/trackma#356]
Hello, I write this post because I can't synchronize my episode on Myanimelist, but I saw that Myanimelist was down. Now the site, is operational so I wanted to know if there will have a update on this app for the Myanimelist database ?

**Comment by z411** [comment]
This is being discussed in #340 - the MAL API is down so every non-official application has no way of working. See this tweet from the MAL staff:

https://twitter.com/myanimelist/status/1007284296070070278
