### ISSUE TITLE
Can you turn this into a snap and put it in the snap store?

### ISSUE THREAD

**Issue by xrishox** [z411/trackma#363]

**Comment by z411** [comment]
Sorry I don't use the Snapstore so I don't think I'd have the time and motivation to maintain it myself, if anyone else wants to do it please feel free to do so, and I'll consider it/re-open if I ever get to use it myself in the future.

**Comment by QEDeD** [comment]
@z411 I fear the same goes for distribution via Flatpak or Appimage?
