### ISSUE TITLE
No idea how to install on Manjaro

### ISSUE THREAD

**Issue by Lyorek** [z411/trackma#375]
I followed the steps on how to install a package from the AUR here: https://wiki.archlinux.org/index.php/Arch_User_Repository#Prerequisites
however, when i go to run any UI except for the base UI i just get errors stating the dependencies could not be found. I've been able to install Trackma on Debian based systems without any issue, but I have no idea how to go about it here.

**Comment by leonardo2707** [comment]
You downloaded PKGBUILD in AUR and ran makepkg -si in it?

Try to use a AUR helper, I recommend yay, can be installed with `sudo pacman -S yay`,  it's very simple to install programs with yay, just run without being root, `yay -S trackma-git`, it will download the package build from aur and do the same thing as makepkg, it should work, have you installed base-devel? in the wiki says that it is necessary to use aur.

Anyway, in readme.md in the root of the project of the trackma shows how to install with python3-setuptools and pip3, however I find it easier by aur with yay.

**Comment by FichteFoll** [comment]
All the various ui libraries are optional dependencies because you only need them for the specific frontend. You need to install them manually, I. E. `pac-man -S python-urwid`. 

https://aur.archlinux.org/packages/trackma-git

**Comment by Lyorek** [comment]
I tried installing urwid just through pacman -S python-urwid when i initially attemtped to install trackma and received an error mesage sayin that the package python-urwid didn't exist. 
After trying again with --asdeps added it seems to have work, no idea whether having that solved the problem or it was something else but either way it works now, thanks!

**Comment by FichteFoll** [comment]
No, you probably just mistyped it earlier.
