### ISSUE TITLE
Trackma-curses won't load Anilist completed

### ISSUE THREAD

**Issue by Qwerty-Space** [z411/trackma#380]
As you can see, it shows my planning list:
<details><summary>Image (click to view)</summary> 

![image](https://user-images.githubusercontent.com/6967592/52890659-d83c1500-317d-11e9-8fd5-ca4c400a9b99.png)
</details>

But not my completed list:
<details><summary>Image (click to view)</summary> 

![image](https://user-images.githubusercontent.com/6967592/52890668-e38f4080-317d-11e9-9ce0-8e1cd5ff6c72.png)
</details>

Despite having a lot of completed anime:
<details><summary>Image (click to view)</summary> 

![image](https://user-images.githubusercontent.com/6967592/52890693-091c4a00-317e-11e9-99fb-22aa3458a469.png)
</details>

**Comment by z411** [comment]
Hello, does this happen on the curses interface exclusively?

If it happens on other interfaces as well, then it's a deeper issue; in that case could you upload the file ` /.trackma/<user>.anilist/anime.list`? Thanks.

**Comment by Qwerty-Space** [comment]
@z411 it happens on all interfaces

**Comment by llomellamomario** [comment]
file:///home/freeman/.trackma/freemansfreedom.anilist/anime.list
Same problem, here's mine

**Comment by llomellamomario** [comment]
[anime.list.txt](https://github.com/z411/trackma/files/3008020/anime.list.txt)
Have the same problem, both in QT, curses and GTK. And my anime.list

**Comment by z411** [comment]
@llomellamomario Hi, thanks a lot for the file. Checking your file it seems completed shows didn't even get downloaded at all, as they aren't present at all in the list:

```
z411.list
Filesize: 430KB
Contents: {'DROPPED': 36, 'PAUSED': 3, 'COMPLETED': 681, 'PLANNING': 15, 'CURRENT': 16}

llomellamomario.list
Filesize: 98KB
Contents: {'DROPPED': 39, 'PAUSED': 17, 'PLANNING': 82, 'CURRENT': 32}
```

So this seems like an issue in our API implementation of Anilist.

As you can see my list works fine, so would you mind if I ask your Anilist username so I can fetch your list and start debugging the issue? Just the username. You can also send it to my e-mail z411@omaera.org - thanks.
(cc @Qwerty-Space)

**Comment by llomellamomario** [comment]
Here my username: freemansfreedom and my profile: https://anilist.co/user/freemansfreedom/ Also a new anime.list. Yesterday I finished one of the seasonal anime, and it was listed under completed, no problem. It dissapeared from the list once I synced with Anilist, but it actually updated remotely. So the problem seems to lie with the sync functionality. And for the record I'm using the AUR package on Manjaro.
[anime.list.txt](https://github.com/z411/trackma/files/3013058/anime.list.txt)

**Comment by z411** [comment]
Thanks @llomellamomario - could you check if the latest commit fixes the issue, and if it does, is everything working correctly?

**Comment by llomellamomario** [comment]
And now it is working as intended, everything seems fine. Thanks for the fix!

**Comment by Qwerty-Space** [comment]
In addition to this, I noticed it doesn't download rewatching?

**Comment by FichteFoll** [comment]
See #385.
