### ISSUE TITLE
Interfacing with the library

### ISSUE THREAD

**Issue by FichteFoll** [z411/trackma#386]
My use case is that I want to fetch all unwatched episodes from the library, i.e. what trackma has found in my media directories, and add those to a playlist. A syncplay playlist, in particular.

I'd be willing to work on this myself, but I don't know where I would add this kind of functionality. The newly added non-interactive CLI sounds useful for this, but should I add it to the others as well?

**Comment by z411** [comment]
Trackma is actually a library so you can do whatever you want with it in your scripts. Of course it's my fault for not documenting this but this design can prove useful. In your case this script would do what you want:

**Make sure to pull from the latest master!**

```
import trackma.engine

# Start Trackma with the account num. 6
engine = trackma.engine.Engine(accountnum=6)
engine.start()

# Re-scan the library just in case something has changed
engine.scan_library()

# Get the library. it's a dictionary in this form:
# {showid: {ep: filename}}
library = engine.library()

for showid, eps in library.items():
    # We need to know what's the latest episode we watched
    # so we query the engine for the details of the entry
    show = engine.get_show_info(showid)
    last_episode_watched = show['my_progress']

    # Now we get which episodes are available in he library
    # and we print out the ones that we haven't watched yet
    for ep, filename in eps.items():
        if ep > last_episode_watched:
            print(filename)
```

**Comment by FichteFoll** [comment]
Awesome, thanks for clarifying and this example. I'll make sure to post my results here once I manage to get trackma to start again and find some time to work on it.

**Comment by FichteFoll** [comment]
Unexpectedly, this wasn't as hard as I feared it to be, so you can check out the result here: https://github.com/FichteFoll/dotfiles/blob/master/tools/tools/trackma2syncplay.py

syncplay's codebase isn't as clean as yours by far, so I had to resort to some hacks to make it behave. Also because it's using twisted. I still need to prevent the player from opening and close it when I'm done, but otherwise this works pretty nicely.
