### ISSUE TITLE
trackma.ui.qt.models: KeyError on show with unknown total eps

### ISSUE THREAD

**Issue by InitialFail** [z411/trackma#389]
On my AniList Plan To Watch list, a show without a known total number of episodes (in my case, Boku no Hero Academia 4) causes the Qt GUI to crash:

```
Traceback (most recent call last):
  File "/path/to/trackma/trackma/ui/qt/models.py", line 189, in data
    return (show['my_progress'], total, self.eps[row][0], self.eps[row][1])
KeyError: 146
```

I'm using 21914812ec51560bb62a8b621ffee017440d7e3a

**Comment by z411** [comment]
Thank you; the Qt interface just underwent heavy changes so I was expecting for several bugs to pop up, very appreciated. See if the latest commit fixes it.

**Comment by InitialFail** [comment]
All good now. Thanks.
