### ISSUE TITLE
Trackma-qt not opening

### ISSUE THREAD

**Issue by ColorOfSilence** [z411/trackma#394]
When I try opening Trackma-qt (or any variation of trackma for that matter I get this error:

`Trackma-qt v0.8.1
Engine: Trackma v0.8.1 - using account colorofsilence(anilist).
Engine: Reading config files...
Data: Initializing...
libanilist: Initializing...
Data: Using libanilist (anime)
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/trackma/ui/qt/workers.py", line 184, in run
    ret = self.function(*self.args, **self.kwargs)
  File "/usr/lib/python3.7/site-packages/trackma/ui/qt/workers.py", line 160, in _start
    self.engine.start()
  File "/usr/lib/python3.7/site-packages/trackma/engine.py", line 237, in start
    (self.api_info, self.mediainfo) = self.data_handler.start()
  File "/usr/lib/python3.7/site-packages/trackma/data.py", line 144, in start
    self._load_queue()
  File "/usr/lib/python3.7/site-packages/trackma/data.py", line 526, in _load_queue
    self.queue = utils.load_data(self.queue_file)
  File "/usr/lib/python3.7/site-packages/trackma/utils.py", line 105, in load_data
    return pickle.load(datafile, encoding='bytes')
EOFError: Ran out of input

[1]    13611 abort (core dumped)  trackma-qt`

It was working fine before, I think it was updated recently and then this error started occuring

**Comment by z411** [comment]
Hi, thanks for the report.  Could you run trackma with the `-d` command line option and post its output?

`trackma -d`

It seems one of the cache files got corrupted.

**Comment by z411** [comment]
Hi, thanks for the report. It seems your queue file got corrupted. Could you try finding the file `~/.local/share/trackma/colorofsilence.anilist/anime.queue` or `~/.trackma/colorofsilence.anilist/anime.queue` and deleting it? It seems it got corrupted. If you try opening it might be empty or truncated.

**Comment by ColorOfSilence** [comment]
@z411 thanks for the quick feedback, that seems to have been the case, the file was empty so I deleted it and tried again and everything seems to be working fine.

Thank you for your support, and for a wonderful program

**Comment by z411** [comment]
No problem. I'll make it so whenever this happens it spouts a warning and recreates the file instead of crashing.
