### ISSUE TITLE
Doesn't recognize episode sometimes?

### ISSUE THREAD

**Issue by FichteFoll** [z411/trackma#401]
So yeah, for some reason, trackma didn't recognize the first episode of Carole & Tuesday and instead wanted to update "Chou Kaudou Girl"? When I reopened the episode (through syncplay, but doesn't matter since it's still using a regular mpv instance), it suddently worked. I don't have another mpv instance open currently.

This may just be a hiccup or something, but I wanted to report it regardless.

![2019-04-27_21-15-29](https://user-images.githubusercontent.com/931051/56854102-b4d9d700-6931-11e9-9014-e15336c9222f.png)

**Comment by z411** [comment]
This might have to do with the fuzzy search being too lenient. Currently it accepts a show in your list as the one you're watching if the title is at least 70% similar to the title in the filename you have open. I was thinking of either making this value configurable or applying some checks or normalizations to the guesser.

You can change the value in the `utils.py` file, line 231, if you want to try for yourself what works best:

```
if highest_ratio[1] > 0.7:
```

**Comment by z411** [comment]
That's weird; the guesser works by choosing the most similar title and Carole & Tuesday was clearly the most similar in your list. Has this happened before with other shows? If it's random it's hard for me to reproduce... I'll look into it nonetheless.

**Comment by FichteFoll** [comment]
I do believe this has happened before, but I can't remember a particular instance. I'll try to pay more attention, though considering how random its nature appears to be I'm not exactly hopeful in finding a useful clue.

**Comment by FichteFoll** [comment]
I'll close this until I can find another (more reliable) case. Seems too much like a fluke to investigate, imo.

**Comment by z411** [comment]
It could be because of that other issue (#411) regarding statuses since it'll just fallback to the most "similar" (not really) show in the library. Let's hope that fixes it.

**Comment by FichteFoll** [comment]
Still an interesting case, because I dropped [that show](https://anilist.co/anime/104284/Chou-Kadou-Girl-16/) long ago.
