### ISSUE TITLE
Does not start tracking on launch

### ISSUE THREAD

**Issue by FichteFoll** [z411/trackma#410]
When trackma is started with an episode already playing (in your configured player) or just open and paused, the tracker does not recognize it. This is suboptimal in case you realize later that trackma wasn't running when you started watching, for example.

**Comment by FichteFoll** [comment]
Oh, note that this occurs with both pynotify and mpris (which I switched to for now).

**Comment by z411** [comment]
This is a known issue with inotify, although MPRIS should do this properly. What media player are you using?

**Comment by FichteFoll** [comment]
mpv with [mpv-mpris](https://github.com/hoyon/mpv-mpris).

**Comment by z411** [comment]
Implemented in ba6c1a5dec3fa589c0c9819e3c8b9bd5b846b8dd for inotify, it should work.

**Comment by FichteFoll** [comment]
Confirmed working with inotify.
