### ISSUE TITLE
Library recognition problem with rewatching status

### ISSUE THREAD

**Issue by FichteFoll** [z411/trackma#411]
I'm having trouble with getting Girls und Panzer recognized. It's in my rewatching list, but checking the relevant code paths, trackma doesn't seem to care about the entry's status anyway.

The correct name is clearly in the database (Romaji, which is used for aliases) so maybe it's the number not being separate from the show title? The tracker regonizes it.

```
>> rescan
…
[D] Engine: Not a show, skipping: /data/Video/Anime/[-__-'] Girls und Panzer [BD 1080p]/[-__-'] Girls und Panzer 01 [BD 1080p DTS-HD 2.1] [BE76583F].mkv
…

>> info 1
Girls und Panzer
----------------
https://anilist.co/anime/14131

English: None
Romaji: Girls und Panzer
Japanese: ガールズ&パンツァー
Synonyms: ['Garupan']
Genres: ['Action', 'Sports']
Studios: ['Actas']
Synopsis: You may have heard of kung fu, but the girls at Oarai High School practice gun-fu—really, really BIG 75mm gun-fu, in fact. It's called Sensha-do, and it's the martial art of operating armored tanks! They take it seriously too, and since winning the national Sensha-do championship is such a huge deal at Oarai, they sometimes go to extreme ends in order to get the best students from Panzer class to sign up. Which is how Miho Nishizumi, who HATES operating tanks, gets drafted to join doomsday-driven driver Mako, even-triggered gunner Hana, highly receptive radio operator Saori and combustible tank-fangirl and loader Yukari as the incomparable Anko Team. They may not be on the half-track to fame and fortune, and maybe a few of them would rather shop for tank tops than become tops in tanks, but once their focus is locked and loaded, they're absolutely driven.<br><br>
(Source: Sentai Filmworks)
Type: TV
Average score: 74
Status: 2

>> tracker
- Tracker status -
State: Playing
Filename: [-__-'] Girls und Panzer 07 [BD 1080p DTS-HD 2.1] [143F056C].mkv
Timer: N/A [P]
Show: Girls und Panzer
Episode: 7
```

**Comment by z411** [comment]
Can't reproduce.

```- Tracker status -
State: Playing
Filename: [-__-'] Girls und Panzer 07 [BD 1080p DTS-HD 2.1] [143F056C].mkv
Timer: 110
Show: Girls und Panzer
Episode: 7```

Could you post your config.json?

**Comment by z411** [comment]
The library scan only scans for the "starting status" (`Watching`) by default. To force it to scan the entire list try enabling `scan_whole_list` in config.json.

I could try fixing this by either
1. Set both `Watching` and `Rewatching` as start statuses, would also fix #385 
2. Make the library scan everything but `Finished`
3. Make the library scan the entire list by default (enable `scan_whole_list` by default) but this slows the scan down.

I think I'll go with a combination of either 1+2 or 1+3.

**Comment by FichteFoll** [comment]
Yeah, seems like rewatching did indeed mess things up. I'm now at the OVA (which I haven't watched before) and everything is being recognized as the specials.

```
[D] Engine: Adding to library: /data/Video/Anime/[-__-'] Girls und Panzer [BD 1080p]/[-__-'] Girls und Panzer 09 [BD 1080p DTS-HD 2.1] [782B1958].mkv
[D] Engine: Redirected to Girls und Panzer Specials 9
…
[D] Engine: Adding to library: /data/Video/Anime/[-__-'] Girls und Panzer [BD 1080p]/[-__-'] Girls und Panzer OVA 1 [BD 1080p FLAC] [7D7CF1A0].mkv
[D] Engine: Redirected to Girls und Panzer Specials 1
…
[D] Engine: Adding to library: /data/Video/Anime/[-__-'] Girls und Panzer [BD 1080p]/Extras/[-__-'] Girls und Panzer - Sensha Kouza 1 [BD 1080p FLAC] [8376F9BB].mkv
[D] Engine: Redirected to Girls und Panzer Specials 1
…
[D] Engine: Adding to library: /data/Video/Anime/[-__-'] Girls und Panzer [BD 1080p]/Extras/[-__-'] Girls und Panzer NCED 02 [BD 1080p FLAC] [92F5EEA3].mkv
[D] Engine: Redirected to Girls und Panzer Specials 2
```

Maybe scanning for paused could be argued about, but I doubt dropped or completed need to be scanned. You may want to rewatch certain episodes, in which case it could be useful, but I wonder how frequently this occurs and how much it would slow down scanning.

**Comment by z411** [comment]
Implemented support for multiple scannable statuses. This means that several statuses get scanned now; I set it to the following for Anilist:

https://github.com/z411/trackma/blob/7b0a949a1027e7196e5540078049cc7801378b50/trackma/lib/libanilist.py#L53

It should fix your issues. Please check if it works.

**Comment by Soitora** [comment]
Didn't work the other day but it works now, cheers!

![image](https://user-images.githubusercontent.com/10836780/57122620-7d7a8880-6d7e-11e9-8f7c-062fac3d44e6.png)

![image](https://user-images.githubusercontent.com/10836780/57122608-7784a780-6d7e-11e9-8c19-71f8c9b650ac.png)

**Comment by FichteFoll** [comment]
Ah, I forgot I opened this issue as well. I verified yesterday that this is working properly.
