### ISSUE TITLE
Qt doesn't remember column width after syncing or rescanning library

### ISSUE THREAD

**Issue by mikael2123** [z411/trackma#421]
All on windows. 

I open trackma-qt and modify the default column widths and the order. I exit through Show > Quit. I open trackma-qt again and the columns are as I modified them; no problems. 

I modify the columns' width or change which column to sort by, then sync or rescan library. It returns to the sort and column width it had when it opened. In order to change the column width or sort so it is remembered after syncing or rescanning I have to modify the column width/sort, quit the program, then restart it and now when I rescan or sync it doesn't change.

In the List menu Sync, Rescan Library and Redownload list all reset the columns and sort while Send Changes doesn't do anything to the columns or sort regardless if there is anything I am sending or not.

**Comment by z411** [comment]
Sorry for the delay. Please see if 9bdd2ce16b643b18c079072a1915555727d3c243 fixes it.

**Comment by mikael2123** [comment]
Yes, this fixed it. Thank you.
