### ISSUE TITLE
Qt interface freezes when trying to update the score unless using the inline editor.

### ISSUE THREAD

**Issue by ardydo** [z411/trackma#422]
I'm using trackma 0.8.1, QT interface and Anilist with 0-100 scoring system.

When trying to update a show score from the sidebar, that is, not from the inline score and changing it and hitting the "set" button, trackma just freezes. I've tried setting a show score to 1, 5, 10, 50 and other numbers and in every case the program just hangs.

When running it from the terminal the following error occurs:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/trackma/ui/qt/workers.py", line 184, in run
    ret = self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/trackma/engine.py", line 567, in set_score
    if (Decimal(str(newscore)) % Decimal(str(self.mediainfo['score_step']))) != 0:
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```
I'm not sure if it is related to my installations issues (as seen on #418 ) but I don't think so and so I'm submitting a report

**Comment by z411** [comment]
Thanks for reporting. If I remember correctly this bug was fixed a bit ago but it hasn't been pushed to pip yet. I just pushed the latest version (0.8.2) to pip so please do a `sudo -H pip3 install --upgrade trackma`. You should now get the version 0.8.2 that includes the fix.

If the issue persists please state so here.

**Comment by ardydo** [comment]
Yup! Version 0.8.2 fixed it! I tried updating it before posting but just like you said the update wasn't pushed there yet.

Thanks again for the swift response :)
