### ISSUE TITLE
pyinotify title seen as 'show name/show name xx'

### ISSUE THREAD

**Issue by Akin2Silver** [z411/trackma#438]
so I have noticed recently an issue with pyinotify detecting the show name as 'show name/show name xx' where xx is the episode count. 
so it will not update the existing show but attempt to add a new one with that name. 

**logs**

```
@ ~]$ trackma-qt
Trackma-qt v0.8.2
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
qt5ct: D-Bus system tray: no
Engine: Trackma v0.8.2 - using account akin2silver(anilist).
Engine: Reading config files...
Data: Initializing...
libanilist: Initializing...
Data: Using libanilist (anime)
Engine: Parsing redirection file (anime-relations.txt)...
Engine: Scanning local library...
Tracker (pyinotify): Initializing...
Tracker (pyinotify): Using pyinotify.
Ready.
Engine: Getting Fairy Gone 8 from library...
Engine: Found. Starting player...
Tracker (pyinotify): Will add Fairy Gone/ Fairy Gone 8
libanilist: Downloading list...
Ready.
Engine: Getting Fairy Gone 8 from library...
Engine: Found. Starting player...
Tracker (pyinotify): Will add Fairy Gone/ Fairy Gone 8
```

I have tested with just launching the player directly and using the 'play next episode' option, both have the same behavior. 
I'm running Manjaro latest `4.19.45-1-MANJARO` and my AUR version of trackma is up to date.
player is VLC

**Comment by z411** [comment]
Hi, is the "Take subdirectory name into account" option enabled? If so, could you try disabling it?

**Comment by Akin2Silver** [comment]
> Hi, is the "Take subdirectory name into account" option enabled? If so, could you try disabling it?

It was indeed, disabling it did resolve the issue! thank you, i am guessing that wont cause any issues with scanning my library?

**Comment by ahmubashshir** [comment]
@Akin2Silver I think you can close this.

**Comment by Akin2Silver** [comment]
Sounds good
