### ISSUE TITLE
Support for external anime-relations.txt

### ISSUE THREAD

**Issue by BanchouBoo** [z411/trackma#441]
It seems like in the original issue about anime relations (#398), the anime-relations.txt was loaded through the .config folder, but now it seems it's built. I'm unsure if the ability to load from .config was removed or if it's just not working for some reason, or if there is an issue with the specific show I'm testing with (Attack on Titan Season 3 Part 2), but in the case it was removed I think being able to load the file externally instead of having to reinstall with a new anime-relations.txt would be very nice.

**Comment by z411** [comment]
Hi, thanks for your inquiry.

No, it wasn't removed. In fact it searches first for the `anime-relations.txt` file in your configuration directory, and *then* it looks for the built-in one.

https://github.com/z411/trackma/blob/f92dd179be9562dae2f53428dd6f6aa434cff711/trackma/engine.py#L244-L248

So if you have your custom file, put it in the configuration directory and Trackma should load that one instead. If it's still not working, could you provide details of what's happening?

**Comment by theboyboy** [comment]
I downloaded the latest anime-relations.txt from [here](https://github.com/erengy/anime-relations) since the built in one doesn't have relations for Attack on Titan Season 3 Part 2, but it still isn't properly detecting the episodes. The specific lines in the file are:
```
# Shingeki no Kyojin -> ~ Season 3 Part 2
- 16498|7442|16498:50-59 -> 38524|41982|104578:1-10!
# Shingeki no Kyojin Season 3 -> ~ Part 2
- 35760|13569|99147:13-22 -> 38524|41982|104578:1-10
- 35760|13569|99147:50-59 -> 38524|41982|104578:1-10
```

When I used Taiga it could properly detect the episodes, so I assumed it just wasn't seeing the file. The path to my file is `~/.config/trackma/anime-relations.txt`, so it's definitely in the right spot and there are no errors or anything when I run Trackma.

**Comment by theboyboy** [comment]
Update: After downloading the new episode it seems to recognize that it's playing in mpv, but it still doesn't seem to recognize the episodes in the filesystem.

**Comment by z411** [comment]
Just to be sure, did you attempt a full library rescan rather than the quick one? (Trackma-qt)

**Comment by theboyboy** [comment]
Yes

**Comment by FichteFoll** [comment]
Would it be feasible to download and update `anime-relations.txt` automatically & periodically, unless the user has an override for it? E.g. to `~/.local/share/trackma/anime-relations.txt`.

**Comment by AlphaCentauri** [comment]
Apologies in advance for bumping an old issue but I just randomly remembered this issue was still open. Did this commit adc56c3 fix your issue by any chance @BanchouBoo?

**Comment by BanchouBoo** [comment]
Whoops, thought I closed this issue. It's been working fine for a little bit now.

**Comment by FichteFoll** [comment]
I posted a new ticket with my earlier suggestion at #507.
