### ISSUE TITLE
Error when Synchronizing

### ISSUE THREAD

**Issue by SolarAquarion** [z411/trackma#449]
`Error: Invalid HTTP request: b'{"errors":[{"message":"Invalid token","status":400,"locations":[{"line":2,"column":3}]}],"data":{"MediaListCollection":null}}'`

**Comment by FichteFoll** [comment]
Your login token expired. You'll have to set a new one.

**Comment by z411** [comment]
The API v2 doesn't let us refresh tokens so I think you have to get the new token manually, yes. Although maybe a less scary error should be displayed in place.

**Comment by SolarAquarion** [comment]
a less scary error message should be a lot better
