### ISSUE TITLE
[Qt] Disable the details dialog or allow changing show progress from the details widget

### ISSUE THREAD

**Issue by amhndu** [z411/trackma#461]
Clicking a show on the list opens the details dialog instantly and almost all of the time when I select a show in the list, I want to be able to change progress/status and thus have to close the dialog.
I find this particularly annoying and I know this can be subjective but I think it'd be more ergonomic to either have the details dialog require some other action ie. double click, or an explicit button. 
Another alternative solution could be to allow making changes to the entry from within the dialog itself.
If the maintainers think this is a good idea, I'm open to make the PR myself.

**Comment by z411** [comment]
A single click is opening it? I'm pretty sure a double click, not a single click should open it.

**Comment by amhndu** [comment]
Yes. I'm on Plasma and if I set the "Single click to open files and folders", a single click triggers the activated signal.
See: <https://doc.qt.io/qt-5/qabstractitemview.html#activated>
It's platform-dependent.

**Comment by z411** [comment]
Ah as I feared, a change to the proper doubleClicked signal should fix things.
