### ISSUE TITLE
Getting 404 on MAL account

### ISSUE THREAD

**Issue by Jzarecta** [z411/trackma#465]
When I try to log into MAL I get an Error 404 and can't access the site. I confirm the sign in credentials and they are fine. Hope this can be fixed.

**Comment by BanchouBoo** [comment]
This is a known issue (#340), and happens because MAL took it's API down. It's not something that can be fixed until the API is restored. ~~AniList is better anyway~~

**Comment by lastweakness** [comment]
> When I try to log into MAL I get an Error 404 and can't access the site. I confirm the sign in credentials and they are fine. Hope this can be fixed.

Please close this isssue
