### ISSUE TITLE
Cannot enter path of player executable (trackma-gtk)

### ISSUE THREAD

**Issue by WhiteSp1rit** [z411/trackma#470]
![2020-01-05_16-43](https://user-images.githubusercontent.com/7308007/71781749-c1432300-2fda-11ea-925e-53ca6993325d.png)
On the screenshot above you can see an example of barely functional dialogue window - unless I missed it, it doesn't feature editable path to the file. There is also no search/filter capabilities in it.

This forces the user to scroll through thousands of files manually in order to select the correct executable, instead of just entering/pasting the path to it.

**Comment by FichteFoll** [comment]
Type a `/`, `~` or `.` to make the input appear. I agree the UI is questionable, but that's just gtk3.

**Comment by WhiteSp1rit** [comment]
> Type a `/`, `~` or `.` to make the input appear. I agree the UI is questionable (especially for discovery), but that's just gtk3.
> Ctrl+v also works.

Interesting, but extremely weird to hide a basic UI functionality behind a keyboard shortcut.
Breadcrumb menus which switch to editable on click were a thing for a long time, why take a concept that is proven by time and make it worse?

**Comment by FichteFoll** [comment]
You're asking the wrong people. As I mentioned, the open dialog is provided by gtk3.

**Comment by lastweakness** [comment]
> > Type a `/`, `~` or `.` to make the input appear. I agree the UI is questionable (especially for discovery), but that's just gtk3.
> > Ctrl+v also works.
> 
> Interesting, but extremely weird to hide a basic UI functionality behind a keyboard shortcut.
> Breadcrumb menus which switch to editable on click were a thing for a long time, even in WIndows - why take a concept that is proven by time and make it much worse?

Ctrl+L is the "obvious" way in GNOME. It's also the same in Nautilus, the file manager in GNOME. It's just the GNOME folks trying to reinvent the wheel as they always have. Sometimes, the reinvented wheel is really pretty and works well (so many of the GNOME apps are examples for this), but most times, it just breaks the traditional workflow. But once you get used to it, it's pretty good.

**Comment by ahmubashshir** [comment]
@z411 @WhiteSp1rit  Shouldn't this be closed (as it's not trackma's fault)?
