### ISSUE TITLE
Doesn't recognize show after it has been added

### ISSUE THREAD

**Issue by FichteFoll** [z411/trackma#471]
This has been kinda bothering me, but when you change your list by adding a show or by moving it from dropped while the show has already been opened, tracker detection isn't redone and the newly added show isn't matched. I need to restart trackma to make it pick up that show.

**Comment by FichteFoll** [comment]
Ah, I should probably mention that I'm using the mpris tracker, but iirc this also applies to pynotify.

**Comment by z411** [comment]
Thanks for the report. This is weird, this should work since _update_tracker() is being called inside add_show().

https://github.com/z411/trackma/blob/0a5170cc8a96c6a462c0d1a4a8e0f55ed8d2f870/trackma/engine.py#L474-L475

I'll look into it.

**Comment by FichteFoll** [comment]
The referenced commit only handles this problem for the mpris tracker. I haven't checked the others yet, so this may need a proper solution in the underlying `Tracker` parent class, but that wouldn't match the scope of that PR.

The problem here in general is that while the list that the tracker maintains is updated, the previous check for whether the playing file can be recognized as an episode is not repeated. Since the Tracker architecture is push-based (from the subclasses' PoV), I suppose they would need to override this method to respond to such a change like I did for mpris.

Additionally, a similar problem exists for when a show is removed from the list and the tracker doesn't check if the removed show happens to be the one it is currently tracking. This is reported separately in #684.
