### ISSUE TITLE
Tracker not starting

### ISSUE THREAD

**Issue by BanchouBoo** [z411/trackma#472]
When I open trackma the tracker doesn't start properly and I get the error below. I have Trackma installed via the AUR and have tried reinstalling both it and `python-pyinotify`. The tracker does work however if I already have an anime open in mpv before opening Trackma.
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/trackma/tracker/pyinotify.py", line 29, in observe
    opened = self._proc_poll()
  File "/usr/lib/python3.8/site-packages/trackma/tracker/inotifyBase.py", line 45, in _proc_poll
    with open('/proc/%s/cmdline' % p, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/proc/8026/cmdline'
```

**Comment by z411** [comment]
Hi, sorry for the late response and thanks for the report. Could you tell me if running Trackma as root suppresses the issue?

**Comment by BanchouBoo** [comment]
The issue also happens as root. The issue however seems to be happening less consistently. When I posted the issue, it was happening every time I started Trackma, now it is only happening every so often (about 2 out of every 5 times I start Trackma).

**Comment by z411** [comment]
This should've been fixed by https://github.com/z411/trackma/commit/18c1f568b0eb9d5acced01ecf18152ea18de7256#diff-f1ddafb5ae52c57cc6d66d03df17ce74eb187002c60ce0937348de6569bbe349
