### ISSUE TITLE
Close button on about menu won't work in GTK

### ISSUE THREAD

**Issue by nattadasu** [z411/trackma#477]
Just open About on option or in context menu while Trackma minimized to system tray, then try to tap/click `close`, the UI isn't closed as it should be.

System information:
Version: Trackma-GTK 0.8.2
DE: XFCE 4.14
WM: XFWM4

**Comment by ahmubashshir** [comment]
This issue is fixed in #481

**Comment by nattadasu** [comment]
Alright, I'll close the issue. Thanks for solving the issue, @ahmubashshir!
