### ISSUE TITLE
Change regex to identify movies/OVA (no episode number)

### ISSUE THREAD

**Issue by SleepyMan** [z411/trackma#49]
The current regex always tries to find an episode number, and if it doesn't it simply stops and logs as " The file format couldn't be recognized".
This conflicts with any movies, whether they are Anime or not, and any single OVA, since they do not have any episode.

E.g. "[Femme] Inari, Konkon, Koi Iroha - OVA [BD 720p Hi444PP AAC][AACB4CD1].mkv"

The regex could be changed to make the episode optional. In case it doesn't find it, assume episode 01, this way, MAL will accept once you update it. This should at least make the regex recognize more files.
While this certainly will make wMAL recognize files like "Batman Origins.mp4", at least it starts recognizing the right ones as well.
As a plus, if in a later update, wMAL integrates with other sites like a fictional "My iMDb List", then it will also be possible to use the same regex.

Since the regex is only going to be run once, I don't think there'll be any performance penalty. What are your thoughts?

Edit: Just checked and the IMDb List seems to be usable like MAL for Live-Action movies (not anime-related). Does it have a public API for changing it?

Edit2: IMDb List doesn't seem to have any public API for changing it... so I guess there's none yet...

**Comment by z411** [comment]
This was implemented by the AnimeInfoExtractor.
