### ISSUE TITLE
anime-relations submodule is very out of date

### ISSUE THREAD

**Issue by AlphaCentauri** [z411/trackma#499]
As of writing this issue the current master for trackma links to https://github.com/erengy/anime-relations/commit/5fe5efbd5a21e1512bfe2d45cb9239d04dc9f56f for the anime-relations submodule which was authored back in April 22nd, 2019. The current anime-relations master, https://github.com/erengy/anime-relations/commit/4a5549a43d14ffb268694c6821667fb47578e146, is 20 commits ahead, with the last commit being authored July 10th, 2020.

I don't have a lot of experience with python, but I'm going to try to submit a PR for this as I'm hoping it'll be as easy as updating the submodule to the current master.

**Comment by AlphaCentauri** [comment]
So as an update, using `[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - 26 [1080p].mkv` as my test file, it doesn't look like trackma is flagging this episode properly. The updated entry is reflected in `self.redirections` (the parsed pattern for Re:Zero Ep. 26+ -> Re:Zero S2: `21355: [((26, -1), 108632, (1, -1))]`), so the file is still being pulled correctly from within `redirections.py` but for whatever reason that entry isn't being triggered. Gonna do some more digging to see what's wrong.

**Comment by AlphaCentauri** [comment]
I believe I figured out the issue I was having. See Issue https://github.com/z411/trackma/issues/500 and PR https://github.com/z411/trackma/pull/501

Also I have opened a PR for this https://github.com/z411/trackma/pull/502

**Comment by FichteFoll** [comment]
Related: https://github.com/z411/trackma/issues/441#issuecomment-649864744

**Comment by AlphaCentauri** [comment]
Closed by 0fc977e for now until the next update to anime-relations master
