### ISSUE TITLE
trackma-qt doesn't want to recognise python-qt5 (PyQt5) = 5.15.0

### ISSUE THREAD

**Issue by v-fox** [z411/trackma#503]
Long time ago trackma-qt broke on openSUSE because it wanted python-qt5 >= 5.14.0, that is absent from official repo, or something. So I've made updated packages of
https://build.opensuse.org/package/show/home:X0F:branches:multimedia/python-sip
https://build.opensuse.org/package/show/home:X0F:branches:multimedia/python-qt5
https://build.opensuse.org/package/show/home:X0F:branches:multimedia/trackma

But now it only spits out:
```
Trackma-qt v0.8.2
Couldn't import Qt5 dependencies. Make sure you installed the PyQt5 package.
Couldn't import Qt4 dependencies. Make sure you installed the PyQt4 package.
```

Running `python3 -v $(which trackma-qt)` gave big dump with:
```
…
import 'subprocess' # <_frozen_importlib_external.SourceFileLoader object at 0x7fd01fc95b50>
# extension module '_uuid' loaded from '/usr/lib64/python3.8/lib-dynload/_uuid.cpython-38-x86_64-linux-gnu.so'
# extension module '_uuid' executed from '/usr/lib64/python3.8/lib-dynload/_uuid.cpython-38-x86_64-linux-gnu.so'
import '_uuid' # <_frozen_importlib_external.ExtensionFileLoader object at 0x7fd01fca8040>
import 'uuid' # <_frozen_importlib_external.SourceFileLoader object at 0x7fd01fce0640>
import 'trackma.utils' # <_frozen_importlib_external.SourceFileLoader object at 0x7fd01fcd6820>
Trackma-qt v0.8.2
# code object from /usr/lib64/python3.8/site-packages/PyQt5/__init__.py
# could not create '/usr/lib64/python3.8/site-packages/PyQt5/__pycache__': PermissionError(13, 'Permission denied')
import 'PyQt5' # <_frozen_importlib_external.SourceFileLoader object at 0x7fd01fcd6310>
Couldn't import Qt5 dependencies. Make sure you installed the PyQt5 package.
Couldn't import Qt4 dependencies. Make sure you installed the PyQt4 package.
…
```

**Comment by FichteFoll** [comment]
Try running with `PYTHONDONTWRITEBYTECODE=1`. 

It seems that whatever package you installed on your distro didn't compile the source code to bytecode and then that can't be written when run outside of root. This is an error with the package and should be reported. For reference, [here's what the Arch build file does](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/pyqt5#n70).

**Comment by v-fox** [comment]
> Try running with `PYTHONDONTWRITEBYTECODE=1`.
> 
> It seems that whatever package you installed on your distro didn't compile the source code to bytecode and then that can't be written when run outside of root. This is an error with the package. For reference, [here's what the Arch build file does](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/pyqt5#n70).

Thanks for the link ! Indeed, it doesn't compile bytecode on its own and I had to put the hack from Arch to force it… but it did not persuade trackma-qt to work. It refuses to recognized it without an error now: [trackma-qt.log](https://github.com/z411/trackma/files/4916121/trackma-qt.log)

**Comment by v-fox** [comment]
Recent changes to python-sip/qt5 packages in openSUSE made it work. Not sure what exactly was wrong but it seems that the issue was in packaging and not trackma.
