### ISSUE TITLE
Update anime-relations.txt independently

### ISSUE THREAD

**Issue by FichteFoll** [z411/trackma#507]
As other issues have shown (#441, #499), the git submodule referring to Taiga's `anime-relations.txt` is updated too infrequently and has to wait for both an update/merge in the code base as well as a new release to be packaged *and* installed in order to receive the latest version.

Since this data file is entirely decoupled from trackma itself, it would be more practical to maintain it separately as well, ideally as an automatic and periodic download that trackma performs itself, e.g. to `~/.local/share/trackma/anime-relations.txt` (`%localappdata%/trackma` on Windows), and which is overridable by the user through `~/.config/trackma/anime-relations.txt`, as is already the case.

**Comment by z411** [comment]
We could definitely get the engine to download the relations file on first sync for APIs that support it. The period could also be configurable, do you have ideas for a good default?

**Comment by FichteFoll** [comment]
Once a day seems reasonable to me. The file isn't updated that frequently, but when it is, you usually want it ASAP for the new additions of new shows. I doubt we would need to worry about straining github's servers, either.

**Comment by z411** [comment]
Implemented in https://github.com/z411/trackma/commit/28a7e5939af98da591f1dd239656b7427d052e1d

`redirections_url` in the config file has the URL to fetch from, `redirections_time` has the sync time in days (defaulting to 1). Now every time the redirections changes you should run a full library update; I'll find a way to do that automatically.
