### ISSUE TITLE
Omaera.org is down preventing user from adding anilist account

### ISSUE THREAD

**Issue by strikersh** [z411/trackma#511]
https://omaera.org/trackma/anilistv2 give me a 404 error
and (when I was still connected) I was getting error messages when trying to search for a series

**Comment by strikersh** [comment]
I just checked and the problem comes from your website,
could you check where the issues is coming?
Would it be possible to write some documentation on self hosting this page?

**Comment by z411** [comment]
Thanks for the report. It should be up now. The page is just a static HTML with a link to `https://anilist.co/api/v2/oauth/authorize?client_id=537&response_type=token`, in fact the GUI clients lead you to this link directly, it's just the terminal based ones that use the omaera link just to make it shorter, but there's no reason why they can't use the direct link instead as well.

**Comment by z411** [comment]
All interfaces now point to Anilist instead of omaera.org so this shouldn't be an issue in the future again.
