### ISSUE TITLE
Can't add new MAL account through GTK frontend

### ISSUE THREAD

**Issue by Phidica** [z411/trackma#520]
Specs: Fedora 32, Python 3.8, Trackma 0.8.3

Running the GTK frontend for Trackma I enter my MAL account username and password, then select the account and click "Open". At this stage the interface gets stuck with `libmal: Initializing...` in the corner. Here is the terminal output:

```
$ trackma-gtk -d
<snip>/python3.8/site-packages/trackma/ui/gtk/window.py:22: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, Gio, Gtk, Gdk
Trackma GTK v0.8.3
[D] Data: Reading userconfig...
Traceback (most recent call last):
  File "<snip>/python3.8/site-packages/trackma/ui/gtk/window.py", line 351, in _on_account_open
    self._create_engine(account)
  File "<snip>/python3.8/site-packages/trackma/ui/gtk/window.py", line 153, in _create_engine
    self._engine = Engine(account, self._message_handler)
  File "<snip>/python3.8/site-packages/trackma/engine.py", line 87, in __init__
    self._init_data_handler()
  File "<snip>/python3.8/site-packages/trackma/engine.py", line 120, in _init_data_handler
    self.data_handler = data.Data(
  File "<snip>/python3.8/site-packages/trackma/data.py", line 86, in __init__
    self.api = libclass(self.msg, account, self.userconfig)
  File "<snip>/python3.8/site-packages/trackma/lib/libmal.py", line 131, in __init__
    raise utils.APIFatal(
trackma.utils.APIFatal: This account seems to be using the old MyAnimeList API.Please re-create and authorize the account.
Engine: Trackma v0.8.3 - using account Phidica(mal).
Engine: Reading config files...
Data: Initializing...
libmal: Initializing...
```

If instead I launch the Qt frontend, I am prompted to request a PIN from MAL and I enter the PIN instead of my password and authenticate my account in this way. After that, the list populates as expected. If I then re-open the GTK frontend, the account loads correctly.

So, I'm guessing the new MAL API requires this PIN authentication rather than a password, and the GTK interface is not set up for this?

**Comment by z411** [comment]
Fix should be up. Thank you.

**Comment by Phidica** [comment]
Awesome, works fine now. Thank you for all your work on Trackma! I'm excited to be able to use it again now that MAL support is back.

**Comment by z411** [comment]
Thank you for the feedback!

**Comment by FichteFoll** [comment]
This issue is fixed. Please create a new one.
