### ISSUE TITLE
(shikimori) no anime list is loaded

### ISSUE THREAD

**Issue by soredake** [z411/trackma#523]
![Screenshot_20201113_154535](https://user-images.githubusercontent.com/5204968/99078593-4ddd4b00-25c7-11eb-95f0-ca10126c1105.png)

**Comment by z411** [comment]
It works for me. Can you upload your `~/.local/share/trackma/(user).shikimori/anime.list` file?

**Comment by soredake** [comment]
[anime.list.zip](https://github.com/z411/trackma/files/5539220/anime.list.zip)

**Comment by z411** [comment]
Fixed. I'm pretty sure it'll crash somewhere when it encounters a cancelled show because I can't find the possible values of `status` in the docs, so I'll keep this open.
