### ISSUE TITLE
When playing from a remote source in MPV pyinotify isn't detecting show

### ISSUE THREAD

**Issue by nate-moo** [z411/trackma#531]
OS: Arch Linux x86_64
Kernel: 5.9.11-arch2-1

Anything else needed can be provided

**Comment by ahmubashshir** [comment]
`pyinotify` only works with local files... switch to mpris tracker.

**Comment by Birdulon** [comment]
MPRIS won't help for stock mpv, you'll have to use the lsof polling tracker or mount your remote share in a way that will generate inotify events. SSHFS mounts have worked for me in the past.

**Comment by nate-moo** [comment]
I was using hls but it doesn't matter anymore. I'll close this since it is basically solved, have a good day.
