### ISSUE TITLE
Is there way to launch trackma automatically system start up?

### ISSUE THREAD

**Issue by toprak** [z411/trackma#535]
I am newbie linux user, I wonder how can I launch trackma automatically when I open my PC. Thank you.

**Comment by ahmubashshir** [comment]
create a desktop file in `$XDG_CONFIG_HOME/autostart/` with
```ini
[Desktop Entry]
Type=Application
Name=Trackma
Exec=trackma-<gtk/qt>
Icon=trackma
```

**Comment by toprak** [comment]
@ahmubashshir thanks!
