### ISSUE TITLE
trackma-qt crashes when start player

### ISSUE THREAD

**Issue by mlunax** [z411/trackma#539]
### Console log:
```
❯ trackma-qt
Trackma-qt v0.8.3
Engine: Trackma v0.8.3 - using account [username](anilist).
Engine: Reading config files...
Engine: The specified media directory  doesn't exist!
Data: Initializing...
libanilist: Initializing...
Data: Using libanilist (anime)
Engine: Parsing redirection file...
Engine: Scanning local library...
Tracker (pyinotify): Initializing...
Ready.
Tracker (pyinotify): Using pyinotify.
Engine: Getting [anime name] from library...
Engine: Found. Starting player...
Tracker (pyinotify): Not playing the next episode of [anime name]. Ignoring.
```

## Steps to reproduce:
1. Turn on trackma-qt
2. Select episode to play.
3. Start the episode.
## Notes:
I am using the MPV player and MKV files.
When using gtk version it works and doesn't crash.
The trackma has to be killed by "-9" (SIGKILL) only.
Sometimes the console output the "segmentation fault" information after the kill.
QT version: 5.15.2

**Comment by ahmubashshir** [comment]
Did you install it with pip? try using from master branch.

**Comment by mlunax** [comment]
I forgot to write I installed it via AUR

**Comment by ahmubashshir** [comment]
try the master branch

**Comment by mlunax** [comment]
It works, I tested in venv.

**Comment by mlunax** [comment]
I have ask about pyinotify. Can I ask here?

**Comment by ahmubashshir** [comment]
Close this and start a new issue :3
as this is fixed :3
