### ISSUE TITLE
HTML Error when attempting to sync with anilist

### ISSUE THREAD

**Issue by Qwerty-Space** [z411/trackma#550]
Tested on trackma-qt and trackma-curses
https://del.dog/morrimasyw.txt
![image](https://user-images.githubusercontent.com/6967592/108445261-fbf63200-7253-11eb-9608-e10cde5883bc.png)

**Comment by Birdulon** [comment]
Anilist had some downtime around 15 hours ago, seems to be up and working for me now.

**Comment by Qwerty-Space** [comment]
It's working for me too.  But trackma is not, even after relogging in

**Comment by Birdulon** [comment]
Hmm, might be cloudflare applying additional security to some IP address ranges going by that response.

**Comment by Qwerty-Space** [comment]
And with that...  It's working again.  Is that sod's law?  Idk

**Comment by Birdulon** [comment]
I suspect it decided you weren't a bad actor after using the website from your browser. Glad it's working for you again now though!

**Comment by Qwerty-Space** [comment]
Hmm interesting
