### ISSUE TITLE
(Anilist) Error when trying to retrieve list & unable to send changes

### ISSUE THREAD

**Issue by BanchouBoo** [z411/trackma#555]
Starting a couple days ago, when I try to retrieve my list, I get the following error:

```sh
APIError: Invalid HTTP request: b'{"errors":[{"message":"Invalid token","status":400,"locations":[{"line":2,"column":3}]}],"data":{"MediaListCollection":null}}'
```

I haven't changed any settings or updated the program or anything (on version 0.8.4)

**Comment by Birdulon** [comment]
Sounds like Anilist has expired your access token, you'll have to generate a new one and replace your current one with it.

**Comment by BanchouBoo** [comment]
that worked, wasn't aware that tokens would expire
