### ISSUE TITLE
API Error:104: chapterCount is not a valid field for anime - libkitsu (Manga)

### ISSUE THREAD

**Issue by plumchii** [z411/trackma#573]
A small error window box appears when switching from Mediatype "anime" to "manga" with the error message "API Error:104: chapterCount is not a valid field for anime". The final line of stdout (when launching in a terminal) displays "libkitsu: Getting page 1...".

Clicking "Ok" in the error window will then close both the main window and error window and return to account selection. The main window is still running and minimized to system tray, which is still hanging on "libkitsu: Getting page 1" if opened back up.

### Steps to reproduce 
- Select Kitsu account
- Switch to manga from anime mediatype
     - If the mediatype manga was already selected before then the main window will try to autoload this and fail once the account          is selected again

### System Details:
- Trackma-qt 2.20210120git.1.fc34 (from Fedora COPR: dyskette/trackma)

### Notes
Deleting the account and re-adding does not fix the issue.
I tried using my username instead of email as I saw #294 but this has come back with a different error/bug it seems.

**Comment by ahmubashshir** [comment]
Fixed in 2b3949c.

**Comment by plumchii** [comment]
Can confirm fixed in master branch.
