### ISSUE TITLE
Readme installation of git version.

### ISSUE THREAD

**Issue by cronyakatsuki** [z411/trackma#575]
Just to make it more known you can also install the git version of trackma using command `pip3 install -U git+https://github.com/z411/trackma.git` if like me you need the development version but don't plan on doing any coding.

You could also add this command so that other people can also see so that they don't have to manually download the git repo and install if they won't be doing any pull requests, while making it easy for them install the development version.

**Comment by z411** [comment]
Done, thank you.

**Comment by ahmubashshir** [comment]
[![Packaging status](https://repology.org/badge/vertical-allrepos/trackma.svg)](https://repology.org/project/trackma/versions)

 this can be added to readme too :3
