### ISSUE TITLE
How to list filtered anime?

### ISSUE THREAD

**Issue by cronyakatsuki** [z411/trackma#576]
I'm trying to list anime that is under the plan to watch status but am not able to. I tryed using command like `trackma ls plantowatch` but after seeing that it doesn't support any more arguments I tried using this `trackma filter plantowatch` and then `trackma ls` but it printed me the anime under the watching status.

So is there any way to list anime under certain category using cli?

**Comment by DavidBonelo** [comment]
first run `trackma`

then `filter plantowatch`

your prompt should change from `[mal] (anime) watching >>` to `[mal] (anime) plantowatch >>`

and then `ls` should show the plan to watch list 👍

from the help command:
command args | description
-|-
`filter <status>` | Changes the filtering of list by status (shows current if empty).

the filter types are: `completed` `dropped` `onhold` `plantowatch` `watching`

or you can type `filter` and double tab to get suggestions.
