### ISSUE TITLE
Website not found. (.com, .io)

### ISSUE THREAD

**Issue by DigitalNXZ** [z411/trackma#582]
In the About it's still "z411.github.com/trackma" is it not .io?

~best regards

**Comment by ahmubashshir** [comment]
it's http://github.com/z411/trackma

**Comment by DigitalNXZ** [comment]
> it's [http://github.com/z411/trackma](https://github.com/z411/trackma)
Sorry but I thin u dont understand.
There is something called "Github pages" 

try z411.github.io/trackma to see  what i mean.

**Comment by mnabid** [comment]
Yeah, the new url is https://z411.github.io/trackma
@z411 probably forgot to update it.

**Comment by Kcchouette** [comment]
Oh, it's on Github GUI, not in trackma source code, lol


![image](https://user-images.githubusercontent.com/3000936/149679606-d07d1259-553c-4950-8d7b-cb02f08ead1f.png)

**Comment by z411** [comment]
Fixed, thank you.
