### ISSUE TITLE
[MAL] Anime shows neither in search, nor in list

### ISSUE THREAD

**Issue by txtsd** [z411/trackma#584]
I'm watching this [Ganbare Douki-chan](https://myanimelist.net/anime/49605/Ganbare_Douki-chan).
It's in my watching list, but it refuses to appear in trackma, and it doesn't show up in the Search/Add from Remote either.

**Comment by clebermatheus** [comment]
Image for reference:
![screenshot 1635986538](https://user-images.githubusercontent.com/2768774/140238404-64a36c2a-2f85-4153-98b8-ce1dae361afa.jpg)

**Comment by txtsd** [comment]
[Getsuyoubi no Tawawa 2](https://myanimelist.net/anime/49854/Getsuyoubi_no_Tawawa_2) doesn't show either.
