### ISSUE TITLE
Specifying project dependencies

### ISSUE THREAD

**Issue by FichteFoll** [z411/trackma#609]
Currently, there is a list of general dependencies in the readme for various aspects of trackma, but those don't map cleanly to Python package names on pypi. It would seem rather useful to me to have these in some form, either in `setup.py` as extras or the readme.

At the same time, what do you know of `pyproject.toml` and using e.g. poetry for managing development environments instead of `setup.py`? I've had a rather good experience with those and they definitely appear to be the way to go forward with, ~~although poetry's dependency groups feature with its recent additions is currently not released in any version~~.

**Comment by txtsd** [comment]
> There are a few instances of `import Image`. I'm not sure what module/package that belongs to, and I'd like clarification as to what it actually imports. Additionally, I would like to push a requirements.txt. Let me know if that's okay.

From my PR #629. I can make a `pyproject.toml` for Poetry, and even a `Pipfile` if you want to look at your options. 

I still need to know what  `import Image` is though.

Here's the `requirements.txt` that I had created earlier.

<details>
<summary>
requirements.txt
</summary>

```
Trackma~=0.8.4
setuptools~=63.1.0
pycairo~=1.21.0
pygobject~=3.42.1
pillow~=9.2.0
pydbus~=0.6.0
pyqt5~=5.15.7
pyqt4~=4.12.3
urwid~=2.1.2
pyinotify~=0.9.6
inotify~=0.2.10
twitter~=1.19.3
requests_oauthlib~=1.3.1
sip~=6.6.2
readline~=6.2.4.1
pypresence~=4.2.1
requests~=2.28.1
```

</details>

**Comment by dyskette** [comment]
Huh... this is definitely needed. It seems I've been neglecting some dependencies because there is simply no automated way to get them.

Also, maybe automating some flatpak packaging would become feasible with this.

+1 for poetry

**Comment by txtsd** [comment]
For the `license` field in `pyproject.toml` I need to know if the code is licensed as `GPL-3.0-or-later` or `GPL-3.0-only`.

**Comment by FichteFoll** [comment]
Imho `pyproject.toml` is the way forward, so either poetry (if developing an application) or flit (if developing a library) sound like the best options, but I haven't dealt with Python packaging in a while. I would start with poetry, though

> I still need to know what `import Image` is though.

I expected it to be from pillow, but [its documentation](https://pillow.readthedocs.io/en/stable/reference/Image.html) seems to imply importing that `from PIL` instead.

> I need to know if the code is licensed as `GPL-3.0-or-later` or `GPL-3.0-only`

Looks GPL-3 to me.

**Comment by FichteFoll** [comment]
> Looks GPL-3-or-later to me.


Doesn't even seem like the GPL is properly applied. As far as I'm concerned, you need [at least this block](https://github.com/z411/trackma/blob/4f7f6195fd9e04b4b9fffc30391b8ba8af5d7f47/COPYING#L634-L648) to appear somewhere in the repository (readme or `LICENSE` file), simply including the GPL verbatim is not enough. And since that part also declares if it's only 3 or 3-or-later, we can't know, though I'd assume 3-or-later is the default.

Regardless, this is something @z411 would need to manage (or at least needs his approval, because it was already implied that trackma was using the GPL.

**Comment by z411** [comment]
What do you mean? That block is included in every source file, except for a few ones that need to be fixed. Code is `GPL-3.0-or-later`.

Regarding requirements, we have to remember that most of these are optional. You don't need PIL to run the CLI or curses interface, nor Qt or GTK. Ideally, these should be separate projects (ie. libtrackma, trackma-cli, trackma-curses, trackma-gtk, trackma-qt) and that was my original idea but it would make things mor complex. Probably. Although for package managers it would be certainly better.

**Comment by FichteFoll** [comment]
Whops, guess I managed to randomly find that one file that didn't ([it's this one](https://github.com/z411/trackma/blob/4f7f6195fd9e04b4b9fffc30391b8ba8af5d7f47/trackma/accounts.py)).

Optional dependencies can be specified as extra( group)s.

**Comment by txtsd** [comment]
@FichteFoll The entire logic for checking whether imaging exists can be dropped, if the whole point was to import from PIL anyway. Once we have dependencies, we can assume it exists.
