### ISSUE TITLE
Unable to get MAL Pin due to trackma.omaera.org being offline.

### ISSUE THREAD

**Issue by EmiliaTheGoddess** [z411/trackma#617]
Everything works in the UI but I can't get a pin to log in due to the website being offline.
![image](https://user-images.githubusercontent.com/43678100/170862433-207493eb-f23f-440b-aae3-f0e3771fb16a.png)

I tried with different networks, mobile data and VPNs but none worked. Is there something wrong with my network or is the website down for a reason?

**Comment by z411** [comment]
The site is indeed down, I'll fix it in a few hours. Thanks for the heads up.

**Comment by z411** [comment]
Sorry for the delay. Issue fixed.
