### ISSUE TITLE
wmal-qt unable to load cache list

### ISSUE THREAD

**Issue by SleepyMan** [z411/trackma#62]
After remaining offline for a few days, I tried to sync wmal, but when i opened it, it got stuck at "Data: Reading cache..."
Running in the terminal, I could see that it threw an exception cPickle.BadPickleGet

File "/usr/lib/python2.7/site-packages/wmal/data.py", line 436, in _load_cache
    self.showlist = cPickle.load( open( self.cache_file , "rb" ) )
cPickle.BadPickleGet: 20�

I tried looking for something that looked like 20 + non-ASCII character, but I couldn't find anything in anime.list (which I believe it is the self.cache_file)
This is the 3rd time this happened after I've been offline for some time, losing maybe 10 or so shows that I don't remember to be able to update manually.
Is it possible to change from cPickle to something more standardized or something that it's easy to see what went wrong? I'm not sure, but maybe JSON?

If you can and you want, I can send my anime.list for debugging (assuming, there is no private info in it).

Edit: I labeled it wmal-qt... but it happens on all, since it's on data.py...

**Comment by z411** [comment]
Has this happened recently?

**Comment by SleepyMan** [comment]
Sorry, haven't used wmal/trackma since Oct due to the lack of season browser. I just installed it again, but since I added show from AniChart (AniList's season browser), it throws an exception regarding "my_progress" being None, thus I can't test if this happens or not.

**Comment by z411** [comment]
Since it seems this hasn't hapened again I'll assume 457983f fixed it.
