### ISSUE TITLE
Custom anime title formatting support on the GTK version, like on the qt one.

### ISSUE THREAD

**Issue by Estebiu** [z411/trackma#625]
Firstly, this tool is truly amazing, but I'd love if you'd could (or anyone capable of doing this) add the possibility to "scan the library using custom formatting", but I'm not sure I'm expressing myself right so I'll try to explain it better.
For example I'm trying to watch season 2 of K-on, and on anilist his name is "K-on! Season 2", and that's fine, but in my local library it's marked as just "K-on!!". So when I'm clicking "watch next" in trackma gui's (bot qt and gtk) it says that it doesn't find the next episode, as, well, the name he's searching for it's obviously different from the one that I have on my library. There are two possible solutions for this:
1) Getting the correct hash then searching anidb for the correct episode info and yada yada yada;
2) Or just simply letting the user select the correct "things" to search.
I could just rename the episodes, but when doing this I'll lose the ability to seed them.

**Comment by FichteFoll** [comment]
In the Qt and the CLI UIs you can set an alternative name that can be used for a show. In your case, you'd select "K-on! Season 2" in your list and set the altname `K-on!!`.

**Comment by Estebiu** [comment]
> In the Qt and the CLI UIs you can set an alternative name that can be used for a show. In your case, you'd select "K-on! Season 2" in your list and set the altname `K-on!!`.
> 
> Although that already is the romaji name, [according to anilist](https://anilist.co/anime/7791/KON-Season-2/) and that should be detected/checked as well.

I verified and it works. Wow! Thanks. But why is the gtk version missing a few things (like also the rewatching feature)?
Also opening the settings on trackma-qt make it crash, on wayland. rip.

**Comment by Estebiu** [comment]
Or even better, use this: https://github.com/erengy/anitomy/tree/master

**Comment by FichteFoll** [comment]
That's already in discussion in #591 and wouldn't help in this case since anitomy is a parser for the file name (and the file name has been parsed correctly here, it just couldn't be matched with the name in the library).

**Comment by Estebiu** [comment]
Closing because now on the gtk client there is an option to set an alternate name, thank you for having implemented this.
