### ISSUE TITLE
MAL can't search H anime and NSFW tag anime

### ISSUE THREAD

**Issue by wadamT** [z411/trackma#626]
I can't search NSFW tag and H anime with MAL account using Trackma. But it is possible using Anilist account. I try searching online and found [MAL api documentation](https://myanimelist.net/apiconfig/references/api/v2#section/Common-parameters) in which states 

> By default, some APIs don’t return nsfw content.You can control this behavior with the nsfw parameter.

Searching Miru Tights with Anilist account
![Anilist 1](https://user-images.githubusercontent.com/70312852/178101465-dc33a344-3a71-4bd4-9c21-f5bbbf6af6e4.png)

Searching Miru Tights with MAL account
![Mal 2](https://user-images.githubusercontent.com/70312852/178101471-dcfa818c-7520-4ca8-b5a8-fa2bbe388db9.png)

**Comment by txtsd** [comment]
Ah shit. This is the reason for #584.

**Comment by txtsd** [comment]
I tried to make a fix by adding `{'nsfw': 'true'}` to the `params` variables in the `search`, `request_info` and `fetch_list` functions in https://github.com/z411/trackma/blob/master/trackma/lib/libmal.py but I still don't see the shows I'm searching for:

- Miru Tights
- Ganbare Douki-chan
- Getsuyoubi no Tawawa 2

(Surprisingly, Getsuyoubi no Tawawa and Getsuyoubi no Tawawa Specials show in the list)

I also tried `{'nsfw': True}`

Is there a way to look at the raw results before they're parsed?
@z411 @FichteFoll

**Comment by txtsd** [comment]
I tried the raw request with `curl` and it does show the missing anime when passing `nsfw=true`.

```sh
curl 'https://api.myanimelist.net/v2/anime?q=tawawa&limit=4&nsfw=True' \                                                                                                    
-H 'X-MAL-CLIENT-ID: 32c510ab2f47a1048a8dd24de266dc0c' \
| jq
```

```json
{
  "data": [
    {
      "node": {
        "id": 34213,
        "title": "Getsuyoubi no Tawawa",
        "main_picture": {
          "medium": "https://api-cdn.myanimelist.net/images/anime/13/83576.jpg",
          "large": "https://api-cdn.myanimelist.net/images/anime/13/83576l.jpg"
        }
      }
    },
    {
      "node": {
        "id": 49854,
        "title": "Getsuyoubi no Tawawa 2",
        "main_picture": {
          "medium": "https://api-cdn.myanimelist.net/images/anime/1370/117813.jpg",
          "large": "https://api-cdn.myanimelist.net/images/anime/1370/117813l.jpg"
        }
      }
    },
    {
      "node": {
        "id": 34481,
        "title": "Getsuyoubi no Tawawa Specials",
        "main_picture": {
          "medium": "https://api-cdn.myanimelist.net/images/anime/13/83698.jpg",
          "large": "https://api-cdn.myanimelist.net/images/anime/13/83698l.jpg"
        }
      }
    },
    {
      "node": {
        "id": 49866,
        "title": "Getsuyoubi no Tawawa 2 Special",
        "main_picture": {
          "medium": "https://api-cdn.myanimelist.net/images/anime/1359/118532.jpg",
          "large": "https://api-cdn.myanimelist.net/images/anime/1359/118532l.jpg"
        }
      }
    }
  ],
  "paging": {
    "next": "https://api.myanimelist.net/v2/anime?offset=4&q=tawawa&limit=4&nsfw=True"
  }
}
```

**Comment by txtsd** [comment]
@wadamT How? I made the same changes and it didn't work for me.

**Comment by wadamT** [comment]
I simply added `'nsfw': True` to params in mentioned lines.

[My code ](https://pastebin.com/cznSsAUG)
