### ISSUE TITLE
App icon breaks under Wayland [Kde]

### ISSUE THREAD

**Issue by alsoGAMER** [z411/trackma#638]
Steps to reproduce:
- Start a plasma wayland session.
- Open trackma(qt).
- Observe.

Reported behaviour:
- The app isn't showing its icon in the taskbar nor in the top-left corner of the application window, the wayland one is shown instead.

Screenshots and app version:
![window](https://user-images.githubusercontent.com/35269770/189527451-1f319d0f-7193-4f85-a236-ff7491b890a0.png)
![taskbar](https://user-images.githubusercontent.com/35269770/189527458-eb2aee5b-4225-4e8f-a0b2-8cc5d61a6ca8.png)

Package trackma-git built on chaotic-aur
Version 0.8.4.r191.g0a2558e-1

**Comment by FichteFoll** [comment]
Does this also occur with the GTK UI?

**Comment by alsoGAMER** [comment]
> Does this also occur with the GTK UI?

Sadly I can't test that, cause it crashes instantly every time that I try to open it.

**Comment by FichteFoll** [comment]
Please open it from the terminal via `trackma-gtk -d` and post the output. That definitely shouldn't happen.

**Comment by alsoGAMER** [comment]
> Please open it from the terminal via `trackma-gtk -d` and post the output. That definitely shouldn't happen.

Doesn't happen anymore, I guess it was caused by some broken system update, that now fixed itself.
The icon works for the GTK variant though.

**Comment by z411** [comment]
Maybe a bug fixed in Qt6? Seems doubtful though. I remember using the standard Qt way to setting the application icon, but I have no way to test under Wayland (thanks NVIDIA)...

**Comment by KodyVB** [comment]
#654 Fixed it for the panel's icons-only task manager for me, but unfortunately I don't know how to fix the icon in the title bar. A couple applications I wrote in PyQt had both broken as well, and the same solution fixed both locations for those applications, but for some reason it's not fixing it in the title bar for Trackma. I'd like to fix the problem fully, but my Google-fu doesn't seem to be advanced enough to do so.

**Comment by txtsd** [comment]
The icon has been working fine for me on Sway on Arch.

**Comment by KodyVB** [comment]
@txtsd I've been experiencing the issues on KDE's Wayland, as with the original issue. Would you be up for testing whether or not changing `app.setDesktopFileName("trackma")` to `app.setDesktopFileName("trackma-qt")` in line 76 of `trackma/ui/qt/__init__.py` breaks the icon for you as a Sway user?

**Comment by txtsd** [comment]
Hold up.
I was looking in the tray, where the icon is correct.
The app icon in the taskbar, however, is neither correct in 0.8.5, nor in your PR with that change you mentioned.

**Comment by alsoGAMER** [comment]
fixed via 7d69f70
