### ISSUE TITLE
Qt variant crashes when re-selecting active mediatype

### ISSUE THREAD

**Issue by alsoGAMER** [z411/trackma#639]
How to reproduce:
- Open trackma-qt
- Click on mediatype (menubar)
- Re-select current active mediatype (if anime, click anime, etc...)

App version:
0.8.4.r191.g0a2558e-1 (from chaotic-aur)

Traceback:
```py 
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/trackma/ui/qt/mainwindow.py", line 1263, in s_mediatype
    mediatype = self.api_info['supported_mediatypes'][index]
TypeError: list indices must be integers or slices, not NoneType
```

**Comment by alsoGAMER** [comment]
Still happen as of 0.8.4.r199.ge132db0-1

**Comment by z411** [comment]
Fixed. Thank you.
