### ISSUE TITLE
Add "View Anime" button and option to use cover image in Discord RPC

### ISSUE THREAD

**Issue by rollingmoai** [z411/trackma#640]
See [MALSync](https://github.com/MALSync/MALSync):
![image](https://user-images.githubusercontent.com/75471378/192958851-22b06462-7b0d-4fb8-86db-62dd59019bf0.png)

**Comment by ahmubashshir** [comment]
I'll try to implement this...

**Comment by FichteFoll** [comment]
There's some info on custom images in RPC here: https://github.com/FichteFoll/discordrp-mpris/issues/19#issuecomment-1091003904

Though I haven't been able to look into it deeper myself.

**Comment by rollingmoai** [comment]
Side question: how do I make trackma not ignore the current episode (for the RPC)?
