### ISSUE TITLE
i want to auto add a not yet watched show, but it just says found player but show not in list 

### ISSUE THREAD

**Issue by autoteelar** [z411/trackma#647]
found player but show not in list 

i want it to auto add when i watch episode 1 of a new show, i found these, 
    ],
    "tracker_enabled": true,
    "tracker_ignore_not_next": true,
    "tracker_interval": 10,
    "tracker_not_found_prompt": false,
    "tracker_process": "mplayer|mplayer2|mpv",
    "tracker_type": "auto",
    "tracker_update_close": false,
    "tracker_update_prompt": false,
    "tracker_update_wait_s": 120,

none of them seem to have anything to do with show not in list though,,, any help?

**Comment by Birdulon** [comment]
Set `tracker_not_found_prompt` to true. Might not work in some UIs, I only ever used it in Qt.

**Comment by autoteelar** [comment]
thanks! yeah i usually use qt or curses,
