### ISSUE TITLE
Jellyfin tracker checking for absolute episode number, not seasonal

### ISSUE THREAD

**Issue by Cwavs** [z411/trackma#668]
I have my jellyfin library ordered by season, but the tracker seems to be looking for the absolute episode number rather than the individual season, causing it to ignore tracking. For example If I'm watching Season 2 Episode 2 of demon misfit academy, however for some reason the tracker is looking for episode 14, which causes it to ignore it.

```Shell
Tracker (Jellyfin) warning: Not playing the next episode of Maou Gakuin no Futekigousha: Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e Kayou (expected: 14, found: 2). Ignoring.
```
![image](https://user-images.githubusercontent.com/16854045/212564902-15d71adf-238e-48d3-8e8d-84e5dfd4d309.png)

**Comment by Cwavs** [comment]
Strange, the issue doesn't seem to be happening with Bungo Stray Dogs season 4, I realised that based on kitsu alone, trackma has no way to tell what individual kitsu entries are actually seasons, and what seasons they are etc. Is trackma using something like thexem to work it out? If so could this be due to bad data over there?

**Comment by FichteFoll** [comment]
trackma is using the [anime-relations](https://github.com/erengy/anime-relations) project for these kinds of mappings. There is an entry for BSD but not for the show you're having problems with.

**Comment by Cwavs** [comment]
Ah, this would explain the issue. It might be worth considering swapping to use thexem, you could use something like this project https://github.com/BeeeQueue/arm-server (or its datasource https://github.com/Fribb/anime-lists) to map between the services and get the anidb id and use that with the xem. Although that would probably need to be discussed under a dedicated issue. I think this specific issue is basically solved now though, so I'll close this thread and open another one for that.
