### ISSUE TITLE
Crashing on QT interface when selecting series

### ISSUE THREAD

**Issue by y0shir** [z411/trackma#704]
On debian testing qt interface is crashing when tying to select manga. It works fine when I try to select series that already has cover downloaded, but when I try to select series that has to dowload it's cover interface crashes. The following is the output to terminal:
```
Trackma-qt v0.8.5
Engine: Trackma v0.8.5 - using account REDACTED(mal).
Engine: Reading config files...
Data: Initializing...
libmal: Initializing...
Data: Using libmal (manga)
Engine: Can't auto-scan library: Operation not supported by current site or mediatype.
Ready.
Traceback (most recent call last):
  File "/home/REDACTED/.local/lib/python3.11/site-packages/trackma/ui/qt/workers.py", line 62, in run
    im.thumbnail((self.size[0], self.size[1]), Image.ANTIALIAS)
                                               ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
Аварийный останов
```

**Comment by toprak** [comment]
Using arch linux same here.

**Comment by molkoback** [comment]
Image.ANTIALIAS was removed in PIL 10.0.0. This has already been fixed in https://github.com/z411/trackma/commit/901599fad2de1e525ef3e32ab49b57734e459067.

**Comment by toprak** [comment]
@molkoback so aur packages are outdated?

**Comment by molkoback** [comment]
trackma-git should work. Atleast it always downloads the current version from this repo. Just make sure you don't have an older version installed with pip in your home/.local/lib.

**Comment by z411** [comment]
I bumped up the version to 0.8.6 and uploaded it to pypi. Upgrading through pip should fix this as well (`pip3 install --upgrade trackma`).

**Comment by z411** [comment]
This was fixed and it's on PyPI.
