### ISSUE TITLE
Cannot open folder

### ISSUE THREAD

**Issue by BigBoyBarney** [z411/trackma#712]
![image](https://github.com/z411/trackma/assets/86712892/8cccb77e-bffc-4774-a3a3-86ac0ab6bc4b)
The openfolder command does not open the folder (either through the UI or cmd) as it lists the episode as not in library, even though it is.

The episode can be listed and played, but the folder cannot be opened.

It seems to stem from [here](https://github.com/z411/trackma/blob/8ea7f79c66864c615a62806756a4d8909770ca4b/trackma/engine.py#L888)

**Comment by BigBoyBarney** [comment]
It currently checks for episode 1 of the show only, and if that is not present, the check fails in `get_episode_path(self, show, episode)`, as episode=1 is passed.

I haven't yet figured out how querying the local library works, but when I do I'll PR a fix

**Comment by z411** [comment]
Thanks, indeed it's not sane to assume episode 1 will always be available. I modified the flow so it gets any episode of the show - since we only need the path. Please pull https://github.com/z411/trackma/commit/994e6e716184f01170a22515b7edad51ff0521bf and tell me if it works. Cheers.

**Comment by BigBoyBarney** [comment]
It works like a charm, thank you!
