### ISSUE TITLE
Does not recognise anime when scanning folder, but recognises when playing

### ISSUE THREAD

**Issue by BigBoyBarney** [z411/trackma#716]
Hi!

I encountered the following problem. Lots of anime are not recognised during library scan (see screenshot)
![image](https://github.com/z411/trackma/assets/86712892/1a3a0dde-974a-4a3d-837d-92d7ea60908c)

BUT they are recognised via MPRIS when I open them with mpv. (see screenshot)
![image](https://github.com/z411/trackma/assets/86712892/1592c880-9d2d-4324-9d43-9dbcc0760411)

I wonder if there is a difference between parsers used in these two scenarios? I checked and there is no metadata pointing to the show other than the filename.

I added a `self.msg.debug("Show title to guess: {}".format(show_title))` to `_add_show_to_library` in `engine`, and it guesses the wrong title, which explain why it cannot match.
![image](https://github.com/z411/trackma/assets/86712892/6d24f8b7-12cf-40cd-8967-a5f37ef2d3fc)

Thanks in advance! <3

**Comment by BigBoyBarney** [comment]
It's mostly [Tenrai-Sensei] releases as their naming scheme is a big mess, especially with episode ranges and season nomenclature.

Adding `base_filename = filename.rsplit('/', 1)[-1]` to https://github.com/z411/trackma/blob/master/trackma/parser/animeinfoextractor.py#L291 fixes this particular issue, but introduces redirection errors due to overflowing episode / season numbers (particularly with Sword Art Online).

I will keep testing different anime and possible additional parsing options, so please keep this issue open to track :)

**Comment by FichteFoll** [comment]
There is an option to include the folder name when trying to resolve anime titles. The mpris tracker doesn't implement that currently, so it will work as if the setting was disabled. I suggest to disable it globally also for the library scanner.

**Comment by BigBoyBarney** [comment]
That does indeed fix the issue. Interesting.
Thank you!
