### ISSUE TITLE
Anilist not Working (Cloudflare protection)

### ISSUE THREAD

**Issue by uzuto** [z411/trackma#718]
Anilist is not working as they added cloudflare protection to their site.
Log file:- 
[trackma-log.txt](https://github.com/z411/trackma/files/12910291/trackma-log.txt)

![Screenshot_2023-10-15-23-19-57_1366x768](https://github.com/z411/trackma/assets/90568133/89e4894a-0057-445e-a189-8e5e1e176a0a)

**Comment by z411** [comment]
It's working for me... maybe you need to visit their website first?

**Comment by uzuto** [comment]
I did but it isn't working, lets wait for other responses for verification.

**Comment by z411** [comment]
What if you try re-adding the account to verify again? I think this happened once to me...

**Comment by uzuto** [comment]
I tried re-adding after deleting entire ~/.config/trackma folder but the result's the same (Gives Error while refreshing user details)
Could this perhaps be a DNS thing? (I have QuadDNS enabled from resolved if that matters)

**Comment by FichteFoll** [comment]
What happens when you open the main page in your browser? Do you see a cloudflare challenge?
Trackma won't be able to do much here. You need to get CF to trust your host/IP.

**Comment by uzuto** [comment]
It works flawlessly in the browser (although I do see challenge for the very fist time after restarting)

**Comment by FichteFoll** [comment]
Is it still a problem in trackma after you have resolved the challenge?

**Comment by uzuto** [comment]
Yes

**Comment by FichteFoll** [comment]
Then I'm afraid you'll have to ask anilist mods (or a/the dev) on how to get yourself from CF's challenge list. As I mentioned, I don't think there is much that trackma can do. My only remaining guess would be to use the same UserAgent as your browser for requests, but I would also not be surprised if CF didn't let that through.

**Comment by uzuto** [comment]
I will try looking into it will let you know if I sort it out.

**Comment by z411** [comment]
Thanks for looking into it. So it was an upstream issue. I don't think putting an API behind Cloudflare checks, they should change this to another technique like rate limiting, but that's up to their team.

**Comment by uzuto** [comment]
Well, the only solution is waiting so it's probably safe to close this issue now.
