### ISSUE TITLE
Support dark/black themes

### ISSUE THREAD

**Issue by artixnous** [z411/trackma#81]
I'm running Mate desktop with a black theme and the regular list title text is unreadable. ATM I've edited /usr/lib/python2.7/site-packages/wmal/ui/gtkui.py and replaced 'black' with '#999999', but an option in Global Settings to manually set text colour would be a more "proper" solution. Thanks.
![wmal_git](https://cloud.githubusercontent.com/assets/6310912/5350020/805f268e-7f47-11e4-8120-86c0ec4635a6.jpg)

**Comment by RaitaroH** [comment]
@z411  
Well. In KDE Neon, the qt version was looking quite... unreadable. The theme colors are too light for the white text. I fixed the issue by using much darker colors, as such:

![screenshot_20180905_164849](https://user-images.githubusercontent.com/19552720/45097447-949fa280-b12b-11e8-87f1-2142cbfe5be3.png)

**Comment by amcsi** [comment]
This is what it looks like for me in Bazzite KDE. Not sure what to do to get the entries to be readable. I tried all 3 themes, but there doesn't appear to be any difference between them.

<img width="1081" height="721" alt="Image" src="https://github.com/user-attachments/assets/95bee2c5-adf7-4312-8684-648ea214306f" />

**Comment by z411** [comment]
This issue is for the GTK frontend. You're using the Qt one. For now you'll have to choose from the system colors manually, but we should probably use those by default.
