### ISSUE TITLE
No Hummingbird manga list support

### ISSUE THREAD

**Issue by FenekAlfa** [z411/trackma#87]
I know that in the past HB was anime-only, but now they support manga, so it would be nice if I wouldn't have to go to the webpage to update my manga list.

**Comment by FenekAlfa** [comment]
Wow, sorry for a very late response.

I can't find anything in the docs either, but I know it works on Tenpenchii so it's possible. Maybe ask the devs about it?

**Comment by kazuoteramoto** [comment]
Possible relevant?

https://forums.hummingbird.me/t/manga-related-api/24670/6

**Comment by Kcchouette** [comment]
With the new V3 API, it should be available. Now the goal is to find the documentation 😆

**Comment by z411** [comment]
It now supports manga through Kitsu.
