### ISSUE TITLE
Support for multiple media/watch directories

### ISSUE THREAD

**Issue by z411** [z411/trackma#89]

**Comment by SleepyMan** [comment]
The idea of having multiple media/watch directories is very nice. I have multiple HDD to store them, so this would be nice to have.

But wouldn't just recursive monitoring solve the problem of the root directory issue in a simpler way?
I mean, even if inotifyx does not provide this, it would be trivial to implement this.
On first add_watch, just add_watch for each subdir and react to create/delete directory to add_watch/rm_watch.

This would solve problems like downloading batches which are stored in their own directory, which would constantly requiring to add/remove media/watch directories.

**Comment by ToostInc** [comment]
Also having multiple HDD's myself, I'm interested if setting the media directory on root is indeed fa valid option. As far as I remember inotify has a set limit to how many files can be watched at the same time. This amount can technically be changed, but obviously not without cost, else the limit wouldn't be there.

For now I've got symlinks from one hard drive to the media folder on the other, but this does mean that every time I make a new folder in the first, I have to manually symlink it as well, if I want the folder to be recognized by Trackma.

**Comment by z411** [comment]
> setting the media directory on root is indeed fa valid option.

Watching the entire root directory is indeed unfeasible as per, as you say, inotify limitations. If you really want to do that disabling inotify and using polling is currently the only option.

>For now I've got symlinks from one hard drive to the media folder on the other, but this does mean that every time I make a new folder in the first, I have to manually symlink it as well

Yes, I think reacting to added or deleted directories is necessary. I'll definitely implement this.
