### ISSUE TITLE
Non-Linux systems?

### ISSUE THREAD

**Issue by Argon-** [z411/trackma#94]
There's no `procfs` on OSX and afaik not on Windows either. `procfs` is not even available on every UNIX system, deprecated on e.g. FreeBSD. What are they supposed to do?

**Comment by z411** [comment]
Oh, thanks for the heads up.

I did this because I wanted to get rid of the lsof dependency; I'll either have to work on several implementations or revert the change. I didn't know it wasn't available on OS X, and I thought it was available on FreeBSD but didn't know it was being deprecated. On Windows there isn't lsof either so we'd need a platform-specific implementation there anyway.

**Comment by Argon-** [comment]
Unfortunately this is something where I doubt one could get away without platform dependent code, therefore imo the best course of action might be passing the work completely on to some external library.

I just googled around a bit and did no tests myself yet, but this one came up: https://pypi.python.org/pypi/watchdog

> **Supported Platforms**
>    Linux 2.6 (inotify)
>    Mac OS X (FSEvents, kqueue)
>    FreeBSD/BSD (kqueue)
>    Windows (ReadDirectoryChangesW with I/O completion ports; ReadDirectoryChangesW worker threads)
>    OS-independent (polling the disk for directory snapshots and comparing them periodically; slow and not recommended)

This reads quite interesting and promising. However, it comes with quite a few dependencies on its own. Personally I wouldn't mind them, considering `pip` takes care of them anyway.

**Comment by z411** [comment]
For the time being I'll revert this (ebf2d9b794eafcfade948907ae8242f533355005) as to not to break things now, and work on a platform-specific implementation in the `no-lsof` branch. I'd like to work on a Win32 implementation there too.

**Comment by GRMrGecko** [comment]
If you need an OS X test subject, I can be one. I really need to play with perl some day to be able to help with projects such as this one. The main issue I have I guess is not undering how to debug in python. I can modify something having an understanding of other programming languages... But Without knowing how to debug, how can I figure out why my fix isn't working.

**Comment by z411** [comment]
Thank you. On Linux we already have inotify+procfs, and on Windows I can scan the window titles with EnumWindows/GetWindowText Win32 API functions. I'll eventually research a way to do this on the BSDs and OS X. If you know of anything please let me know. The very basic requirement is to be able to know what files are open by processes. An instant event notifier like Linux's inotify would be a plus.

**Comment by GRMrGecko** [comment]
I need to somewhat research what Inotify is.before I go about finding a solution for the mac. I thought at first that it was just watching the folder for events of changes, such as file saved/added/removed/renamed. I am a mac developer, so I can look into APIs and test them. I know there is a way to do it as, instruments/activity monitor does it.

It will be summer before I get around since I am at school full time and work full time.

**Comment by z411** [comment]
Yeah, most people need to watch directories for changed files, but in our special case we need events to know which files are opened and closed. But that's the ideal case to avoid polling anyway; anything that can tell us which files a process is using helps.

**Comment by GRMrGecko** [comment]
What I meant by a way to do it, I was referring to viewing what a program has open.

**Comment by z411** [comment]
Oh okay. Sorry, just making sure.

**Comment by GRMrGecko** [comment]
I was somewhat wondering what this program was doing by enumerating the whole media directory... I do not know if this is the right place to ask though.

**Comment by GRMrGecko** [comment]
What I expected this program to do is look for any file that is open by a program that has the extension of a media file.

**Comment by z411** [comment]
Yes, that's exactly what it does under non-Linux systems. It polls lsof after a certain interval.
Only under Linux it enumerates and watches media directories through the Linux's inotify API.

**Comment by Argon-** [comment]
OSX: https://developer.apple.com/library/mac/documentation/Darwin/Reference/FSEvents_Ref/index.html#//apple_ref/doc/c_ref/kFSEventStreamCreateFlagFileEvents
`kqueue` would work on both, BSD and OSX. However, I don't know about its capabilities.

**Comment by GRMrGecko** [comment]
@Argon- FSEvent is to watch a directory for changes. What we want to do is watch a PID for when it open files. I know there has to be an API somewhere... I can find it when I have the time.

See example of Activity Monitor doing this. ![Example](http://g.gec.im/ab5a729fef0d3cf90e5d716f021e9065.png)

**Comment by Argon-** [comment]
I guess I now what you mean. But for such an API you most likely have to know the process in order to query the necessary information? So you somehow have to watch for media players getting launched.

**Comment by GRMrGecko** [comment]
Watching for processes that launch is easy though.

**Comment by z411** [comment]
This is an old issue but I implemented the procfs method for pyinotify for now. This should remove the lsof dependency.

If the user is using pyinotify he must be in a Linux platform, which means using procfs should be safe.
